import type { Scope, TokenBudget } from "@hypermind/client";
import { buildContextSessions, inspectContext, renderContextSessionOptions } from "./context.js";
import { ConsoleDataError } from "./errors.js";
import { section, escapeText } from "./html.js";
import { operationalArray, operationalFacts, operationalInteger, operationalRecord, operationalReply, operationalScope, operationalText, OperationalRecord } from "./operations.js";
import { ConsoleEnvelope, ConsoleTransport } from "./transport.js";

export type ContinuityMode = "off" | "pass_through" | "shadow" | "primary";
export interface ContinuityView { scope: Scope; sessionId: string; generation: number; cursor: { epoch: number; sequence: number }; policy: { revision: number; mode: ContinuityMode; strict: boolean }; unsupportedParts: boolean; active: OperationalRecord | null; receipts: OperationalRecord; sequence: number; sourceCount: number; contextTokens: number }
export interface ContinuityDraft { mode: Exclude<ContinuityMode, "primary">; strict: boolean; revision: number; generation: number }
export interface ContinuityState { view?: ContinuityView; draft?: ContinuityDraft; notice: string; busy: boolean; pressure?: OperationalRecord }
export type ContinuityAction = { action: "inspect" } | { action: "configure"; mode: ContinuityMode; strict: boolean; expected_revision: number } | { action: "pressure"; budget: TokenBudget; required_ids: string[] } | { action: "cancel_hook"; trace_id: string };
function mode(value: unknown): ContinuityMode { const name = operationalText(value, "mode"); if (!["off", "pass_through", "shadow", "primary"].includes(name)) throw new ConsoleDataError("continuity", "mode"); return name as ContinuityMode; }
export function buildContinuityView(envelope: ConsoleEnvelope, sourceCount: number, contextTokens: number): ContinuityView {
  const v = operationalReply(envelope, "continuity"); if (v.version !== 1) throw new ConsoleDataError("continuity", "version");
  const policy = operationalRecord(v.policy, "policy"); const cursor = operationalRecord(v.cursor, "cursor");
  if (typeof policy.strict !== "boolean" || typeof v.unsupported_parts !== "boolean") throw new ConsoleDataError("continuity", "flags");
  return { scope: operationalScope(v.scope), sessionId: operationalText(v.session_id, "session_id"), generation: operationalInteger(v.generation, "generation"), policy: { revision: operationalInteger(policy.revision, "revision"), mode: mode(policy.mode), strict: policy.strict }, cursor: { epoch: operationalInteger(cursor.epoch, "epoch"), sequence: operationalInteger(cursor.sequence, "sequence") }, unsupportedParts: v.unsupported_parts, active: v.active_hook === null ? null : operationalRecord(v.active_hook, "active_hook"), receipts: operationalRecord(v.receipts, "receipts"), sequence: operationalInteger(v.sequence, "sequence"), sourceCount, contextTokens };
}
export async function continuityAction(transport: ConsoleTransport, actor: number, conversation: string, owner: Scope, sessionId: string, generation: number, action: ContinuityAction, requestId = `continuity-${globalThis.crypto.randomUUID()}`): Promise<ConsoleEnvelope> {
  if (action.action === "configure" && action.mode === "primary") throw new ConsoleDataError("continuity", "host capability", "Primary host dispatch authority is unavailable; native policy does not establish host refusal capability");
  const envelope = await transport.callTool("remember", { actor, conversation, kind: "user", content: "", context: { operation: "continuity", request: { version: 1, scope: owner, session_id: sessionId, request_id: requestId, expected_generation: generation, action } } });
  operationalReply(envelope, "continuity"); return envelope;
}
export async function inspectContinuity(transport: ConsoleTransport, actor: number, sessionId: string, conversation: string): Promise<ContinuityView> {
  const context = await inspectContext(transport, actor, sessionId);
  const history = operationalRecord(context.operations.history, "history");
  const envelope = await continuityAction(transport, actor, conversation, context.report.scope, sessionId, context.report.generation, { action: "inspect" });
  const view = buildContinuityView(envelope, operationalInteger(history.message_count, "message_count"), context.report.token_count);
  if (view.sessionId !== sessionId || view.generation !== context.report.generation || JSON.stringify(view.scope) !== JSON.stringify(context.report.scope)) throw new ConsoleDataError("continuity", "binding", "native session scope or generation changed during inspection");
  return view;
}
export async function submitContinuityDraft(state: ContinuityState, transport: ConsoleTransport, actor: number, conversation: string): Promise<boolean> {
  if (!state.view || !state.draft || state.busy) return false;
  const draft = state.draft; state.busy = true;
  try { await continuityAction(transport, actor, conversation, state.view.scope, state.view.sessionId, draft.generation, { action: "configure", mode: draft.mode, strict: draft.strict, expected_revision: draft.revision }); state.draft = undefined; state.notice = "Native mode policy recorded at a turn boundary."; return true; }
  catch (error) { state.notice = `Policy refused. The draft, expected revision and generation remain unchanged. ${error instanceof Error ? error.message : "native service unavailable"}`; return false; }
  finally { state.busy = false; }
}
function ticketFacts(ticket: OperationalRecord): string { const fence = operationalRecord(ticket.fence, "fence"); const source = operationalRecord(ticket.source, "source"); const budget = operationalRecord(ticket.budget, "budget"); return operationalFacts([["Trace", ticket.trace_id], ["Generation fence", fence.generation], ["Grant revision", fence.grant_revision], ["Profile revision digest", fence.profile_revision], ["Source history digest", source.history_digest], ["Rendered digest", ticket.rendered_digest], ["Context token ceiling", budget.context_tokens], ["Reserved output tokens", budget.reserved_output_tokens], ["Required tokens", budget.required_tokens]]); }
export function renderContinuity(view: ContinuityView): string {
  const receiptCards = Object.entries(view.receipts).map(([id, value]) => { const receipt = operationalRecord(value, "receipt"); return `<article class="context-card">${operationalFacts([["Request", id], ["Request digest", receipt.digest]])}</article>`; }).join("") || '<p>No continuity policy or hook receipts.</p>';
  return section("Session continuity", operationalFacts([["Session", view.sessionId], ["Owner", view.scope.owner_id], ["Project", view.scope.project_id], ["Native mode", view.policy.mode], ["Policy revision", view.policy.revision], ["Strict policy", view.policy.strict], ["Generation", view.generation], ["Source cursor", `${view.cursor.epoch}:${view.cursor.sequence}`], ["Source messages", view.sourceCount], ["Current context tokens", view.contextTokens], ["Unsupported source parts", view.unsupportedParts], ["Operation sequence", view.sequence]]) + '<p>Primary host dispatch is unavailable: native policy does not establish the host capability to refuse dispatch. This console cannot enable Primary.</p>' + section("Active native hook", view.active ? ticketFacts(view.active) + `<button type="button" data-hook-cancel="${escapeText(String(view.active.trace_id))}">Cancel native hook</button>` : '<p>No active native hook. Profile and budget fences are unavailable until a native hook or pressure plan reports them.</p>') + section("Continuity receipts", receiptCards));
}
export function renderContinuityPressure(value: OperationalRecord): string {
  const plan = value.plan === null ? null : operationalRecord(value.plan, "plan");
  if (!plan) return section("Pressure result", operationalFacts([["Mode", value.mode], ["Published", value.published], ["Provider input changed", value.provider_input_changed]]) + '<p>The native policy passed through provider input unchanged.</p>');
  const rendered = operationalRecord(plan.rendered, "rendered"); const report = operationalRecord(rendered.report, "report"); const budget = operationalRecord(plan.budget, "budget");
  return section("Pressure plan", operationalFacts([["Mode", value.mode], ["Published", value.published], ["Profile digest", plan.profile_digest], ["Rendered digest", report.digest], ["Generation", report.generation], ["Used tokens", report.token_count], ["Context token ceiling", budget.context_tokens], ["Reserved output tokens", budget.reserved_output_tokens], ["Required tokens", budget.required_tokens], ["Included blocks", operationalArray(report.included, "included").length], ["Omitted blocks", operationalArray(report.omitted, "omitted").length]]) + '<p>Source and rendered content remain hidden. This inspection does not dispatch provider input.</p>');
}
export function renderContinuityDraft(draft: ContinuityDraft): string {
  return `<form data-continuity-policy><label>Mode<select name="mode">${["off", "pass_through", "shadow"].map((m) => `<option value="${m}"${draft.mode === m ? " selected" : ""}>${m.replace(/_/g, " ")}</option>`).join("")}<option value="primary" disabled>Primary — host authority unavailable</option></select></label><label>Strict policy<input type="checkbox" name="strict"${draft.strict ? " checked" : ""} /></label>${operationalFacts([["Expected policy revision", draft.revision], ["Expected generation", draft.generation]])}<button type="submit">Record native mode policy</button></form>`;
}
export async function mountContinuity(mount: HTMLElement, transport: ConsoleTransport, actor: number, conversation: string): Promise<ContinuityState> {
  const state: ContinuityState = { notice: "", busy: false }; let selected = ""; let version = 0;
  const selector = document.createElement("select"); selector.setAttribute("aria-label", "Scoped continuity session"); selector.disabled = true;
  const refresh = document.createElement("button"); refresh.type = "button"; refresh.textContent = "Refresh continuity state";
  const body = document.createElement("div"); const notice = document.createElement("p"); notice.setAttribute("aria-live", "polite"); const draft = document.createElement("div"); const pressure = document.createElement("div");
  const budgetForm = document.createElement("form"); budgetForm.innerHTML = '<label>Context token ceiling<input name="context" type="number" min="1" required /></label><label>Reserved output tokens<input name="output" type="number" min="1" required /></label><label>Required tokens<input name="required" type="number" min="0" required /></label><button type="submit" disabled>Inspect pressure plan</button>';
  mount.append(selector, refresh, notice, body, draft, budgetForm, pressure);
  const paint = () => { notice.textContent = state.notice; draft.innerHTML = state.draft ? renderContinuityDraft(state.draft) : ""; };
  const load = async () => { if (!selected) return; const current = ++version; try { const view = await inspectContinuity(transport, actor, selected, conversation); if (current !== version) return; state.view = view; body.innerHTML = renderContinuity(view); if (!state.draft) state.draft = { mode: view.policy.mode === "primary" ? "off" : view.policy.mode, strict: view.policy.strict, revision: view.policy.revision, generation: view.generation }; const button = budgetForm.querySelector<HTMLButtonElement>("button"); if (button) button.disabled = view.unsupportedParts; } catch (error) { state.notice = `Continuity unavailable: ${error instanceof Error ? error.message : "inspection failed"}`; } paint(); };
  refresh.addEventListener("click", () => { void load(); });
  selector.addEventListener("change", () => { if (state.draft && state.view && (state.draft.mode !== state.view.policy.mode || state.draft.strict !== state.view.policy.strict)) { state.notice = "Record or resolve the existing policy draft before selecting another session."; selector.value = selected; paint(); return; } selected = selector.value; state.draft = undefined; state.pressure = undefined; pressure.textContent = ""; void load(); });
  draft.addEventListener("input", (event) => { if (!state.draft) return; const target = event.target as HTMLInputElement; if (target.name === "mode" && ["off", "pass_through", "shadow"].includes(target.value)) state.draft.mode = target.value as ContinuityDraft["mode"]; if (target.name === "strict") state.draft.strict = target.checked; });
  draft.addEventListener("submit", (event) => { event.preventDefault(); void submitContinuityDraft(state, transport, actor, conversation).then((accepted) => { paint(); if (accepted) void load(); }); });
  budgetForm.addEventListener("submit", (event) => { event.preventDefault(); if (!state.view || state.busy) return; const values = new FormData(budgetForm); state.busy = true; void continuityAction(transport, actor, conversation, state.view.scope, state.view.sessionId, state.view.generation, { action: "pressure", budget: { context_tokens: Number(values.get("context")), reserved_output_tokens: Number(values.get("output")), required_tokens: Number(values.get("required")) }, required_ids: [] }).then((reply) => { state.pressure = operationalReply(reply, "continuity"); pressure.innerHTML = renderContinuityPressure(state.pressure); state.notice = "Native pressure inspection completed."; }).catch((error) => { state.notice = `Pressure refused. Budget draft preserved. ${error instanceof Error ? error.message : "unavailable"}`; }).finally(() => { state.busy = false; paint(); }); });
  body.addEventListener("click", (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>("[data-hook-cancel]"); if (!button || !state.view || state.busy) return; state.busy = true; void continuityAction(transport, actor, conversation, state.view.scope, state.view.sessionId, state.view.generation, { action: "cancel_hook", trace_id: button.dataset.hookCancel! }).then(() => { state.notice = "Native hook cancelled."; }).catch((error) => { state.notice = `Hook cancellation refused: ${error instanceof Error ? error.message : "unavailable"}`; }).finally(() => { state.busy = false; void load(); }); });
  try { const sessions = buildContextSessions(await transport.callTool("inspect", { uri: `hm://${actor}/context` })); selector.innerHTML = sessions.length ? renderContextSessionOptions(sessions) : '<option>No scoped sessions available</option>'; selector.disabled = sessions.length === 0; if (sessions.length) { selected = sessions[0].session_id; await load(); } else notice.textContent = "Create a bound scoped session before inspecting continuity."; } catch (error) { notice.textContent = `Scoped sessions unavailable: ${error instanceof Error ? error.message : "inspection failed"}`; }
  return state;
}
