import assert from "node:assert/strict";
import test from "node:test";
import { spawn, execFile } from "node:child_process";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { promisify } from "node:util";
import { createHash } from "node:crypto";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { Client, Scope } from "@hypermind/client";
import { clientTransport } from "./node-transport.js";
import { dispatchDigest, inspectOperations, operationsAction, operationalRecord, renderOperations } from "./operations.js";
import { exerciseNativeContinuity } from "./continuity.test.js";

const exec = promisify(execFile);
const pause = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

test("console consumes selected native fabric and continuity through actual daemon transport", async (context) => {
  assert.ok(process.env.HM_DAEMON_BIN, "supply the current native daemon binary");
  assert.ok(process.env.HM_FABRIC_CONFIG, "supply a trusted fabric descriptor template");
  const template = JSON.parse(await readFile(process.env.HM_FABRIC_CONFIG, "utf8")) as { actor: number; backend: { scope: Scope; home: { path: string } }; worker: { command: string; cwd: string } };
  const directory = await mkdtemp(path.join(os.tmpdir(), "hypermind-console-operational-"));
  const home = path.join(directory, "backend"); await mkdir(home);
  template.backend.home.path = home; template.worker.cwd = home; template.worker.command = process.env.HM_DAEMON_BIN;
  const fabric = path.join(directory, "fabric.json"); const binding = path.join(directory, "scope.json"); const config = path.join(directory, "server.conf"); const socket = path.join(directory, "daemon.sock");
  const actor = template.actor; const scope = template.backend.scope; const token = "44".repeat(32);
  await writeFile(fabric, JSON.stringify(template), { mode: 0o600 });
  await writeFile(binding, JSON.stringify({ version: 1, actor, scope }), { mode: 0o600 });
  await writeFile(config, [`socket=${socket}`, `data=${path.join(directory, "data")}`, `user=${"11".repeat(16)}`, `kek=${"22".repeat(32)}`, `admin_token=${"33".repeat(32)}`, `actor=${actor}:${token}`, "projection_map_bytes=67108864", ""].join("\n"), { mode: 0o600 });
  let stderr = "";
  const daemon = spawn(process.env.HM_DAEMON_BIN, ["serve", "--config", config, "--context-scope", binding], { stdio: ["ignore", "ignore", "pipe"], env: { ...process.env, HM_FABRIC_CONFIG: fabric, HM_DEVELOPMENT_PROVIDER: "off", HM_RECONSTRUCTION_PROVIDER: "" } });
  daemon.stderr.on("data", (chunk) => { stderr += String(chunk); });
  let workerPid: number | undefined;
  let client: Client | undefined;
  let controlClient: Client | undefined;
  context.after(async () => { if (client) await client.close(); if (controlClient) await controlClient.close(); if (workerPid) { try { process.kill(workerPid, "SIGCONT"); } catch {} } if (daemon.exitCode === null) { daemon.kill("SIGINT"); await new Promise<void>((resolve) => daemon.once("exit", () => resolve())); } await rm(directory, { recursive: true, force: true }); });
  let ready = false;
  for (let attempt = 0; attempt < 300; attempt++) { try { const probe = net.createConnection(socket); await new Promise<void>((resolve, reject) => { probe.once("connect", resolve); probe.once("error", reject); }); probe.destroy(); ready = true; break; } catch { if (daemon.exitCode !== null) break; await pause(20); } }
  assert.ok(ready, `actual daemon did not start: ${stderr}`);
  client = await Client.connect({ socketPath: socket, capabilityToken: Buffer.from(token, "hex"), connectionId: Buffer.alloc(16, 9) });
  const transport = clientTransport(client);
  controlClient = await Client.connect({ socketPath: socket, capabilityToken: Buffer.from(token, "hex"), connectionId: Buffer.alloc(16, 10) });
  const control = clientTransport(controlClient);
  const initial = await inspectOperations(transport, actor);
  assert.equal(initial.backend.operational_backend, "sqlite");
  assert.equal(initial.families.find((f) => f.family === "digest_worker")?.available, true);
  assert.equal(initial.families.find((f) => f.family === "model_runner")?.available, false);
  assert.ok(renderOperations(initial).includes("Selected operational backend"));
  const text = "An actual native digest operation.";
  const result = await dispatchDigest(transport, actor, initial, text, 10000, "console-digest");
  assert.equal(operationalRecord(result.result, "result").digest, createHash("sha256").update(text).digest("hex"));
  const completed = await inspectOperations(transport, actor);
  assert.ok(completed.receipts?.some((r) => operationalRecord(r.intent, "intent").state === "terminal"));
  assert.equal(renderOperations(completed).includes(text), false);
  await assert.rejects(() => operationsAction(transport, actor, scope, { action: "cancel", effect_id: "missing-effect" }, "cancel-missing"));
  const unsupported = await transport.callTool("remember", { conversation: "fabric", kind: "user", content: "", context: { operation: "fabric", request: { version: 1, scope, request_id: "unsupported-operation", action: { action: "dispatch", operation: "model_runner", bytes: [], timeout_ms: 1000 } } } });
  assert.equal(unsupported.ok, false);
  const evidence = await transport.callTool("remember", { conversation: "fabric", kind: "user", content: "", context: { operation: "fabric", request: { version: 1, scope, request_id: "untrusted-evidence", action: { action: "reconcile", effect_id: "console-digest", evidence: "caller supplied" } } } });
  assert.equal(evidence.ok, false);
  await exerciseNativeContinuity(transport, actor, scope);
  assert.ok(daemon.pid);
  const children = await exec("ps", ["-o", "pid=,args=", "--ppid", String(daemon.pid)]);
  const worker = children.stdout.split("\n").find((line) => line.includes("fabric-worker"));
  assert.ok(worker, "the actual owned digest worker is running");
  workerPid = Number(worker.trim().split(/\s+/)[0]);
  process.kill(workerPid, "SIGSTOP");
  const activeRequest = dispatchDigest(transport, actor, completed, "Cancel this actual owned digest request", 10000, "console-cancelled").then(() => "succeeded", () => "refused");
  let active = await inspectOperations(control, actor);
  for (let attempt = 0; attempt < 100 && (active.active?.id !== "console-cancelled" || !["prepared", "dispatched"].includes(String(active.active?.phase))); attempt++) { await pause(10); active = await inspectOperations(control, actor); }
  assert.equal(active.active?.id, "console-cancelled");
  assert.ok(["prepared", "dispatched"].includes(String(active.active?.phase)));
  assert.equal(active.busy, true);
  assert.equal(active.receiptsAvailable, false);
  const cancelled = await operationsAction(control, actor, scope, { action: "cancel", effect_id: "console-cancelled" }, "console-cancel");
  assert.equal(cancelled.worker_stopped, true);
  assert.equal(cancelled.automatic_replay, false);
  assert.equal(await activeRequest, "refused");
  const uncertain = await inspectOperations(transport, actor);
  assert.equal(uncertain.families.find((f) => f.family === "digest_worker")?.available, false);
  assert.ok(uncertain.receipts?.some((r) => operationalRecord(r.intent, "intent").state === "uncertain"));
  assert.ok(renderOperations(uncertain).includes("Automatic replay is blocked"));
  await assert.rejects(() => operationsAction(transport, actor, scope, { action: "reconcile", effect_id: "console-cancelled" }, "console-reconcile"));
});
