// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type AttentionDecided struct {
	_tab flatbuffers.Table
}

func GetRootAsAttentionDecided(buf []byte, offset flatbuffers.UOffsetT) *AttentionDecided {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AttentionDecided{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAttentionDecided(buf []byte, offset flatbuffers.UOffsetT) *AttentionDecided {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AttentionDecided{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AttentionDecided) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AttentionDecided) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AttentionDecided) IntentionId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *AttentionDecided) IntentionIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AttentionDecided) IntentionIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AttentionDecided) MutateIntentionId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *AttentionDecided) WakeId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *AttentionDecided) WakeIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AttentionDecided) WakeIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AttentionDecided) MutateWakeId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *AttentionDecided) Decision() AttentionDecision {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return AttentionDecision(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *AttentionDecided) MutateDecision(n AttentionDecision) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *AttentionDecided) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AttentionDecidedStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func AttentionDecidedAddIntentionId(builder *flatbuffers.Builder, intentionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(intentionId), 0)
}
func AttentionDecidedStartIntentionIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AttentionDecidedAddWakeId(builder *flatbuffers.Builder, wakeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(wakeId), 0)
}
func AttentionDecidedStartWakeIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AttentionDecidedAddDecision(builder *flatbuffers.Builder, decision AttentionDecision) {
	builder.PrependByteSlot(2, byte(decision), 0)
}
func AttentionDecidedAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(reason), 0)
}
func AttentionDecidedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
