// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type Authority byte

const (
	Authorityuser_asserted       Authority = 0
	Authorityexternal_observed   Authority = 1
	Authoritytool_observed       Authority = 2
	Authorityruntime_fact        Authority = 3
	Authorityassistant_generated Authority = 4
	Authorityderived_inference   Authority = 5
)

var EnumNamesAuthority = map[Authority]string{
	Authorityuser_asserted:       "user_asserted",
	Authorityexternal_observed:   "external_observed",
	Authoritytool_observed:       "tool_observed",
	Authorityruntime_fact:        "runtime_fact",
	Authorityassistant_generated: "assistant_generated",
	Authorityderived_inference:   "derived_inference",
}

var EnumValuesAuthority = map[string]Authority{
	"user_asserted":       Authorityuser_asserted,
	"external_observed":   Authorityexternal_observed,
	"tool_observed":       Authoritytool_observed,
	"runtime_fact":        Authorityruntime_fact,
	"assistant_generated": Authorityassistant_generated,
	"derived_inference":   Authorityderived_inference,
}

func (v Authority) String() string {
	if s, ok := EnumNamesAuthority[v]; ok {
		return s
	}
	return "Authority(" + strconv.FormatInt(int64(v), 10) + ")"
}
