// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ConsolidationBudget struct {
	_tab flatbuffers.Table
}

func GetRootAsConsolidationBudget(buf []byte, offset flatbuffers.UOffsetT) *ConsolidationBudget {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsolidationBudget{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConsolidationBudget(buf []byte, offset flatbuffers.UOffsetT) *ConsolidationBudget {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConsolidationBudget{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConsolidationBudget) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsolidationBudget) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsolidationBudget) MaxLlmCalls() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationBudget) MutateMaxLlmCalls(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ConsolidationBudget) MaxTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationBudget) MutateMaxTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *ConsolidationBudget) MaxMicrousd() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationBudget) MutateMaxMicrousd(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *ConsolidationBudget) MaxWallMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationBudget) MutateMaxWallMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func ConsolidationBudgetStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ConsolidationBudgetAddMaxLlmCalls(builder *flatbuffers.Builder, maxLlmCalls uint64) {
	builder.PrependUint64Slot(0, maxLlmCalls, 0)
}
func ConsolidationBudgetAddMaxTokens(builder *flatbuffers.Builder, maxTokens uint64) {
	builder.PrependUint64Slot(1, maxTokens, 0)
}
func ConsolidationBudgetAddMaxMicrousd(builder *flatbuffers.Builder, maxMicrousd uint64) {
	builder.PrependUint64Slot(2, maxMicrousd, 0)
}
func ConsolidationBudgetAddMaxWallMs(builder *flatbuffers.Builder, maxWallMs uint64) {
	builder.PrependUint64Slot(3, maxWallMs, 0)
}
func ConsolidationBudgetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
