// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ConsolidationRetracted struct {
	_tab flatbuffers.Table
}

func GetRootAsConsolidationRetracted(buf []byte, offset flatbuffers.UOffsetT) *ConsolidationRetracted {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsolidationRetracted{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConsolidationRetracted(buf []byte, offset flatbuffers.UOffsetT) *ConsolidationRetracted {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConsolidationRetracted{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConsolidationRetracted) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsolidationRetracted) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsolidationRetracted) TargetRunId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ConsolidationRetracted) TargetRunIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConsolidationRetracted) TargetRunIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConsolidationRetracted) MutateTargetRunId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ConsolidationRetracted) PreviousGeneration() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationRetracted) MutatePreviousGeneration(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *ConsolidationRetracted) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConsolidationRetractedStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ConsolidationRetractedAddTargetRunId(builder *flatbuffers.Builder, targetRunId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetRunId), 0)
}
func ConsolidationRetractedStartTargetRunIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ConsolidationRetractedAddPreviousGeneration(builder *flatbuffers.Builder, previousGeneration uint64) {
	builder.PrependUint64Slot(1, previousGeneration, 0)
}
func ConsolidationRetractedAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(reason), 0)
}
func ConsolidationRetractedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
