// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ConsolidationClosed struct {
	_tab flatbuffers.Table
}

func GetRootAsConsolidationClosed(buf []byte, offset flatbuffers.UOffsetT) *ConsolidationClosed {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsolidationClosed{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConsolidationClosed(buf []byte, offset flatbuffers.UOffsetT) *ConsolidationClosed {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConsolidationClosed{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConsolidationClosed) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsolidationClosed) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsolidationClosed) Generation() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationClosed) MutateGeneration(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ConsolidationClosed) ExpectedActiveGeneration() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationClosed) MutateExpectedActiveGeneration(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *ConsolidationClosed) DerivedRecords() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationClosed) MutateDerivedRecords(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *ConsolidationClosed) DroppedCandidates() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationClosed) MutateDroppedCandidates(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *ConsolidationClosed) LlmCalls() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationClosed) MutateLlmCalls(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *ConsolidationClosed) InputTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationClosed) MutateInputTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *ConsolidationClosed) OutputTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationClosed) MutateOutputTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *ConsolidationClosed) CostMicrousd() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationClosed) MutateCostMicrousd(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func ConsolidationClosedStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func ConsolidationClosedAddGeneration(builder *flatbuffers.Builder, generation uint64) {
	builder.PrependUint64Slot(0, generation, 0)
}
func ConsolidationClosedAddExpectedActiveGeneration(builder *flatbuffers.Builder, expectedActiveGeneration uint64) {
	builder.PrependUint64Slot(1, expectedActiveGeneration, 0)
}
func ConsolidationClosedAddDerivedRecords(builder *flatbuffers.Builder, derivedRecords uint64) {
	builder.PrependUint64Slot(2, derivedRecords, 0)
}
func ConsolidationClosedAddDroppedCandidates(builder *flatbuffers.Builder, droppedCandidates uint64) {
	builder.PrependUint64Slot(3, droppedCandidates, 0)
}
func ConsolidationClosedAddLlmCalls(builder *flatbuffers.Builder, llmCalls uint64) {
	builder.PrependUint64Slot(4, llmCalls, 0)
}
func ConsolidationClosedAddInputTokens(builder *flatbuffers.Builder, inputTokens uint64) {
	builder.PrependUint64Slot(5, inputTokens, 0)
}
func ConsolidationClosedAddOutputTokens(builder *flatbuffers.Builder, outputTokens uint64) {
	builder.PrependUint64Slot(6, outputTokens, 0)
}
func ConsolidationClosedAddCostMicrousd(builder *flatbuffers.Builder, costMicrousd uint64) {
	builder.PrependUint64Slot(7, costMicrousd, 0)
}
func ConsolidationClosedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
