// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type ConsolidationPhaseName byte

const (
	ConsolidationPhaseNamenrem      ConsolidationPhaseName = 0
	ConsolidationPhaseNameconnect   ConsolidationPhaseName = 1
	ConsolidationPhaseNameabstract  ConsolidationPhaseName = 2
	ConsolidationPhaseNamehindsight ConsolidationPhaseName = 3
	ConsolidationPhaseNamereview    ConsolidationPhaseName = 4
	ConsolidationPhaseNamepublish   ConsolidationPhaseName = 5
)

var EnumNamesConsolidationPhaseName = map[ConsolidationPhaseName]string{
	ConsolidationPhaseNamenrem:      "nrem",
	ConsolidationPhaseNameconnect:   "connect",
	ConsolidationPhaseNameabstract:  "abstract",
	ConsolidationPhaseNamehindsight: "hindsight",
	ConsolidationPhaseNamereview:    "review",
	ConsolidationPhaseNamepublish:   "publish",
}

var EnumValuesConsolidationPhaseName = map[string]ConsolidationPhaseName{
	"nrem":      ConsolidationPhaseNamenrem,
	"connect":   ConsolidationPhaseNameconnect,
	"abstract":  ConsolidationPhaseNameabstract,
	"hindsight": ConsolidationPhaseNamehindsight,
	"review":    ConsolidationPhaseNamereview,
	"publish":   ConsolidationPhaseNamepublish,
}

func (v ConsolidationPhaseName) String() string {
	if s, ok := EnumNamesConsolidationPhaseName[v]; ok {
		return s
	}
	return "ConsolidationPhaseName(" + strconv.FormatInt(int64(v), 10) + ")"
}
