// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ConsolidationPhase struct {
	_tab flatbuffers.Table
}

func GetRootAsConsolidationPhase(buf []byte, offset flatbuffers.UOffsetT) *ConsolidationPhase {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsolidationPhase{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConsolidationPhase(buf []byte, offset flatbuffers.UOffsetT) *ConsolidationPhase {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConsolidationPhase{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConsolidationPhase) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsolidationPhase) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsolidationPhase) Phase() ConsolidationPhaseName {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ConsolidationPhaseName(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ConsolidationPhase) MutatePhase(n ConsolidationPhaseName) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ConsolidationPhase) State() ConsolidationPhaseState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ConsolidationPhaseState(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ConsolidationPhase) MutateState(n ConsolidationPhaseState) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *ConsolidationPhase) AttemptPrefix(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ConsolidationPhase) AttemptPrefixLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConsolidationPhase) AttemptPrefixBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConsolidationPhase) MutateAttemptPrefix(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ConsolidationPhase) Cursor(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ConsolidationPhase) CursorLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConsolidationPhase) CursorBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConsolidationPhase) MutateCursor(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ConsolidationPhase) LlmCalls() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationPhase) MutateLlmCalls(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *ConsolidationPhase) InputTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationPhase) MutateInputTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *ConsolidationPhase) OutputTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationPhase) MutateOutputTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *ConsolidationPhase) CostMicrousd() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationPhase) MutateCostMicrousd(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func (rcv *ConsolidationPhase) DroppedCandidates() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsolidationPhase) MutateDroppedCandidates(n uint64) bool {
	return rcv._tab.MutateUint64Slot(20, n)
}

func ConsolidationPhaseStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func ConsolidationPhaseAddPhase(builder *flatbuffers.Builder, phase ConsolidationPhaseName) {
	builder.PrependByteSlot(0, byte(phase), 0)
}
func ConsolidationPhaseAddState(builder *flatbuffers.Builder, state ConsolidationPhaseState) {
	builder.PrependByteSlot(1, byte(state), 0)
}
func ConsolidationPhaseAddAttemptPrefix(builder *flatbuffers.Builder, attemptPrefix flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(attemptPrefix), 0)
}
func ConsolidationPhaseStartAttemptPrefixVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ConsolidationPhaseAddCursor(builder *flatbuffers.Builder, cursor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(cursor), 0)
}
func ConsolidationPhaseStartCursorVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ConsolidationPhaseAddLlmCalls(builder *flatbuffers.Builder, llmCalls uint64) {
	builder.PrependUint64Slot(4, llmCalls, 0)
}
func ConsolidationPhaseAddInputTokens(builder *flatbuffers.Builder, inputTokens uint64) {
	builder.PrependUint64Slot(5, inputTokens, 0)
}
func ConsolidationPhaseAddOutputTokens(builder *flatbuffers.Builder, outputTokens uint64) {
	builder.PrependUint64Slot(6, outputTokens, 0)
}
func ConsolidationPhaseAddCostMicrousd(builder *flatbuffers.Builder, costMicrousd uint64) {
	builder.PrependUint64Slot(7, costMicrousd, 0)
}
func ConsolidationPhaseAddDroppedCandidates(builder *flatbuffers.Builder, droppedCandidates uint64) {
	builder.PrependUint64Slot(8, droppedCandidates, 0)
}
func ConsolidationPhaseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
