// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type ConsolidationPhaseState byte

const (
	ConsolidationPhaseStatestarted   ConsolidationPhaseState = 0
	ConsolidationPhaseStatecompleted ConsolidationPhaseState = 1
	ConsolidationPhaseStateaborted   ConsolidationPhaseState = 2
)

var EnumNamesConsolidationPhaseState = map[ConsolidationPhaseState]string{
	ConsolidationPhaseStatestarted:   "started",
	ConsolidationPhaseStatecompleted: "completed",
	ConsolidationPhaseStateaborted:   "aborted",
}

var EnumValuesConsolidationPhaseState = map[string]ConsolidationPhaseState{
	"started":   ConsolidationPhaseStatestarted,
	"completed": ConsolidationPhaseStatecompleted,
	"aborted":   ConsolidationPhaseStateaborted,
}

func (v ConsolidationPhaseState) String() string {
	if s, ok := EnumNamesConsolidationPhaseState[v]; ok {
		return s
	}
	return "ConsolidationPhaseState(" + strconv.FormatInt(int64(v), 10) + ")"
}
