// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type EventEnvelope struct {
	_tab flatbuffers.Table
}

func GetRootAsEventEnvelope(buf []byte, offset flatbuffers.UOffsetT) *EventEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EventEnvelope{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsEventEnvelope(buf []byte, offset flatbuffers.UOffsetT) *EventEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EventEnvelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *EventEnvelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EventEnvelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EventEnvelope) SchemaVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *EventEnvelope) MutateSchemaVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *EventEnvelope) PayloadType() EventPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return EventPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EventEnvelope) MutatePayloadType(n EventPayload) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *EventEnvelope) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *EventEnvelope) ConnectionId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *EventEnvelope) ConnectionIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *EventEnvelope) ConnectionIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EventEnvelope) MutateConnectionId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *EventEnvelope) ClientSeq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEnvelope) MutateClientSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *EventEnvelope) ClientEventIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEnvelope) MutateClientEventIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *EventEnvelope) ClientEventCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEnvelope) MutateClientEventCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *EventEnvelope) OriginActor() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEnvelope) MutateOriginActor(n uint16) bool {
	return rcv._tab.MutateUint16Slot(18, n)
}

func (rcv *EventEnvelope) RunId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *EventEnvelope) RunIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *EventEnvelope) RunIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EventEnvelope) MutateRunId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *EventEnvelope) ModelProvenance(obj *ModelProvenance) *ModelProvenance {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ModelProvenance)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *EventEnvelope) Authority() Authority {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return Authority(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EventEnvelope) MutateAuthority(n Authority) bool {
	return rcv._tab.MutateByteSlot(24, byte(n))
}

func (rcv *EventEnvelope) Retention() Retention {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return Retention(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EventEnvelope) MutateRetention(n Retention) bool {
	return rcv._tab.MutateByteSlot(26, byte(n))
}

func (rcv *EventEnvelope) Sensitivity() Sensitivity {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return Sensitivity(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EventEnvelope) MutateSensitivity(n Sensitivity) bool {
	return rcv._tab.MutateByteSlot(28, byte(n))
}

func (rcv *EventEnvelope) EventTimeNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEnvelope) MutateEventTimeNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(30, n)
}

func EventEnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(14)
}
func EventEnvelopeAddSchemaVersion(builder *flatbuffers.Builder, schemaVersion uint16) {
	builder.PrependUint16Slot(0, schemaVersion, 1)
}
func EventEnvelopeAddPayloadType(builder *flatbuffers.Builder, payloadType EventPayload) {
	builder.PrependByteSlot(1, byte(payloadType), 0)
}
func EventEnvelopeAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(payload), 0)
}
func EventEnvelopeAddConnectionId(builder *flatbuffers.Builder, connectionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(connectionId), 0)
}
func EventEnvelopeStartConnectionIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func EventEnvelopeAddClientSeq(builder *flatbuffers.Builder, clientSeq uint64) {
	builder.PrependUint64Slot(4, clientSeq, 0)
}
func EventEnvelopeAddClientEventIndex(builder *flatbuffers.Builder, clientEventIndex uint32) {
	builder.PrependUint32Slot(5, clientEventIndex, 0)
}
func EventEnvelopeAddClientEventCount(builder *flatbuffers.Builder, clientEventCount uint32) {
	builder.PrependUint32Slot(6, clientEventCount, 0)
}
func EventEnvelopeAddOriginActor(builder *flatbuffers.Builder, originActor uint16) {
	builder.PrependUint16Slot(7, originActor, 0)
}
func EventEnvelopeAddRunId(builder *flatbuffers.Builder, runId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(runId), 0)
}
func EventEnvelopeStartRunIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func EventEnvelopeAddModelProvenance(builder *flatbuffers.Builder, modelProvenance flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(modelProvenance), 0)
}
func EventEnvelopeAddAuthority(builder *flatbuffers.Builder, authority Authority) {
	builder.PrependByteSlot(10, byte(authority), 0)
}
func EventEnvelopeAddRetention(builder *flatbuffers.Builder, retention Retention) {
	builder.PrependByteSlot(11, byte(retention), 0)
}
func EventEnvelopeAddSensitivity(builder *flatbuffers.Builder, sensitivity Sensitivity) {
	builder.PrependByteSlot(12, byte(sensitivity), 0)
}
func EventEnvelopeAddEventTimeNs(builder *flatbuffers.Builder, eventTimeNs int64) {
	builder.PrependInt64Slot(13, eventTimeNs, 0)
}
func EventEnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
