// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type IntentionCancelled struct {
	_tab flatbuffers.Table
}

func GetRootAsIntentionCancelled(buf []byte, offset flatbuffers.UOffsetT) *IntentionCancelled {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IntentionCancelled{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsIntentionCancelled(buf []byte, offset flatbuffers.UOffsetT) *IntentionCancelled {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IntentionCancelled{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *IntentionCancelled) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IntentionCancelled) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IntentionCancelled) IntentionId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *IntentionCancelled) IntentionIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *IntentionCancelled) IntentionIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *IntentionCancelled) MutateIntentionId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *IntentionCancelled) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func IntentionCancelledStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func IntentionCancelledAddIntentionId(builder *flatbuffers.Builder, intentionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(intentionId), 0)
}
func IntentionCancelledStartIntentionIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func IntentionCancelledAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reason), 0)
}
func IntentionCancelledEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
