// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type MemoryFaded struct {
	_tab flatbuffers.Table
}

func GetRootAsMemoryFaded(buf []byte, offset flatbuffers.UOffsetT) *MemoryFaded {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MemoryFaded{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMemoryFaded(buf []byte, offset flatbuffers.UOffsetT) *MemoryFaded {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MemoryFaded{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MemoryFaded) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MemoryFaded) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MemoryFaded) MemoryId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MemoryFaded) MemoryIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MemoryFaded) MemoryIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MemoryFaded) MutateMemoryId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MemoryFaded) Reason() MemoryFadeReason {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return MemoryFadeReason(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MemoryFaded) MutateReason(n MemoryFadeReason) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *MemoryFaded) EvidenceLsns(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *MemoryFaded) EvidenceLsnsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MemoryFaded) MutateEvidenceLsns(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func MemoryFadedStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MemoryFadedAddMemoryId(builder *flatbuffers.Builder, memoryId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(memoryId), 0)
}
func MemoryFadedStartMemoryIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MemoryFadedAddReason(builder *flatbuffers.Builder, reason MemoryFadeReason) {
	builder.PrependByteSlot(1, byte(reason), 0)
}
func MemoryFadedAddEvidenceLsns(builder *flatbuffers.Builder, evidenceLsns flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(evidenceLsns), 0)
}
func MemoryFadedStartEvidenceLsnsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func MemoryFadedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
