// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ModelProvenance struct {
	_tab flatbuffers.Table
}

func GetRootAsModelProvenance(buf []byte, offset flatbuffers.UOffsetT) *ModelProvenance {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ModelProvenance{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsModelProvenance(buf []byte, offset flatbuffers.UOffsetT) *ModelProvenance {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ModelProvenance{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ModelProvenance) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ModelProvenance) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ModelProvenance) ModelId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ModelProvenance) PromptId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ModelProvenance) PromptVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ModelProvenance) MutatePromptVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *ModelProvenance) Temperature() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ModelProvenance) MutateTemperature(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *ModelProvenance) CallId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ModelProvenance) CallIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ModelProvenance) CallIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ModelProvenance) MutateCallId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ModelProvenance) InputTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ModelProvenance) MutateInputTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *ModelProvenance) OutputTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ModelProvenance) MutateOutputTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *ModelProvenance) CacheReadTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ModelProvenance) MutateCacheReadTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func (rcv *ModelProvenance) CacheWriteTokens() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ModelProvenance) MutateCacheWriteTokens(n uint64) bool {
	return rcv._tab.MutateUint64Slot(20, n)
}

func (rcv *ModelProvenance) CostMicrousd() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ModelProvenance) MutateCostMicrousd(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func ModelProvenanceStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func ModelProvenanceAddModelId(builder *flatbuffers.Builder, modelId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(modelId), 0)
}
func ModelProvenanceAddPromptId(builder *flatbuffers.Builder, promptId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(promptId), 0)
}
func ModelProvenanceAddPromptVersion(builder *flatbuffers.Builder, promptVersion uint16) {
	builder.PrependUint16Slot(2, promptVersion, 0)
}
func ModelProvenanceAddTemperature(builder *flatbuffers.Builder, temperature float32) {
	builder.PrependFloat32Slot(3, temperature, 0.0)
}
func ModelProvenanceAddCallId(builder *flatbuffers.Builder, callId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(callId), 0)
}
func ModelProvenanceStartCallIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ModelProvenanceAddInputTokens(builder *flatbuffers.Builder, inputTokens uint64) {
	builder.PrependUint64Slot(5, inputTokens, 0)
}
func ModelProvenanceAddOutputTokens(builder *flatbuffers.Builder, outputTokens uint64) {
	builder.PrependUint64Slot(6, outputTokens, 0)
}
func ModelProvenanceAddCacheReadTokens(builder *flatbuffers.Builder, cacheReadTokens uint64) {
	builder.PrependUint64Slot(7, cacheReadTokens, 0)
}
func ModelProvenanceAddCacheWriteTokens(builder *flatbuffers.Builder, cacheWriteTokens uint64) {
	builder.PrependUint64Slot(8, cacheWriteTokens, 0)
}
func ModelProvenanceAddCostMicrousd(builder *flatbuffers.Builder, costMicrousd uint64) {
	builder.PrependUint64Slot(9, costMicrousd, 0)
}
func ModelProvenanceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
