// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type OutcomeObserved struct {
	_tab flatbuffers.Table
}

func GetRootAsOutcomeObserved(buf []byte, offset flatbuffers.UOffsetT) *OutcomeObserved {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OutcomeObserved{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsOutcomeObserved(buf []byte, offset flatbuffers.UOffsetT) *OutcomeObserved {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OutcomeObserved{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *OutcomeObserved) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OutcomeObserved) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OutcomeObserved) PredictionId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *OutcomeObserved) PredictionIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *OutcomeObserved) PredictionIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OutcomeObserved) MutatePredictionId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *OutcomeObserved) Revision() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OutcomeObserved) MutateRevision(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *OutcomeObserved) Assessment() OutcomeAssessment {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return OutcomeAssessment(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OutcomeObserved) MutateAssessment(n OutcomeAssessment) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *OutcomeObserved) ObservationLsns(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *OutcomeObserved) ObservationLsnsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *OutcomeObserved) MutateObservationLsns(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *OutcomeObserved) EvaluatorVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func OutcomeObservedStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func OutcomeObservedAddPredictionId(builder *flatbuffers.Builder, predictionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(predictionId), 0)
}
func OutcomeObservedStartPredictionIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func OutcomeObservedAddRevision(builder *flatbuffers.Builder, revision uint32) {
	builder.PrependUint32Slot(1, revision, 0)
}
func OutcomeObservedAddAssessment(builder *flatbuffers.Builder, assessment OutcomeAssessment) {
	builder.PrependByteSlot(2, byte(assessment), 0)
}
func OutcomeObservedAddObservationLsns(builder *flatbuffers.Builder, observationLsns flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(observationLsns), 0)
}
func OutcomeObservedStartObservationLsnsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func OutcomeObservedAddEvaluatorVersion(builder *flatbuffers.Builder, evaluatorVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(evaluatorVersion), 0)
}
func OutcomeObservedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
