// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type OutcomeAssessment byte

const (
	OutcomeAssessmentsupported    OutcomeAssessment = 0
	OutcomeAssessmentcontradicted OutcomeAssessment = 1
	OutcomeAssessmentpending      OutcomeAssessment = 2
	OutcomeAssessmentunresolvable OutcomeAssessment = 3
	OutcomeAssessmentnot_executed OutcomeAssessment = 4
)

var EnumNamesOutcomeAssessment = map[OutcomeAssessment]string{
	OutcomeAssessmentsupported:    "supported",
	OutcomeAssessmentcontradicted: "contradicted",
	OutcomeAssessmentpending:      "pending",
	OutcomeAssessmentunresolvable: "unresolvable",
	OutcomeAssessmentnot_executed: "not_executed",
}

var EnumValuesOutcomeAssessment = map[string]OutcomeAssessment{
	"supported":    OutcomeAssessmentsupported,
	"contradicted": OutcomeAssessmentcontradicted,
	"pending":      OutcomeAssessmentpending,
	"unresolvable": OutcomeAssessmentunresolvable,
	"not_executed": OutcomeAssessmentnot_executed,
}

func (v OutcomeAssessment) String() string {
	if s, ok := EnumNamesOutcomeAssessment[v]; ok {
		return s
	}
	return "OutcomeAssessment(" + strconv.FormatInt(int64(v), 10) + ")"
}
