// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type PredicateKind byte

const (
	PredicateKindobject_exists      PredicateKind = 0
	PredicateKindrevision_equals    PredicateKind = 1
	PredicateKinddigest_equals      PredicateKind = 2
	PredicateKindreceipt_matches    PredicateKind = 3
	PredicateKindproperty_satisfies PredicateKind = 4
	PredicateKindprocess_terminated PredicateKind = 5
	PredicateKindanswer_committed   PredicateKind = 6
)

var EnumNamesPredicateKind = map[PredicateKind]string{
	PredicateKindobject_exists:      "object_exists",
	PredicateKindrevision_equals:    "revision_equals",
	PredicateKinddigest_equals:      "digest_equals",
	PredicateKindreceipt_matches:    "receipt_matches",
	PredicateKindproperty_satisfies: "property_satisfies",
	PredicateKindprocess_terminated: "process_terminated",
	PredicateKindanswer_committed:   "answer_committed",
}

var EnumValuesPredicateKind = map[string]PredicateKind{
	"object_exists":      PredicateKindobject_exists,
	"revision_equals":    PredicateKindrevision_equals,
	"digest_equals":      PredicateKinddigest_equals,
	"receipt_matches":    PredicateKindreceipt_matches,
	"property_satisfies": PredicateKindproperty_satisfies,
	"process_terminated": PredicateKindprocess_terminated,
	"answer_committed":   PredicateKindanswer_committed,
}

func (v PredicateKind) String() string {
	if s, ok := EnumNamesPredicateKind[v]; ok {
		return s
	}
	return "PredicateKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
