// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ProcedureAdopted struct {
	_tab flatbuffers.Table
}

func GetRootAsProcedureAdopted(buf []byte, offset flatbuffers.UOffsetT) *ProcedureAdopted {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProcedureAdopted{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsProcedureAdopted(buf []byte, offset flatbuffers.UOffsetT) *ProcedureAdopted {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProcedureAdopted{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ProcedureAdopted) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProcedureAdopted) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProcedureAdopted) ProcedureId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ProcedureAdopted) ProcedureIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProcedureAdopted) ProcedureIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProcedureAdopted) MutateProcedureId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ProcedureAdopted) ProcedureLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProcedureAdopted) MutateProcedureLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func ProcedureAdoptedStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ProcedureAdoptedAddProcedureId(builder *flatbuffers.Builder, procedureId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(procedureId), 0)
}
func ProcedureAdoptedStartProcedureIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ProcedureAdoptedAddProcedureLsn(builder *flatbuffers.Builder, procedureLsn uint64) {
	builder.PrependUint64Slot(1, procedureLsn, 0)
}
func ProcedureAdoptedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
