// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ProcedureSupport struct {
	_tab flatbuffers.Table
}

func GetRootAsProcedureSupport(buf []byte, offset flatbuffers.UOffsetT) *ProcedureSupport {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProcedureSupport{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsProcedureSupport(buf []byte, offset flatbuffers.UOffsetT) *ProcedureSupport {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProcedureSupport{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ProcedureSupport) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProcedureSupport) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProcedureSupport) SourceRoot(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ProcedureSupport) SourceRootLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProcedureSupport) SourceRootBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProcedureSupport) MutateSourceRoot(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ProcedureSupport) Conversation(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ProcedureSupport) ConversationLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProcedureSupport) ConversationBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProcedureSupport) MutateConversation(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ProcedureSupport) EpisodeLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProcedureSupport) MutateEpisodeLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func ProcedureSupportStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ProcedureSupportAddSourceRoot(builder *flatbuffers.Builder, sourceRoot flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sourceRoot), 0)
}
func ProcedureSupportStartSourceRootVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ProcedureSupportAddConversation(builder *flatbuffers.Builder, conversation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(conversation), 0)
}
func ProcedureSupportStartConversationVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ProcedureSupportAddEpisodeLsn(builder *flatbuffers.Builder, episodeLsn uint64) {
	builder.PrependUint64Slot(2, episodeLsn, 0)
}
func ProcedureSupportEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
