// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type PromptVersion struct {
	_tab flatbuffers.Table
}

func GetRootAsPromptVersion(buf []byte, offset flatbuffers.UOffsetT) *PromptVersion {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PromptVersion{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPromptVersion(buf []byte, offset flatbuffers.UOffsetT) *PromptVersion {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PromptVersion{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *PromptVersion) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PromptVersion) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PromptVersion) PromptId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PromptVersion) Version() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PromptVersion) MutateVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *PromptVersion) ModelId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PromptVersionStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PromptVersionAddPromptId(builder *flatbuffers.Builder, promptId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(promptId), 0)
}
func PromptVersionAddVersion(builder *flatbuffers.Builder, version uint16) {
	builder.PrependUint16Slot(1, version, 0)
}
func PromptVersionAddModelId(builder *flatbuffers.Builder, modelId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(modelId), 0)
}
func PromptVersionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
