// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ProposedAssertion struct {
	_tab flatbuffers.Table
}

func GetRootAsProposedAssertion(buf []byte, offset flatbuffers.UOffsetT) *ProposedAssertion {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProposedAssertion{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsProposedAssertion(buf []byte, offset flatbuffers.UOffsetT) *ProposedAssertion {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProposedAssertion{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ProposedAssertion) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProposedAssertion) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProposedAssertion) BeliefId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ProposedAssertion) BeliefIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProposedAssertion) BeliefIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProposedAssertion) MutateBeliefId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ProposedAssertion) BeliefType() BeliefType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return BeliefType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ProposedAssertion) MutateBeliefType(n BeliefType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *ProposedAssertion) CanonicalIdentity() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProposedAssertion) Value(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ProposedAssertion) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProposedAssertion) ValueBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProposedAssertion) MutateValue(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ProposedAssertion) ValidFromNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProposedAssertion) MutateValidFromNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *ProposedAssertion) ValidToNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProposedAssertion) MutateValidToNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *ProposedAssertion) Provenance(obj *ProvenanceRange, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 24
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ProposedAssertion) ProvenanceLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProposedAssertion) ConflictDomain() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProposedAssertion) Claim() AssertionClaim {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return AssertionClaim(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ProposedAssertion) MutateClaim(n AssertionClaim) bool {
	return rcv._tab.MutateByteSlot(20, byte(n))
}

func ProposedAssertionStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func ProposedAssertionAddBeliefId(builder *flatbuffers.Builder, beliefId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(beliefId), 0)
}
func ProposedAssertionStartBeliefIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ProposedAssertionAddBeliefType(builder *flatbuffers.Builder, beliefType BeliefType) {
	builder.PrependByteSlot(1, byte(beliefType), 0)
}
func ProposedAssertionAddCanonicalIdentity(builder *flatbuffers.Builder, canonicalIdentity flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(canonicalIdentity), 0)
}
func ProposedAssertionAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(value), 0)
}
func ProposedAssertionStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ProposedAssertionAddValidFromNs(builder *flatbuffers.Builder, validFromNs int64) {
	builder.PrependInt64Slot(4, validFromNs, 0)
}
func ProposedAssertionAddValidToNs(builder *flatbuffers.Builder, validToNs int64) {
	builder.PrependInt64Slot(5, validToNs, 0)
}
func ProposedAssertionAddProvenance(builder *flatbuffers.Builder, provenance flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(provenance), 0)
}
func ProposedAssertionStartProvenanceVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(24, numElems, 8)
}
func ProposedAssertionAddConflictDomain(builder *flatbuffers.Builder, conflictDomain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(conflictDomain), 0)
}
func ProposedAssertionAddClaim(builder *flatbuffers.Builder, claim AssertionClaim) {
	builder.PrependByteSlot(8, byte(claim), 0)
}
func ProposedAssertionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
