// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type ReviewRating byte

const (
	ReviewRatingagain ReviewRating = 0
	ReviewRatinghard  ReviewRating = 1
	ReviewRatinggood  ReviewRating = 2
	ReviewRatingeasy  ReviewRating = 3
)

var EnumNamesReviewRating = map[ReviewRating]string{
	ReviewRatingagain: "again",
	ReviewRatinghard:  "hard",
	ReviewRatinggood:  "good",
	ReviewRatingeasy:  "easy",
}

var EnumValuesReviewRating = map[string]ReviewRating{
	"again": ReviewRatingagain,
	"hard":  ReviewRatinghard,
	"good":  ReviewRatinggood,
	"easy":  ReviewRatingeasy,
}

func (v ReviewRating) String() string {
	if s, ok := EnumNamesReviewRating[v]; ok {
		return s
	}
	return "ReviewRating(" + strconv.FormatInt(int64(v), 10) + ")"
}
