// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type Sensitivity byte

const (
	Sensitivitypublic   Sensitivity = 0
	Sensitivitypersonal Sensitivity = 1
	Sensitivitysecret   Sensitivity = 2
)

var EnumNamesSensitivity = map[Sensitivity]string{
	Sensitivitypublic:   "public",
	Sensitivitypersonal: "personal",
	Sensitivitysecret:   "secret",
}

var EnumValuesSensitivity = map[string]Sensitivity{
	"public":   Sensitivitypublic,
	"personal": Sensitivitypersonal,
	"secret":   Sensitivitysecret,
}

func (v Sensitivity) String() string {
	if s, ok := EnumNamesSensitivity[v]; ok {
		return s
	}
	return "Sensitivity(" + strconv.FormatInt(int64(v), 10) + ")"
}
