// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type WakeChannelMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsWakeChannelMessage(buf []byte, offset flatbuffers.UOffsetT) *WakeChannelMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WakeChannelMessage{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsWakeChannelMessage(buf []byte, offset flatbuffers.UOffsetT) *WakeChannelMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WakeChannelMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *WakeChannelMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WakeChannelMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WakeChannelMessage) Channel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func WakeChannelMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WakeChannelMessageAddChannel(builder *flatbuffers.Builder, channel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(channel), 0)
}
func WakeChannelMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
