// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type WakeEntityMentioned struct {
	_tab flatbuffers.Table
}

func GetRootAsWakeEntityMentioned(buf []byte, offset flatbuffers.UOffsetT) *WakeEntityMentioned {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WakeEntityMentioned{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsWakeEntityMentioned(buf []byte, offset flatbuffers.UOffsetT) *WakeEntityMentioned {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WakeEntityMentioned{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *WakeEntityMentioned) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WakeEntityMentioned) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WakeEntityMentioned) EntityId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *WakeEntityMentioned) EntityIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *WakeEntityMentioned) EntityIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WakeEntityMentioned) MutateEntityId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func WakeEntityMentionedStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WakeEntityMentionedAddEntityId(builder *flatbuffers.Builder, entityId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entityId), 0)
}
func WakeEntityMentionedStartEntityIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func WakeEntityMentionedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
