// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type WakeTrigger byte

const (
	WakeTriggerNONE                   WakeTrigger = 0
	WakeTriggerWakeAt                 WakeTrigger = 1
	WakeTriggerWakeSchedule           WakeTrigger = 2
	WakeTriggerWakeChildTerminal      WakeTrigger = 3
	WakeTriggerWakeProcessExit        WakeTrigger = 4
	WakeTriggerWakeFileChanged        WakeTrigger = 5
	WakeTriggerWakeRepositoryChanged  WakeTrigger = 6
	WakeTriggerWakeChannelMessage     WakeTrigger = 7
	WakeTriggerWakeExternalCondition  WakeTrigger = 8
	WakeTriggerWakeUserResponse       WakeTrigger = 9
	WakeTriggerWakeEntityMentioned    WakeTrigger = 10
	WakeTriggerWakeLoopClosed         WakeTrigger = 11
	WakeTriggerWakePredictionResolved WakeTrigger = 12
	WakeTriggerWakeBeliefChanged      WakeTrigger = 13
)

var EnumNamesWakeTrigger = map[WakeTrigger]string{
	WakeTriggerNONE:                   "NONE",
	WakeTriggerWakeAt:                 "WakeAt",
	WakeTriggerWakeSchedule:           "WakeSchedule",
	WakeTriggerWakeChildTerminal:      "WakeChildTerminal",
	WakeTriggerWakeProcessExit:        "WakeProcessExit",
	WakeTriggerWakeFileChanged:        "WakeFileChanged",
	WakeTriggerWakeRepositoryChanged:  "WakeRepositoryChanged",
	WakeTriggerWakeChannelMessage:     "WakeChannelMessage",
	WakeTriggerWakeExternalCondition:  "WakeExternalCondition",
	WakeTriggerWakeUserResponse:       "WakeUserResponse",
	WakeTriggerWakeEntityMentioned:    "WakeEntityMentioned",
	WakeTriggerWakeLoopClosed:         "WakeLoopClosed",
	WakeTriggerWakePredictionResolved: "WakePredictionResolved",
	WakeTriggerWakeBeliefChanged:      "WakeBeliefChanged",
}

var EnumValuesWakeTrigger = map[string]WakeTrigger{
	"NONE":                   WakeTriggerNONE,
	"WakeAt":                 WakeTriggerWakeAt,
	"WakeSchedule":           WakeTriggerWakeSchedule,
	"WakeChildTerminal":      WakeTriggerWakeChildTerminal,
	"WakeProcessExit":        WakeTriggerWakeProcessExit,
	"WakeFileChanged":        WakeTriggerWakeFileChanged,
	"WakeRepositoryChanged":  WakeTriggerWakeRepositoryChanged,
	"WakeChannelMessage":     WakeTriggerWakeChannelMessage,
	"WakeExternalCondition":  WakeTriggerWakeExternalCondition,
	"WakeUserResponse":       WakeTriggerWakeUserResponse,
	"WakeEntityMentioned":    WakeTriggerWakeEntityMentioned,
	"WakeLoopClosed":         WakeTriggerWakeLoopClosed,
	"WakePredictionResolved": WakeTriggerWakePredictionResolved,
	"WakeBeliefChanged":      WakeTriggerWakeBeliefChanged,
}

func (v WakeTrigger) String() string {
	if s, ok := EnumNamesWakeTrigger[v]; ok {
		return s
	}
	return "WakeTrigger(" + strconv.FormatInt(int64(v), 10) + ")"
}
