// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type WakeLoopClosed struct {
	_tab flatbuffers.Table
}

func GetRootAsWakeLoopClosed(buf []byte, offset flatbuffers.UOffsetT) *WakeLoopClosed {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WakeLoopClosed{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsWakeLoopClosed(buf []byte, offset flatbuffers.UOffsetT) *WakeLoopClosed {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WakeLoopClosed{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *WakeLoopClosed) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WakeLoopClosed) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WakeLoopClosed) LoopId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *WakeLoopClosed) LoopIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *WakeLoopClosed) LoopIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WakeLoopClosed) MutateLoopId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func WakeLoopClosedStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WakeLoopClosedAddLoopId(builder *flatbuffers.Builder, loopId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(loopId), 0)
}
func WakeLoopClosedStartLoopIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func WakeLoopClosedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
