// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type WakeProcessExit struct {
	_tab flatbuffers.Table
}

func GetRootAsWakeProcessExit(buf []byte, offset flatbuffers.UOffsetT) *WakeProcessExit {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WakeProcessExit{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsWakeProcessExit(buf []byte, offset flatbuffers.UOffsetT) *WakeProcessExit {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WakeProcessExit{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *WakeProcessExit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WakeProcessExit) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WakeProcessExit) ProcessId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *WakeProcessExit) ProcessIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *WakeProcessExit) ProcessIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WakeProcessExit) MutateProcessId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func WakeProcessExitStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WakeProcessExitAddProcessId(builder *flatbuffers.Builder, processId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(processId), 0)
}
func WakeProcessExitStartProcessIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func WakeProcessExitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
