// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type WakeSchedule struct {
	_tab flatbuffers.Table
}

func GetRootAsWakeSchedule(buf []byte, offset flatbuffers.UOffsetT) *WakeSchedule {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WakeSchedule{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsWakeSchedule(buf []byte, offset flatbuffers.UOffsetT) *WakeSchedule {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WakeSchedule{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *WakeSchedule) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WakeSchedule) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WakeSchedule) Schedule() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func WakeScheduleStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WakeScheduleAddSchedule(builder *flatbuffers.Builder, schedule flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(schedule), 0)
}
func WakeScheduleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
