use wide::i16x8;

#[must_use]
pub fn scalar_dot(left: &[i8], right: &[i8]) -> Option<i64> {
    (left.len() == right.len()).then(|| {
        left.iter()
            .zip(right)
            .map(|(left, right)| i64::from(*left) * i64::from(*right))
            .sum()
    })
}

#[must_use]
pub fn simd_dot(left: &[i8], right: &[i8]) -> Option<i64> {
    if left.len() != right.len() {
        return None;
    }
    let mut total = 0_i64;
    let mut left_chunks = left.chunks_exact(8);
    let mut right_chunks = right.chunks_exact(8);
    for (left, right) in left_chunks.by_ref().zip(right_chunks.by_ref()) {
        let left = i16x8::new(std::array::from_fn(|index| i16::from(left[index])));
        let right = i16x8::new(std::array::from_fn(|index| i16::from(right[index])));
        total += (left * right)
            .to_array()
            .into_iter()
            .map(i64::from)
            .sum::<i64>();
    }
    total += left_chunks
        .remainder()
        .iter()
        .zip(right_chunks.remainder())
        .map(|(left, right)| i64::from(*left) * i64::from(*right))
        .sum::<i64>();
    Some(total)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn simd_equals_scalar_for_generated_vectors() {
        for length in 0_usize..=513 {
            let left: Vec<_> = (0..length)
                .map(|index| {
                    u8::try_from((index * 67 + length * 13) & 0xff)
                        .expect("generated byte")
                        .cast_signed()
                })
                .collect();
            let right: Vec<_> = (0..length)
                .map(|index| {
                    u8::try_from((index * 29 + length * 101) & 0xff)
                        .expect("generated byte")
                        .cast_signed()
                })
                .collect();
            assert_eq!(simd_dot(&left, &right), scalar_dot(&left, &right));
        }
        assert_eq!(simd_dot(&[1], &[]), None);
    }
}
