// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type BeliefProvenanceRecord struct {
	_tab flatbuffers.Table
}

func GetRootAsBeliefProvenanceRecord(buf []byte, offset flatbuffers.UOffsetT) *BeliefProvenanceRecord {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BeliefProvenanceRecord{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsBeliefProvenanceRecord(buf []byte, offset flatbuffers.UOffsetT) *BeliefProvenanceRecord {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BeliefProvenanceRecord{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *BeliefProvenanceRecord) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BeliefProvenanceRecord) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BeliefProvenanceRecord) FirstLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefProvenanceRecord) MutateFirstLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *BeliefProvenanceRecord) LastLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefProvenanceRecord) MutateLastLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *BeliefProvenanceRecord) ByteStart() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefProvenanceRecord) MutateByteStart(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *BeliefProvenanceRecord) ByteEnd() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefProvenanceRecord) MutateByteEnd(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func BeliefProvenanceRecordStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func BeliefProvenanceRecordAddFirstLsn(builder *flatbuffers.Builder, firstLsn uint64) {
	builder.PrependUint64Slot(0, firstLsn, 0)
}
func BeliefProvenanceRecordAddLastLsn(builder *flatbuffers.Builder, lastLsn uint64) {
	builder.PrependUint64Slot(1, lastLsn, 0)
}
func BeliefProvenanceRecordAddByteStart(builder *flatbuffers.Builder, byteStart uint32) {
	builder.PrependUint32Slot(2, byteStart, 0)
}
func BeliefProvenanceRecordAddByteEnd(builder *flatbuffers.Builder, byteEnd uint32) {
	builder.PrependUint32Slot(3, byteEnd, 0)
}
func BeliefProvenanceRecordEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
