// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type MutationEffectState byte

const (
	MutationEffectStatenone           MutationEffectState = 0
	MutationEffectStatenot_dispatched MutationEffectState = 1
	MutationEffectStateunknown        MutationEffectState = 2
	MutationEffectStaterejected       MutationEffectState = 3
)

var EnumNamesMutationEffectState = map[MutationEffectState]string{
	MutationEffectStatenone:           "none",
	MutationEffectStatenot_dispatched: "not_dispatched",
	MutationEffectStateunknown:        "unknown",
	MutationEffectStaterejected:       "rejected",
}

var EnumValuesMutationEffectState = map[string]MutationEffectState{
	"none":           MutationEffectStatenone,
	"not_dispatched": MutationEffectStatenot_dispatched,
	"unknown":        MutationEffectStateunknown,
	"rejected":       MutationEffectStaterejected,
}

func (v MutationEffectState) String() string {
	if s, ok := EnumNamesMutationEffectState[v]; ok {
		return s
	}
	return "MutationEffectState(" + strconv.FormatInt(int64(v), 10) + ")"
}
