[Service]
ExecStart=
ExecStart=/usr/local/bin/hm serve --config /var/lib/hypermind/hypermind.conf --grpc-bind 0.0.0.0:8443 --rest-bind 0.0.0.0:8444 --tls-cert /etc/hypermind/tls/server.pem --tls-key /etc/hypermind/tls/server.key --tls-client-ca /etc/hypermind/tls/client-ca.pem
