// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Activate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Activate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsActivate(bb:flatbuffers.ByteBuffer, obj?:Activate):Activate {
  return (obj || new Activate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsActivate(bb:flatbuffers.ByteBuffer, obj?:Activate):Activate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Activate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

conversation(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

conversationLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

conversationArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

query(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

queryLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

queryArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

turnText(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

turnTextLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

turnTextArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

budgetTokens():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

queryEmbedding(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

queryEmbeddingLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

queryEmbeddingArray():Int8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

queryBinaryPrefilter(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

queryBinaryPrefilterLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

queryBinaryPrefilterArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

temporalFromNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

temporalToNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

tokenWeights(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

tokenWeightsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

tokenWeightsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

tokenItemOverhead():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startActivate(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addConversation(builder:flatbuffers.Builder, conversationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, conversationOffset, 0);
}

static createConversationVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startConversationVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addQuery(builder:flatbuffers.Builder, queryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, queryOffset, 0);
}

static createQueryVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startQueryVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addTurnText(builder:flatbuffers.Builder, turnTextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, turnTextOffset, 0);
}

static createTurnTextVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startTurnTextVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addBudgetTokens(builder:flatbuffers.Builder, budgetTokens:bigint) {
  builder.addFieldInt64(3, budgetTokens, BigInt('0'));
}

static addQueryEmbedding(builder:flatbuffers.Builder, queryEmbeddingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, queryEmbeddingOffset, 0);
}

static createQueryEmbeddingVector(builder:flatbuffers.Builder, data:number[]|Int8Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createQueryEmbeddingVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createQueryEmbeddingVector(builder:flatbuffers.Builder, data:number[]|Int8Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startQueryEmbeddingVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addQueryBinaryPrefilter(builder:flatbuffers.Builder, queryBinaryPrefilterOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, queryBinaryPrefilterOffset, 0);
}

static createQueryBinaryPrefilterVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startQueryBinaryPrefilterVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addTemporalFromNs(builder:flatbuffers.Builder, temporalFromNs:bigint) {
  builder.addFieldInt64(6, temporalFromNs, BigInt('0'));
}

static addTemporalToNs(builder:flatbuffers.Builder, temporalToNs:bigint) {
  builder.addFieldInt64(7, temporalToNs, BigInt('0'));
}

static addTokenWeights(builder:flatbuffers.Builder, tokenWeightsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, tokenWeightsOffset, 0);
}

static createTokenWeightsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createTokenWeightsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createTokenWeightsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startTokenWeightsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addTokenItemOverhead(builder:flatbuffers.Builder, tokenItemOverhead:number) {
  builder.addFieldInt32(9, tokenItemOverhead, 0);
}

static endActivate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // conversation
  builder.requiredField(offset, 6) // query
  return offset;
}

static createActivate(builder:flatbuffers.Builder, conversationOffset:flatbuffers.Offset, queryOffset:flatbuffers.Offset, turnTextOffset:flatbuffers.Offset, budgetTokens:bigint, queryEmbeddingOffset:flatbuffers.Offset, queryBinaryPrefilterOffset:flatbuffers.Offset, temporalFromNs:bigint, temporalToNs:bigint, tokenWeightsOffset:flatbuffers.Offset, tokenItemOverhead:number):flatbuffers.Offset {
  Activate.startActivate(builder);
  Activate.addConversation(builder, conversationOffset);
  Activate.addQuery(builder, queryOffset);
  Activate.addTurnText(builder, turnTextOffset);
  Activate.addBudgetTokens(builder, budgetTokens);
  Activate.addQueryEmbedding(builder, queryEmbeddingOffset);
  Activate.addQueryBinaryPrefilter(builder, queryBinaryPrefilterOffset);
  Activate.addTemporalFromNs(builder, temporalFromNs);
  Activate.addTemporalToNs(builder, temporalToNs);
  Activate.addTokenWeights(builder, tokenWeightsOffset);
  Activate.addTokenItemOverhead(builder, tokenItemOverhead);
  return Activate.endActivate(builder);
}

unpack(): ActivateT {
  return new ActivateT(
    this.bb!.createScalarList(this.conversation.bind(this), this.conversationLength()),
    this.bb!.createScalarList(this.query.bind(this), this.queryLength()),
    this.bb!.createScalarList(this.turnText.bind(this), this.turnTextLength()),
    this.budgetTokens(),
    this.bb!.createScalarList(this.queryEmbedding.bind(this), this.queryEmbeddingLength()),
    this.bb!.createScalarList(this.queryBinaryPrefilter.bind(this), this.queryBinaryPrefilterLength()),
    this.temporalFromNs(),
    this.temporalToNs(),
    this.bb!.createScalarList(this.tokenWeights.bind(this), this.tokenWeightsLength()),
    this.tokenItemOverhead()
  );
}


unpackTo(_o: ActivateT): void {
  _o.conversation = this.bb!.createScalarList(this.conversation.bind(this), this.conversationLength());
  _o.query = this.bb!.createScalarList(this.query.bind(this), this.queryLength());
  _o.turnText = this.bb!.createScalarList(this.turnText.bind(this), this.turnTextLength());
  _o.budgetTokens = this.budgetTokens();
  _o.queryEmbedding = this.bb!.createScalarList(this.queryEmbedding.bind(this), this.queryEmbeddingLength());
  _o.queryBinaryPrefilter = this.bb!.createScalarList(this.queryBinaryPrefilter.bind(this), this.queryBinaryPrefilterLength());
  _o.temporalFromNs = this.temporalFromNs();
  _o.temporalToNs = this.temporalToNs();
  _o.tokenWeights = this.bb!.createScalarList(this.tokenWeights.bind(this), this.tokenWeightsLength());
  _o.tokenItemOverhead = this.tokenItemOverhead();
}
}

export class ActivateT {
constructor(
  public conversation: (number)[] = [],
  public query: (number)[] = [],
  public turnText: (number)[] = [],
  public budgetTokens: bigint = BigInt('0'),
  public queryEmbedding: (number)[] = [],
  public queryBinaryPrefilter: (number)[] = [],
  public temporalFromNs: bigint = BigInt('0'),
  public temporalToNs: bigint = BigInt('0'),
  public tokenWeights: (number)[] = [],
  public tokenItemOverhead: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const conversation = Activate.createConversationVector(builder, this.conversation);
  const query = Activate.createQueryVector(builder, this.query);
  const turnText = Activate.createTurnTextVector(builder, this.turnText);
  const queryEmbedding = Activate.createQueryEmbeddingVector(builder, this.queryEmbedding);
  const queryBinaryPrefilter = Activate.createQueryBinaryPrefilterVector(builder, this.queryBinaryPrefilter);
  const tokenWeights = Activate.createTokenWeightsVector(builder, this.tokenWeights);

  return Activate.createActivate(builder,
    conversation,
    query,
    turnText,
    this.budgetTokens,
    queryEmbedding,
    queryBinaryPrefilter,
    this.temporalFromNs,
    this.temporalToNs,
    tokenWeights,
    this.tokenItemOverhead
  );
}
}
