// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class AppendEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AppendEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAppendEvent(bb:flatbuffers.ByteBuffer, obj?:AppendEvent):AppendEvent {
  return (obj || new AppendEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAppendEvent(bb:flatbuffers.ByteBuffer, obj?:AppendEvent):AppendEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AppendEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

conversation(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

conversationLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

conversationArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startAppendEvent(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addKind(builder:flatbuffers.Builder, kind:number) {
  builder.addFieldInt8(0, kind, 0);
}

static addConversation(builder:flatbuffers.Builder, conversationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, conversationOffset, 0);
}

static createConversationVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startConversationVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endAppendEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // conversation
  builder.requiredField(offset, 8) // payload
  return offset;
}

static createAppendEvent(builder:flatbuffers.Builder, kind:number, conversationOffset:flatbuffers.Offset, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  AppendEvent.startAppendEvent(builder);
  AppendEvent.addKind(builder, kind);
  AppendEvent.addConversation(builder, conversationOffset);
  AppendEvent.addPayload(builder, payloadOffset);
  return AppendEvent.endAppendEvent(builder);
}

unpack(): AppendEventT {
  return new AppendEventT(
    this.kind(),
    this.bb!.createScalarList(this.conversation.bind(this), this.conversationLength()),
    this.bb!.createScalarList(this.payload.bind(this), this.payloadLength())
  );
}


unpackTo(_o: AppendEventT): void {
  _o.kind = this.kind();
  _o.conversation = this.bb!.createScalarList(this.conversation.bind(this), this.conversationLength());
  _o.payload = this.bb!.createScalarList(this.payload.bind(this), this.payloadLength());
}
}

export class AppendEventT {
constructor(
  public kind: number = 0,
  public conversation: (number)[] = [],
  public payload: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const conversation = AppendEvent.createConversationVector(builder, this.conversation);
  const payload = AppendEvent.createPayloadVector(builder, this.payload);

  return AppendEvent.createAppendEvent(builder,
    this.kind,
    conversation,
    payload
  );
}
}
