// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { AppendEvent, AppendEventT } from '../../hypermind/protocol/append-event';


export class Append {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Append {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAppend(bb:flatbuffers.ByteBuffer, obj?:Append):Append {
  return (obj || new Append()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAppend(bb:flatbuffers.ByteBuffer, obj?:Append):Append {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Append()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientSeq():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

events(index: number, obj?:AppendEvent):AppendEvent|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new AppendEvent()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

eventsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startAppend(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addClientSeq(builder:flatbuffers.Builder, clientSeq:bigint) {
  builder.addFieldInt64(0, clientSeq, BigInt('0'));
}

static addEvents(builder:flatbuffers.Builder, eventsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, eventsOffset, 0);
}

static createEventsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEventsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endAppend(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // events
  return offset;
}

static createAppend(builder:flatbuffers.Builder, clientSeq:bigint, eventsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Append.startAppend(builder);
  Append.addClientSeq(builder, clientSeq);
  Append.addEvents(builder, eventsOffset);
  return Append.endAppend(builder);
}

unpack(): AppendT {
  return new AppendT(
    this.clientSeq(),
    this.bb!.createObjList(this.events.bind(this), this.eventsLength())
  );
}


unpackTo(_o: AppendT): void {
  _o.clientSeq = this.clientSeq();
  _o.events = this.bb!.createObjList(this.events.bind(this), this.eventsLength());
}
}

export class AppendT {
constructor(
  public clientSeq: bigint = BigInt('0'),
  public events: (AppendEventT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const events = Append.createEventsVector(builder, builder.createObjectOffsetList(this.events));

  return Append.createAppend(builder,
    this.clientSeq,
    events
  );
}
}
