// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class AppendAck {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AppendAck {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAppendAck(bb:flatbuffers.ByteBuffer, obj?:AppendAck):AppendAck {
  return (obj || new AppendAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAppendAck(bb:flatbuffers.ByteBuffer, obj?:AppendAck):AppendAck {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AppendAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientSeq():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

firstLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

lastLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

duplicate():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

leafCount():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

lastLeafHash(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

lastLeafHashLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

lastLeafHashArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

mmrRoot(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

mmrRootLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

mmrRootArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startAppendAck(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addClientSeq(builder:flatbuffers.Builder, clientSeq:bigint) {
  builder.addFieldInt64(0, clientSeq, BigInt('0'));
}

static addFirstLsn(builder:flatbuffers.Builder, firstLsn:bigint) {
  builder.addFieldInt64(1, firstLsn, BigInt('0'));
}

static addLastLsn(builder:flatbuffers.Builder, lastLsn:bigint) {
  builder.addFieldInt64(2, lastLsn, BigInt('0'));
}

static addDuplicate(builder:flatbuffers.Builder, duplicate:boolean) {
  builder.addFieldInt8(3, +duplicate, +false);
}

static addLeafCount(builder:flatbuffers.Builder, leafCount:bigint) {
  builder.addFieldInt64(4, leafCount, BigInt('0'));
}

static addLastLeafHash(builder:flatbuffers.Builder, lastLeafHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, lastLeafHashOffset, 0);
}

static createLastLeafHashVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startLastLeafHashVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addMmrRoot(builder:flatbuffers.Builder, mmrRootOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, mmrRootOffset, 0);
}

static createMmrRootVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startMmrRootVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endAppendAck(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAppendAck(builder:flatbuffers.Builder, clientSeq:bigint, firstLsn:bigint, lastLsn:bigint, duplicate:boolean, leafCount:bigint, lastLeafHashOffset:flatbuffers.Offset, mmrRootOffset:flatbuffers.Offset):flatbuffers.Offset {
  AppendAck.startAppendAck(builder);
  AppendAck.addClientSeq(builder, clientSeq);
  AppendAck.addFirstLsn(builder, firstLsn);
  AppendAck.addLastLsn(builder, lastLsn);
  AppendAck.addDuplicate(builder, duplicate);
  AppendAck.addLeafCount(builder, leafCount);
  AppendAck.addLastLeafHash(builder, lastLeafHashOffset);
  AppendAck.addMmrRoot(builder, mmrRootOffset);
  return AppendAck.endAppendAck(builder);
}

unpack(): AppendAckT {
  return new AppendAckT(
    this.clientSeq(),
    this.firstLsn(),
    this.lastLsn(),
    this.duplicate(),
    this.leafCount(),
    this.bb!.createScalarList(this.lastLeafHash.bind(this), this.lastLeafHashLength()),
    this.bb!.createScalarList(this.mmrRoot.bind(this), this.mmrRootLength())
  );
}


unpackTo(_o: AppendAckT): void {
  _o.clientSeq = this.clientSeq();
  _o.firstLsn = this.firstLsn();
  _o.lastLsn = this.lastLsn();
  _o.duplicate = this.duplicate();
  _o.leafCount = this.leafCount();
  _o.lastLeafHash = this.bb!.createScalarList(this.lastLeafHash.bind(this), this.lastLeafHashLength());
  _o.mmrRoot = this.bb!.createScalarList(this.mmrRoot.bind(this), this.mmrRootLength());
}
}

export class AppendAckT {
constructor(
  public clientSeq: bigint = BigInt('0'),
  public firstLsn: bigint = BigInt('0'),
  public lastLsn: bigint = BigInt('0'),
  public duplicate: boolean = false,
  public leafCount: bigint = BigInt('0'),
  public lastLeafHash: (number)[] = [],
  public mmrRoot: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const lastLeafHash = AppendAck.createLastLeafHashVector(builder, this.lastLeafHash);
  const mmrRoot = AppendAck.createMmrRootVector(builder, this.mmrRoot);

  return AppendAck.createAppendAck(builder,
    this.clientSeq,
    this.firstLsn,
    this.lastLsn,
    this.duplicate,
    this.leafCount,
    lastLeafHash,
    mmrRoot
  );
}
}
