// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class AttestAck {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AttestAck {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAttestAck(bb:flatbuffers.ByteBuffer, obj?:AttestAck):AttestAck {
  return (obj || new AttestAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAttestAck(bb:flatbuffers.ByteBuffer, obj?:AttestAck):AttestAck {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AttestAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

firstLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

lastLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

count():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startAttestAck(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addFirstLsn(builder:flatbuffers.Builder, firstLsn:bigint) {
  builder.addFieldInt64(0, firstLsn, BigInt('0'));
}

static addLastLsn(builder:flatbuffers.Builder, lastLsn:bigint) {
  builder.addFieldInt64(1, lastLsn, BigInt('0'));
}

static addCount(builder:flatbuffers.Builder, count:number) {
  builder.addFieldInt32(2, count, 0);
}

static endAttestAck(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAttestAck(builder:flatbuffers.Builder, firstLsn:bigint, lastLsn:bigint, count:number):flatbuffers.Offset {
  AttestAck.startAttestAck(builder);
  AttestAck.addFirstLsn(builder, firstLsn);
  AttestAck.addLastLsn(builder, lastLsn);
  AttestAck.addCount(builder, count);
  return AttestAck.endAttestAck(builder);
}

unpack(): AttestAckT {
  return new AttestAckT(
    this.firstLsn(),
    this.lastLsn(),
    this.count()
  );
}


unpackTo(_o: AttestAckT): void {
  _o.firstLsn = this.firstLsn();
  _o.lastLsn = this.lastLsn();
  _o.count = this.count();
}
}

export class AttestAckT {
constructor(
  public firstLsn: bigint = BigInt('0'),
  public lastLsn: bigint = BigInt('0'),
  public count: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return AttestAck.createAttestAck(builder,
    this.firstLsn,
    this.lastLsn,
    this.count
  );
}
}
