// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class BeliefConflictRecord {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BeliefConflictRecord {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBeliefConflictRecord(bb:flatbuffers.ByteBuffer, obj?:BeliefConflictRecord):BeliefConflictRecord {
  return (obj || new BeliefConflictRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBeliefConflictRecord(bb:flatbuffers.ByteBuffer, obj?:BeliefConflictRecord):BeliefConflictRecord {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BeliefConflictRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

otherType():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

otherCanonicalIdentity():string|null
otherCanonicalIdentity(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
otherCanonicalIdentity(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

createdLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

resolvedLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

obligatedSurfacing():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startBeliefConflictRecord(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addOtherType(builder:flatbuffers.Builder, otherType:number) {
  builder.addFieldInt8(0, otherType, 0);
}

static addOtherCanonicalIdentity(builder:flatbuffers.Builder, otherCanonicalIdentityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, otherCanonicalIdentityOffset, 0);
}

static addCreatedLsn(builder:flatbuffers.Builder, createdLsn:bigint) {
  builder.addFieldInt64(2, createdLsn, BigInt('0'));
}

static addResolvedLsn(builder:flatbuffers.Builder, resolvedLsn:bigint) {
  builder.addFieldInt64(3, resolvedLsn, BigInt('0'));
}

static addObligatedSurfacing(builder:flatbuffers.Builder, obligatedSurfacing:boolean) {
  builder.addFieldInt8(4, +obligatedSurfacing, +false);
}

static endBeliefConflictRecord(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // other_canonical_identity
  return offset;
}

static createBeliefConflictRecord(builder:flatbuffers.Builder, otherType:number, otherCanonicalIdentityOffset:flatbuffers.Offset, createdLsn:bigint, resolvedLsn:bigint, obligatedSurfacing:boolean):flatbuffers.Offset {
  BeliefConflictRecord.startBeliefConflictRecord(builder);
  BeliefConflictRecord.addOtherType(builder, otherType);
  BeliefConflictRecord.addOtherCanonicalIdentity(builder, otherCanonicalIdentityOffset);
  BeliefConflictRecord.addCreatedLsn(builder, createdLsn);
  BeliefConflictRecord.addResolvedLsn(builder, resolvedLsn);
  BeliefConflictRecord.addObligatedSurfacing(builder, obligatedSurfacing);
  return BeliefConflictRecord.endBeliefConflictRecord(builder);
}

unpack(): BeliefConflictRecordT {
  return new BeliefConflictRecordT(
    this.otherType(),
    this.otherCanonicalIdentity(),
    this.createdLsn(),
    this.resolvedLsn(),
    this.obligatedSurfacing()
  );
}


unpackTo(_o: BeliefConflictRecordT): void {
  _o.otherType = this.otherType();
  _o.otherCanonicalIdentity = this.otherCanonicalIdentity();
  _o.createdLsn = this.createdLsn();
  _o.resolvedLsn = this.resolvedLsn();
  _o.obligatedSurfacing = this.obligatedSurfacing();
}
}

export class BeliefConflictRecordT {
constructor(
  public otherType: number = 0,
  public otherCanonicalIdentity: string|Uint8Array|null = null,
  public createdLsn: bigint = BigInt('0'),
  public resolvedLsn: bigint = BigInt('0'),
  public obligatedSurfacing: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const otherCanonicalIdentity = (this.otherCanonicalIdentity !== null ? builder.createString(this.otherCanonicalIdentity!) : 0);

  return BeliefConflictRecord.createBeliefConflictRecord(builder,
    this.otherType,
    otherCanonicalIdentity,
    this.createdLsn,
    this.resolvedLsn,
    this.obligatedSurfacing
  );
}
}
