// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class BeliefProvenanceRecord {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BeliefProvenanceRecord {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBeliefProvenanceRecord(bb:flatbuffers.ByteBuffer, obj?:BeliefProvenanceRecord):BeliefProvenanceRecord {
  return (obj || new BeliefProvenanceRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBeliefProvenanceRecord(bb:flatbuffers.ByteBuffer, obj?:BeliefProvenanceRecord):BeliefProvenanceRecord {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BeliefProvenanceRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

firstLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

lastLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

byteStart():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

byteEnd():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startBeliefProvenanceRecord(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addFirstLsn(builder:flatbuffers.Builder, firstLsn:bigint) {
  builder.addFieldInt64(0, firstLsn, BigInt('0'));
}

static addLastLsn(builder:flatbuffers.Builder, lastLsn:bigint) {
  builder.addFieldInt64(1, lastLsn, BigInt('0'));
}

static addByteStart(builder:flatbuffers.Builder, byteStart:number) {
  builder.addFieldInt32(2, byteStart, 0);
}

static addByteEnd(builder:flatbuffers.Builder, byteEnd:number) {
  builder.addFieldInt32(3, byteEnd, 0);
}

static endBeliefProvenanceRecord(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBeliefProvenanceRecord(builder:flatbuffers.Builder, firstLsn:bigint, lastLsn:bigint, byteStart:number, byteEnd:number):flatbuffers.Offset {
  BeliefProvenanceRecord.startBeliefProvenanceRecord(builder);
  BeliefProvenanceRecord.addFirstLsn(builder, firstLsn);
  BeliefProvenanceRecord.addLastLsn(builder, lastLsn);
  BeliefProvenanceRecord.addByteStart(builder, byteStart);
  BeliefProvenanceRecord.addByteEnd(builder, byteEnd);
  return BeliefProvenanceRecord.endBeliefProvenanceRecord(builder);
}

unpack(): BeliefProvenanceRecordT {
  return new BeliefProvenanceRecordT(
    this.firstLsn(),
    this.lastLsn(),
    this.byteStart(),
    this.byteEnd()
  );
}


unpackTo(_o: BeliefProvenanceRecordT): void {
  _o.firstLsn = this.firstLsn();
  _o.lastLsn = this.lastLsn();
  _o.byteStart = this.byteStart();
  _o.byteEnd = this.byteEnd();
}
}

export class BeliefProvenanceRecordT {
constructor(
  public firstLsn: bigint = BigInt('0'),
  public lastLsn: bigint = BigInt('0'),
  public byteStart: number = 0,
  public byteEnd: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return BeliefProvenanceRecord.createBeliefProvenanceRecord(builder,
    this.firstLsn,
    this.lastLsn,
    this.byteStart,
    this.byteEnd
  );
}
}
