// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Persists an opaque turn state with client-sequence idempotency.
 */
export class Checkpoint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Checkpoint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCheckpoint(bb:flatbuffers.ByteBuffer, obj?:Checkpoint):Checkpoint {
  return (obj || new Checkpoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCheckpoint(bb:flatbuffers.ByteBuffer, obj?:Checkpoint):Checkpoint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Checkpoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

turnId(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

turnIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

turnIdArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

blob(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

blobLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

blobArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

clientSeq():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startCheckpoint(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTurnId(builder:flatbuffers.Builder, turnIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, turnIdOffset, 0);
}

static createTurnIdVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startTurnIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addBlob(builder:flatbuffers.Builder, blobOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, blobOffset, 0);
}

static createBlobVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startBlobVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addClientSeq(builder:flatbuffers.Builder, clientSeq:bigint) {
  builder.addFieldInt64(2, clientSeq, BigInt('0'));
}

static endCheckpoint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // turn_id
  builder.requiredField(offset, 6) // blob
  return offset;
}

static createCheckpoint(builder:flatbuffers.Builder, turnIdOffset:flatbuffers.Offset, blobOffset:flatbuffers.Offset, clientSeq:bigint):flatbuffers.Offset {
  Checkpoint.startCheckpoint(builder);
  Checkpoint.addTurnId(builder, turnIdOffset);
  Checkpoint.addBlob(builder, blobOffset);
  Checkpoint.addClientSeq(builder, clientSeq);
  return Checkpoint.endCheckpoint(builder);
}

unpack(): CheckpointT {
  return new CheckpointT(
    this.bb!.createScalarList(this.turnId.bind(this), this.turnIdLength()),
    this.bb!.createScalarList(this.blob.bind(this), this.blobLength()),
    this.clientSeq()
  );
}


unpackTo(_o: CheckpointT): void {
  _o.turnId = this.bb!.createScalarList(this.turnId.bind(this), this.turnIdLength());
  _o.blob = this.bb!.createScalarList(this.blob.bind(this), this.blobLength());
  _o.clientSeq = this.clientSeq();
}
}

export class CheckpointT {
constructor(
  public turnId: (number)[] = [],
  public blob: (number)[] = [],
  public clientSeq: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const turnId = Checkpoint.createTurnIdVector(builder, this.turnId);
  const blob = Checkpoint.createBlobVector(builder, this.blob);

  return Checkpoint.createCheckpoint(builder,
    turnId,
    blob,
    this.clientSeq
  );
}
}
