// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Identifies the ledger record containing the accepted checkpoint.
 */
export class CheckpointAck {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CheckpointAck {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCheckpointAck(bb:flatbuffers.ByteBuffer, obj?:CheckpointAck):CheckpointAck {
  return (obj || new CheckpointAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCheckpointAck(bb:flatbuffers.ByteBuffer, obj?:CheckpointAck):CheckpointAck {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CheckpointAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startCheckpointAck(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLsn(builder:flatbuffers.Builder, lsn:bigint) {
  builder.addFieldInt64(0, lsn, BigInt('0'));
}

static endCheckpointAck(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCheckpointAck(builder:flatbuffers.Builder, lsn:bigint):flatbuffers.Offset {
  CheckpointAck.startCheckpointAck(builder);
  CheckpointAck.addLsn(builder, lsn);
  return CheckpointAck.endCheckpointAck(builder);
}

unpack(): CheckpointAckT {
  return new CheckpointAckT(
    this.lsn()
  );
}


unpackTo(_o: CheckpointAckT): void {
  _o.lsn = this.lsn();
}
}

export class CheckpointAckT {
constructor(
  public lsn: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return CheckpointAck.createCheckpointAck(builder,
    this.lsn
  );
}
}
