// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { MutationEffectState } from '../../hypermind/protocol/mutation-effect-state';


export class ErrorDetail {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ErrorDetail {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsErrorDetail(bb:flatbuffers.ByteBuffer, obj?:ErrorDetail):ErrorDetail {
  return (obj || new ErrorDetail()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsErrorDetail(bb:flatbuffers.ByteBuffer, obj?:ErrorDetail):ErrorDetail {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ErrorDetail()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

systemError():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

lsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

offset():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

effectState():MutationEffectState {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MutationEffectState.none;
}

static startErrorDetail(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addCode(builder:flatbuffers.Builder, code:number) {
  builder.addFieldInt8(0, code, 0);
}

static addSystemError(builder:flatbuffers.Builder, systemError:number) {
  builder.addFieldInt32(1, systemError, 0);
}

static addLsn(builder:flatbuffers.Builder, lsn:bigint) {
  builder.addFieldInt64(2, lsn, BigInt('0'));
}

static addOffset(builder:flatbuffers.Builder, offset:bigint) {
  builder.addFieldInt64(3, offset, BigInt('0'));
}

static addEffectState(builder:flatbuffers.Builder, effectState:MutationEffectState) {
  builder.addFieldInt8(4, effectState, MutationEffectState.none);
}

static endErrorDetail(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createErrorDetail(builder:flatbuffers.Builder, code:number, systemError:number, lsn:bigint, offset:bigint, effectState:MutationEffectState):flatbuffers.Offset {
  ErrorDetail.startErrorDetail(builder);
  ErrorDetail.addCode(builder, code);
  ErrorDetail.addSystemError(builder, systemError);
  ErrorDetail.addLsn(builder, lsn);
  ErrorDetail.addOffset(builder, offset);
  ErrorDetail.addEffectState(builder, effectState);
  return ErrorDetail.endErrorDetail(builder);
}

unpack(): ErrorDetailT {
  return new ErrorDetailT(
    this.code(),
    this.systemError(),
    this.lsn(),
    this.offset(),
    this.effectState()
  );
}


unpackTo(_o: ErrorDetailT): void {
  _o.code = this.code();
  _o.systemError = this.systemError();
  _o.lsn = this.lsn();
  _o.offset = this.offset();
  _o.effectState = this.effectState();
}
}

export class ErrorDetailT {
constructor(
  public code: number = 0,
  public systemError: number = 0,
  public lsn: bigint = BigInt('0'),
  public offset: bigint = BigInt('0'),
  public effectState: MutationEffectState = MutationEffectState.none
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ErrorDetail.createErrorDetail(builder,
    this.code,
    this.systemError,
    this.lsn,
    this.offset,
    this.effectState
  );
}
}
