// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Health {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Health {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHealth(bb:flatbuffers.ByteBuffer, obj?:Health):Health {
  return (obj || new Health()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHealth(bb:flatbuffers.ByteBuffer, obj?:Health):Health {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Health()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startHealth(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endHealth(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHealth(builder:flatbuffers.Builder):flatbuffers.Offset {
  Health.startHealth(builder);
  return Health.endHealth(builder);
}

unpack(): HealthT {
  return new HealthT();
}


unpackTo(_o: HealthT): void {}
}

export class HealthT {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Health.createHealth(builder);
}
}
