// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class LatencyHistograms {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LatencyHistograms {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLatencyHistograms(bb:flatbuffers.ByteBuffer, obj?:LatencyHistograms):LatencyHistograms {
  return (obj || new LatencyHistograms()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLatencyHistograms(bb:flatbuffers.ByteBuffer, obj?:LatencyHistograms):LatencyHistograms {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LatencyHistograms()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startLatencyHistograms(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endLatencyHistograms(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLatencyHistograms(builder:flatbuffers.Builder):flatbuffers.Offset {
  LatencyHistograms.startLatencyHistograms(builder);
  return LatencyHistograms.endLatencyHistograms(builder);
}

unpack(): LatencyHistogramsT {
  return new LatencyHistogramsT();
}


unpackTo(_o: LatencyHistogramsT): void {}
}

export class LatencyHistogramsT {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return LatencyHistograms.createLatencyHistograms(builder);
}
}
