// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class LatencyBucket {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LatencyBucket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLatencyBucket(bb:flatbuffers.ByteBuffer, obj?:LatencyBucket):LatencyBucket {
  return (obj || new LatencyBucket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLatencyBucket(bb:flatbuffers.ByteBuffer, obj?:LatencyBucket):LatencyBucket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LatencyBucket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

operation():string|null
operation(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
operation(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

upperBoundNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

count():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startLatencyBucket(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addOperation(builder:flatbuffers.Builder, operationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, operationOffset, 0);
}

static addUpperBoundNs(builder:flatbuffers.Builder, upperBoundNs:bigint) {
  builder.addFieldInt64(1, upperBoundNs, BigInt('0'));
}

static addCount(builder:flatbuffers.Builder, count:bigint) {
  builder.addFieldInt64(2, count, BigInt('0'));
}

static endLatencyBucket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // operation
  return offset;
}

static createLatencyBucket(builder:flatbuffers.Builder, operationOffset:flatbuffers.Offset, upperBoundNs:bigint, count:bigint):flatbuffers.Offset {
  LatencyBucket.startLatencyBucket(builder);
  LatencyBucket.addOperation(builder, operationOffset);
  LatencyBucket.addUpperBoundNs(builder, upperBoundNs);
  LatencyBucket.addCount(builder, count);
  return LatencyBucket.endLatencyBucket(builder);
}

unpack(): LatencyBucketT {
  return new LatencyBucketT(
    this.operation(),
    this.upperBoundNs(),
    this.count()
  );
}


unpackTo(_o: LatencyBucketT): void {
  _o.operation = this.operation();
  _o.upperBoundNs = this.upperBoundNs();
  _o.count = this.count();
}
}

export class LatencyBucketT {
constructor(
  public operation: string|Uint8Array|null = null,
  public upperBoundNs: bigint = BigInt('0'),
  public count: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const operation = (this.operation !== null ? builder.createString(this.operation!) : 0);

  return LatencyBucket.createLatencyBucket(builder,
    operation,
    this.upperBoundNs,
    this.count
  );
}
}
