// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Reads the latest persisted state for one turn identity.
 */
export class LatestCheckpoint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LatestCheckpoint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLatestCheckpoint(bb:flatbuffers.ByteBuffer, obj?:LatestCheckpoint):LatestCheckpoint {
  return (obj || new LatestCheckpoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLatestCheckpoint(bb:flatbuffers.ByteBuffer, obj?:LatestCheckpoint):LatestCheckpoint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LatestCheckpoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

turnId(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

turnIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

turnIdArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startLatestCheckpoint(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTurnId(builder:flatbuffers.Builder, turnIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, turnIdOffset, 0);
}

static createTurnIdVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startTurnIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endLatestCheckpoint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // turn_id
  return offset;
}

static createLatestCheckpoint(builder:flatbuffers.Builder, turnIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  LatestCheckpoint.startLatestCheckpoint(builder);
  LatestCheckpoint.addTurnId(builder, turnIdOffset);
  return LatestCheckpoint.endLatestCheckpoint(builder);
}

unpack(): LatestCheckpointT {
  return new LatestCheckpointT(
    this.bb!.createScalarList(this.turnId.bind(this), this.turnIdLength())
  );
}


unpackTo(_o: LatestCheckpointT): void {
  _o.turnId = this.bb!.createScalarList(this.turnId.bind(this), this.turnIdLength());
}
}

export class LatestCheckpointT {
constructor(
  public turnId: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const turnId = LatestCheckpoint.createTurnIdVector(builder, this.turnId);

  return LatestCheckpoint.createLatestCheckpoint(builder,
    turnId
  );
}
}
