// automatically generated by the FlatBuffers compiler, do not modify

import { Activate, ActivateT } from '../../hypermind/protocol/activate';
import { Append, AppendT } from '../../hypermind/protocol/append';
import { AsOf, AsOfT } from '../../hypermind/protocol/as-of';
import { Attest, AttestT } from '../../hypermind/protocol/attest';
import { Checkpoint, CheckpointT } from '../../hypermind/protocol/checkpoint';
import { CryptoDelete, CryptoDeleteT } from '../../hypermind/protocol/crypto-delete';
import { Health, HealthT } from '../../hypermind/protocol/health';
import { LatencyHistograms, LatencyHistogramsT } from '../../hypermind/protocol/latency-histograms';
import { LatestCheckpoint, LatestCheckpointT } from '../../hypermind/protocol/latest-checkpoint';
import { RebuildProjection, RebuildProjectionT } from '../../hypermind/protocol/rebuild-projection';
import { Recall, RecallT } from '../../hypermind/protocol/recall';
import { Stats, StatsT } from '../../hypermind/protocol/stats';
import { Subscribe, SubscribeT } from '../../hypermind/protocol/subscribe';
import { Transcript, TranscriptT } from '../../hypermind/protocol/transcript';
import { VerifyStatus, VerifyStatusT } from '../../hypermind/protocol/verify-status';


export enum RequestPayload {
  NONE = 0,
  Append = 1,
  Activate = 2,
  Transcript = 3,
  Recall = 4,
  AsOf = 5,
  Checkpoint = 6,
  LatestCheckpoint = 7,
  Attest = 8,
  Subscribe = 9,
  Health = 10,
  Stats = 11,
  LatencyHistograms = 12,
  VerifyStatus = 13,
  RebuildProjection = 14,
  CryptoDelete = 15
}

export function unionToRequestPayload(
  type: RequestPayload,
  accessor: (obj:Activate|Append|AsOf|Attest|Checkpoint|CryptoDelete|Health|LatencyHistograms|LatestCheckpoint|RebuildProjection|Recall|Stats|Subscribe|Transcript|VerifyStatus) => Activate|Append|AsOf|Attest|Checkpoint|CryptoDelete|Health|LatencyHistograms|LatestCheckpoint|RebuildProjection|Recall|Stats|Subscribe|Transcript|VerifyStatus|null
): Activate|Append|AsOf|Attest|Checkpoint|CryptoDelete|Health|LatencyHistograms|LatestCheckpoint|RebuildProjection|Recall|Stats|Subscribe|Transcript|VerifyStatus|null {
  switch(RequestPayload[type]) {
    case 'NONE': return null; 
    case 'Append': return accessor(new Append())! as Append;
    case 'Activate': return accessor(new Activate())! as Activate;
    case 'Transcript': return accessor(new Transcript())! as Transcript;
    case 'Recall': return accessor(new Recall())! as Recall;
    case 'AsOf': return accessor(new AsOf())! as AsOf;
    case 'Checkpoint': return accessor(new Checkpoint())! as Checkpoint;
    case 'LatestCheckpoint': return accessor(new LatestCheckpoint())! as LatestCheckpoint;
    case 'Attest': return accessor(new Attest())! as Attest;
    case 'Subscribe': return accessor(new Subscribe())! as Subscribe;
    case 'Health': return accessor(new Health())! as Health;
    case 'Stats': return accessor(new Stats())! as Stats;
    case 'LatencyHistograms': return accessor(new LatencyHistograms())! as LatencyHistograms;
    case 'VerifyStatus': return accessor(new VerifyStatus())! as VerifyStatus;
    case 'RebuildProjection': return accessor(new RebuildProjection())! as RebuildProjection;
    case 'CryptoDelete': return accessor(new CryptoDelete())! as CryptoDelete;
    default: return null;
  }
}

export function unionListToRequestPayload(
  type: RequestPayload, 
  accessor: (index: number, obj:Activate|Append|AsOf|Attest|Checkpoint|CryptoDelete|Health|LatencyHistograms|LatestCheckpoint|RebuildProjection|Recall|Stats|Subscribe|Transcript|VerifyStatus) => Activate|Append|AsOf|Attest|Checkpoint|CryptoDelete|Health|LatencyHistograms|LatestCheckpoint|RebuildProjection|Recall|Stats|Subscribe|Transcript|VerifyStatus|null, 
  index: number
): Activate|Append|AsOf|Attest|Checkpoint|CryptoDelete|Health|LatencyHistograms|LatestCheckpoint|RebuildProjection|Recall|Stats|Subscribe|Transcript|VerifyStatus|null {
  switch(RequestPayload[type]) {
    case 'NONE': return null; 
    case 'Append': return accessor(index, new Append())! as Append;
    case 'Activate': return accessor(index, new Activate())! as Activate;
    case 'Transcript': return accessor(index, new Transcript())! as Transcript;
    case 'Recall': return accessor(index, new Recall())! as Recall;
    case 'AsOf': return accessor(index, new AsOf())! as AsOf;
    case 'Checkpoint': return accessor(index, new Checkpoint())! as Checkpoint;
    case 'LatestCheckpoint': return accessor(index, new LatestCheckpoint())! as LatestCheckpoint;
    case 'Attest': return accessor(index, new Attest())! as Attest;
    case 'Subscribe': return accessor(index, new Subscribe())! as Subscribe;
    case 'Health': return accessor(index, new Health())! as Health;
    case 'Stats': return accessor(index, new Stats())! as Stats;
    case 'LatencyHistograms': return accessor(index, new LatencyHistograms())! as LatencyHistograms;
    case 'VerifyStatus': return accessor(index, new VerifyStatus())! as VerifyStatus;
    case 'RebuildProjection': return accessor(index, new RebuildProjection())! as RebuildProjection;
    case 'CryptoDelete': return accessor(index, new CryptoDelete())! as CryptoDelete;
    default: return null;
  }
}
