// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { AppendAck, AppendAckT } from '../../hypermind/protocol/append-ack';
import { AttestAck, AttestAckT } from '../../hypermind/protocol/attest-ack';
import { BeliefResult, BeliefResultT } from '../../hypermind/protocol/belief-result';
import { BytesResult, BytesResultT } from '../../hypermind/protocol/bytes-result';
import { CheckpointAck, CheckpointAckT } from '../../hypermind/protocol/checkpoint-ack';
import { CheckpointResult, CheckpointResultT } from '../../hypermind/protocol/checkpoint-result';
import { DeleteResult, DeleteResultT } from '../../hypermind/protocol/delete-result';
import { ErrorDetail, ErrorDetailT } from '../../hypermind/protocol/error-detail';
import { HealthResult, HealthResultT } from '../../hypermind/protocol/health-result';
import { LatencyResult, LatencyResultT } from '../../hypermind/protocol/latency-result';
import { RebuildResult, RebuildResultT } from '../../hypermind/protocol/rebuild-result';
import { RecallResult, RecallResultT } from '../../hypermind/protocol/recall-result';
import { ResponsePayload, unionToResponsePayload, unionListToResponsePayload } from '../../hypermind/protocol/response-payload';
import { ResponseStatus } from '../../hypermind/protocol/response-status';
import { StatsResult, StatsResultT } from '../../hypermind/protocol/stats-result';
import { SubscriptionAck, SubscriptionAckT } from '../../hypermind/protocol/subscription-ack';
import { TranscriptResult, TranscriptResultT } from '../../hypermind/protocol/transcript-result';
import { VerifyResult, VerifyResultT } from '../../hypermind/protocol/verify-result';


export class Response {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Response {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResponse(bb:flatbuffers.ByteBuffer, obj?:Response):Response {
  return (obj || new Response()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResponse(bb:flatbuffers.ByteBuffer, obj?:Response):Response {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Response()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

status():ResponseStatus {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ResponseStatus.ok;
}

payloadType():ResponsePayload {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ResponsePayload.NONE;
}

payload<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startResponse(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRequestId(builder:flatbuffers.Builder, requestId:bigint) {
  builder.addFieldInt64(0, requestId, BigInt('0'));
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatus) {
  builder.addFieldInt8(1, status, ResponseStatus.ok);
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:ResponsePayload) {
  builder.addFieldInt8(2, payloadType, ResponsePayload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, payloadOffset, 0);
}

static endResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResponse(builder:flatbuffers.Builder, requestId:bigint, status:ResponseStatus, payloadType:ResponsePayload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  Response.startResponse(builder);
  Response.addRequestId(builder, requestId);
  Response.addStatus(builder, status);
  Response.addPayloadType(builder, payloadType);
  Response.addPayload(builder, payloadOffset);
  return Response.endResponse(builder);
}

unpack(): ResponseT {
  return new ResponseT(
    this.requestId(),
    this.status(),
    this.payloadType(),
    (() => {
      let temp = unionToResponsePayload(this.payloadType(), this.payload.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: ResponseT): void {
  _o.requestId = this.requestId();
  _o.status = this.status();
  _o.payloadType = this.payloadType();
  _o.payload = (() => {
      let temp = unionToResponsePayload(this.payloadType(), this.payload.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class ResponseT {
constructor(
  public requestId: bigint = BigInt('0'),
  public status: ResponseStatus = ResponseStatus.ok,
  public payloadType: ResponsePayload = ResponsePayload.NONE,
  public payload: AppendAckT|AttestAckT|BeliefResultT|BytesResultT|CheckpointAckT|CheckpointResultT|DeleteResultT|ErrorDetailT|HealthResultT|LatencyResultT|RebuildResultT|RecallResultT|StatsResultT|SubscriptionAckT|TranscriptResultT|VerifyResultT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const payload = builder.createObjectOffset(this.payload);

  return Response.createResponse(builder,
    this.requestId,
    this.status,
    this.payloadType,
    payload
  );
}
}
