// automatically generated by the FlatBuffers compiler, do not modify

import { AppendAck, AppendAckT } from '../../hypermind/protocol/append-ack';
import { AttestAck, AttestAckT } from '../../hypermind/protocol/attest-ack';
import { BeliefResult, BeliefResultT } from '../../hypermind/protocol/belief-result';
import { BytesResult, BytesResultT } from '../../hypermind/protocol/bytes-result';
import { CheckpointAck, CheckpointAckT } from '../../hypermind/protocol/checkpoint-ack';
import { CheckpointResult, CheckpointResultT } from '../../hypermind/protocol/checkpoint-result';
import { DeleteResult, DeleteResultT } from '../../hypermind/protocol/delete-result';
import { ErrorDetail, ErrorDetailT } from '../../hypermind/protocol/error-detail';
import { HealthResult, HealthResultT } from '../../hypermind/protocol/health-result';
import { LatencyResult, LatencyResultT } from '../../hypermind/protocol/latency-result';
import { RebuildResult, RebuildResultT } from '../../hypermind/protocol/rebuild-result';
import { RecallResult, RecallResultT } from '../../hypermind/protocol/recall-result';
import { StatsResult, StatsResultT } from '../../hypermind/protocol/stats-result';
import { SubscriptionAck, SubscriptionAckT } from '../../hypermind/protocol/subscription-ack';
import { TranscriptResult, TranscriptResultT } from '../../hypermind/protocol/transcript-result';
import { VerifyResult, VerifyResultT } from '../../hypermind/protocol/verify-result';


export enum ResponsePayload {
  NONE = 0,
  ErrorDetail = 1,
  AppendAck = 2,
  BytesResult = 3,
  SubscriptionAck = 4,
  HealthResult = 5,
  StatsResult = 6,
  LatencyResult = 7,
  VerifyResult = 8,
  RebuildResult = 9,
  DeleteResult = 10,
  TranscriptResult = 11,
  RecallResult = 12,
  BeliefResult = 13,
  CheckpointAck = 14,
  CheckpointResult = 15,
  AttestAck = 16
}

export function unionToResponsePayload(
  type: ResponsePayload,
  accessor: (obj:AppendAck|AttestAck|BeliefResult|BytesResult|CheckpointAck|CheckpointResult|DeleteResult|ErrorDetail|HealthResult|LatencyResult|RebuildResult|RecallResult|StatsResult|SubscriptionAck|TranscriptResult|VerifyResult) => AppendAck|AttestAck|BeliefResult|BytesResult|CheckpointAck|CheckpointResult|DeleteResult|ErrorDetail|HealthResult|LatencyResult|RebuildResult|RecallResult|StatsResult|SubscriptionAck|TranscriptResult|VerifyResult|null
): AppendAck|AttestAck|BeliefResult|BytesResult|CheckpointAck|CheckpointResult|DeleteResult|ErrorDetail|HealthResult|LatencyResult|RebuildResult|RecallResult|StatsResult|SubscriptionAck|TranscriptResult|VerifyResult|null {
  switch(ResponsePayload[type]) {
    case 'NONE': return null; 
    case 'ErrorDetail': return accessor(new ErrorDetail())! as ErrorDetail;
    case 'AppendAck': return accessor(new AppendAck())! as AppendAck;
    case 'BytesResult': return accessor(new BytesResult())! as BytesResult;
    case 'SubscriptionAck': return accessor(new SubscriptionAck())! as SubscriptionAck;
    case 'HealthResult': return accessor(new HealthResult())! as HealthResult;
    case 'StatsResult': return accessor(new StatsResult())! as StatsResult;
    case 'LatencyResult': return accessor(new LatencyResult())! as LatencyResult;
    case 'VerifyResult': return accessor(new VerifyResult())! as VerifyResult;
    case 'RebuildResult': return accessor(new RebuildResult())! as RebuildResult;
    case 'DeleteResult': return accessor(new DeleteResult())! as DeleteResult;
    case 'TranscriptResult': return accessor(new TranscriptResult())! as TranscriptResult;
    case 'RecallResult': return accessor(new RecallResult())! as RecallResult;
    case 'BeliefResult': return accessor(new BeliefResult())! as BeliefResult;
    case 'CheckpointAck': return accessor(new CheckpointAck())! as CheckpointAck;
    case 'CheckpointResult': return accessor(new CheckpointResult())! as CheckpointResult;
    case 'AttestAck': return accessor(new AttestAck())! as AttestAck;
    default: return null;
  }
}

export function unionListToResponsePayload(
  type: ResponsePayload, 
  accessor: (index: number, obj:AppendAck|AttestAck|BeliefResult|BytesResult|CheckpointAck|CheckpointResult|DeleteResult|ErrorDetail|HealthResult|LatencyResult|RebuildResult|RecallResult|StatsResult|SubscriptionAck|TranscriptResult|VerifyResult) => AppendAck|AttestAck|BeliefResult|BytesResult|CheckpointAck|CheckpointResult|DeleteResult|ErrorDetail|HealthResult|LatencyResult|RebuildResult|RecallResult|StatsResult|SubscriptionAck|TranscriptResult|VerifyResult|null, 
  index: number
): AppendAck|AttestAck|BeliefResult|BytesResult|CheckpointAck|CheckpointResult|DeleteResult|ErrorDetail|HealthResult|LatencyResult|RebuildResult|RecallResult|StatsResult|SubscriptionAck|TranscriptResult|VerifyResult|null {
  switch(ResponsePayload[type]) {
    case 'NONE': return null; 
    case 'ErrorDetail': return accessor(index, new ErrorDetail())! as ErrorDetail;
    case 'AppendAck': return accessor(index, new AppendAck())! as AppendAck;
    case 'BytesResult': return accessor(index, new BytesResult())! as BytesResult;
    case 'SubscriptionAck': return accessor(index, new SubscriptionAck())! as SubscriptionAck;
    case 'HealthResult': return accessor(index, new HealthResult())! as HealthResult;
    case 'StatsResult': return accessor(index, new StatsResult())! as StatsResult;
    case 'LatencyResult': return accessor(index, new LatencyResult())! as LatencyResult;
    case 'VerifyResult': return accessor(index, new VerifyResult())! as VerifyResult;
    case 'RebuildResult': return accessor(index, new RebuildResult())! as RebuildResult;
    case 'DeleteResult': return accessor(index, new DeleteResult())! as DeleteResult;
    case 'TranscriptResult': return accessor(index, new TranscriptResult())! as TranscriptResult;
    case 'RecallResult': return accessor(index, new RecallResult())! as RecallResult;
    case 'BeliefResult': return accessor(index, new BeliefResult())! as BeliefResult;
    case 'CheckpointAck': return accessor(index, new CheckpointAck())! as CheckpointAck;
    case 'CheckpointResult': return accessor(index, new CheckpointResult())! as CheckpointResult;
    case 'AttestAck': return accessor(index, new AttestAck())! as AttestAck;
    default: return null;
  }
}
