// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ToolRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ToolRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsToolRequest(bb:flatbuffers.ByteBuffer, obj?:ToolRequest):ToolRequest {
  return (obj || new ToolRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsToolRequest(bb:flatbuffers.ByteBuffer, obj?:ToolRequest):ToolRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ToolRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

verb():string|null
verb(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
verb(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

argumentsJson(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

argumentsJsonLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

argumentsJsonArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startToolRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addVerb(builder:flatbuffers.Builder, verbOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, verbOffset, 0);
}

static addArgumentsJson(builder:flatbuffers.Builder, argumentsJsonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, argumentsJsonOffset, 0);
}

static createArgumentsJsonVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startArgumentsJsonVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endToolRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // verb
  builder.requiredField(offset, 6) // arguments_json
  return offset;
}

static createToolRequest(builder:flatbuffers.Builder, verbOffset:flatbuffers.Offset, argumentsJsonOffset:flatbuffers.Offset):flatbuffers.Offset {
  ToolRequest.startToolRequest(builder);
  ToolRequest.addVerb(builder, verbOffset);
  ToolRequest.addArgumentsJson(builder, argumentsJsonOffset);
  return ToolRequest.endToolRequest(builder);
}

unpack(): ToolRequestT {
  return new ToolRequestT(
    this.verb(),
    this.bb!.createScalarList(this.argumentsJson.bind(this), this.argumentsJsonLength())
  );
}


unpackTo(_o: ToolRequestT): void {
  _o.verb = this.verb();
  _o.argumentsJson = this.bb!.createScalarList(this.argumentsJson.bind(this), this.argumentsJsonLength());
}
}

export class ToolRequestT {
constructor(
  public verb: string|Uint8Array|null = null,
  public argumentsJson: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const verb = (this.verb !== null ? builder.createString(this.verb!) : 0);
  const argumentsJson = ToolRequest.createArgumentsJsonVector(builder, this.argumentsJson);

  return ToolRequest.createToolRequest(builder,
    verb,
    argumentsJson
  );
}
}
