// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Transcript {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Transcript {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTranscript(bb:flatbuffers.ByteBuffer, obj?:Transcript):Transcript {
  return (obj || new Transcript()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTranscript(bb:flatbuffers.ByteBuffer, obj?:Transcript):Transcript {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Transcript()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

conversation(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

conversationLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

conversationArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

sinceLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

limit():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startTranscript(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addConversation(builder:flatbuffers.Builder, conversationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, conversationOffset, 0);
}

static createConversationVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startConversationVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addSinceLsn(builder:flatbuffers.Builder, sinceLsn:bigint) {
  builder.addFieldInt64(1, sinceLsn, BigInt('0'));
}

static addLimit(builder:flatbuffers.Builder, limit:number) {
  builder.addFieldInt32(2, limit, 0);
}

static endTranscript(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // conversation
  return offset;
}

static createTranscript(builder:flatbuffers.Builder, conversationOffset:flatbuffers.Offset, sinceLsn:bigint, limit:number):flatbuffers.Offset {
  Transcript.startTranscript(builder);
  Transcript.addConversation(builder, conversationOffset);
  Transcript.addSinceLsn(builder, sinceLsn);
  Transcript.addLimit(builder, limit);
  return Transcript.endTranscript(builder);
}

unpack(): TranscriptT {
  return new TranscriptT(
    this.bb!.createScalarList(this.conversation.bind(this), this.conversationLength()),
    this.sinceLsn(),
    this.limit()
  );
}


unpackTo(_o: TranscriptT): void {
  _o.conversation = this.bb!.createScalarList(this.conversation.bind(this), this.conversationLength());
  _o.sinceLsn = this.sinceLsn();
  _o.limit = this.limit();
}
}

export class TranscriptT {
constructor(
  public conversation: (number)[] = [],
  public sinceLsn: bigint = BigInt('0'),
  public limit: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const conversation = Transcript.createConversationVector(builder, this.conversation);

  return Transcript.createTranscript(builder,
    conversation,
    this.sinceLsn,
    this.limit
  );
}
}
