# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Activate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Activate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsActivate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ActivateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # Activate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Activate
    def Conversation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Activate
    def ConversationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Activate
    def ConversationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Activate
    def ConversationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Activate
    def Query(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Activate
    def QueryAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Activate
    def QueryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Activate
    def QueryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Activate
    def TurnText(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Activate
    def TurnTextAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Activate
    def TurnTextLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Activate
    def TurnTextIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Activate
    def BudgetTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Activate
    def QueryEmbedding(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Activate
    def QueryEmbeddingAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Activate
    def QueryEmbeddingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Activate
    def QueryEmbeddingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Activate
    def QueryBinaryPrefilter(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Activate
    def QueryBinaryPrefilterAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Activate
    def QueryBinaryPrefilterLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Activate
    def QueryBinaryPrefilterIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Activate
    def TemporalFromNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Activate
    def TemporalToNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Activate
    def TokenWeights(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # Activate
    def TokenWeightsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # Activate
    def TokenWeightsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Activate
    def TokenWeightsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # Activate
    def TokenItemOverhead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ActivateStart(builder): builder.StartObject(10)
def Start(builder):
    return ActivateStart(builder)
def ActivateAddConversation(builder, conversation): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(conversation), 0)
def AddConversation(builder, conversation):
    return ActivateAddConversation(builder, conversation)
def ActivateStartConversationVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartConversationVector(builder, numElems):
    return ActivateStartConversationVector(builder, numElems)
def ActivateAddQuery(builder, query): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)
def AddQuery(builder, query):
    return ActivateAddQuery(builder, query)
def ActivateStartQueryVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartQueryVector(builder, numElems):
    return ActivateStartQueryVector(builder, numElems)
def ActivateAddTurnText(builder, turnText): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(turnText), 0)
def AddTurnText(builder, turnText):
    return ActivateAddTurnText(builder, turnText)
def ActivateStartTurnTextVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartTurnTextVector(builder, numElems):
    return ActivateStartTurnTextVector(builder, numElems)
def ActivateAddBudgetTokens(builder, budgetTokens): builder.PrependUint64Slot(3, budgetTokens, 0)
def AddBudgetTokens(builder, budgetTokens):
    return ActivateAddBudgetTokens(builder, budgetTokens)
def ActivateAddQueryEmbedding(builder, queryEmbedding): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(queryEmbedding), 0)
def AddQueryEmbedding(builder, queryEmbedding):
    return ActivateAddQueryEmbedding(builder, queryEmbedding)
def ActivateStartQueryEmbeddingVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartQueryEmbeddingVector(builder, numElems):
    return ActivateStartQueryEmbeddingVector(builder, numElems)
def ActivateAddQueryBinaryPrefilter(builder, queryBinaryPrefilter): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(queryBinaryPrefilter), 0)
def AddQueryBinaryPrefilter(builder, queryBinaryPrefilter):
    return ActivateAddQueryBinaryPrefilter(builder, queryBinaryPrefilter)
def ActivateStartQueryBinaryPrefilterVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartQueryBinaryPrefilterVector(builder, numElems):
    return ActivateStartQueryBinaryPrefilterVector(builder, numElems)
def ActivateAddTemporalFromNs(builder, temporalFromNs): builder.PrependInt64Slot(6, temporalFromNs, 0)
def AddTemporalFromNs(builder, temporalFromNs):
    return ActivateAddTemporalFromNs(builder, temporalFromNs)
def ActivateAddTemporalToNs(builder, temporalToNs): builder.PrependInt64Slot(7, temporalToNs, 0)
def AddTemporalToNs(builder, temporalToNs):
    return ActivateAddTemporalToNs(builder, temporalToNs)
def ActivateAddTokenWeights(builder, tokenWeights): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(tokenWeights), 0)
def AddTokenWeights(builder, tokenWeights):
    return ActivateAddTokenWeights(builder, tokenWeights)
def ActivateStartTokenWeightsVector(builder, numElems): return builder.StartVector(2, numElems, 2)
def StartTokenWeightsVector(builder, numElems):
    return ActivateStartTokenWeightsVector(builder, numElems)
def ActivateAddTokenItemOverhead(builder, tokenItemOverhead): builder.PrependUint32Slot(9, tokenItemOverhead, 0)
def AddTokenItemOverhead(builder, tokenItemOverhead):
    return ActivateAddTokenItemOverhead(builder, tokenItemOverhead)
def ActivateEnd(builder): return builder.EndObject()
def End(builder):
    return ActivateEnd(builder)
try:
    from typing import List
except:
    pass

class ActivateT(object):

    # ActivateT
    def __init__(self):
        self.conversation = None  # type: List[int]
        self.query = None  # type: List[int]
        self.turnText = None  # type: List[int]
        self.budgetTokens = 0  # type: int
        self.queryEmbedding = None  # type: List[int]
        self.queryBinaryPrefilter = None  # type: List[int]
        self.temporalFromNs = 0  # type: int
        self.temporalToNs = 0  # type: int
        self.tokenWeights = None  # type: List[int]
        self.tokenItemOverhead = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        activate = Activate()
        activate.Init(buf, pos)
        return cls.InitFromObj(activate)

    @classmethod
    def InitFromObj(cls, activate):
        x = ActivateT()
        x._UnPack(activate)
        return x

    # ActivateT
    def _UnPack(self, activate):
        if activate is None:
            return
        if not activate.ConversationIsNone():
            if np is None:
                self.conversation = []
                for i in range(activate.ConversationLength()):
                    self.conversation.append(activate.Conversation(i))
            else:
                self.conversation = activate.ConversationAsNumpy()
        if not activate.QueryIsNone():
            if np is None:
                self.query = []
                for i in range(activate.QueryLength()):
                    self.query.append(activate.Query(i))
            else:
                self.query = activate.QueryAsNumpy()
        if not activate.TurnTextIsNone():
            if np is None:
                self.turnText = []
                for i in range(activate.TurnTextLength()):
                    self.turnText.append(activate.TurnText(i))
            else:
                self.turnText = activate.TurnTextAsNumpy()
        self.budgetTokens = activate.BudgetTokens()
        if not activate.QueryEmbeddingIsNone():
            if np is None:
                self.queryEmbedding = []
                for i in range(activate.QueryEmbeddingLength()):
                    self.queryEmbedding.append(activate.QueryEmbedding(i))
            else:
                self.queryEmbedding = activate.QueryEmbeddingAsNumpy()
        if not activate.QueryBinaryPrefilterIsNone():
            if np is None:
                self.queryBinaryPrefilter = []
                for i in range(activate.QueryBinaryPrefilterLength()):
                    self.queryBinaryPrefilter.append(activate.QueryBinaryPrefilter(i))
            else:
                self.queryBinaryPrefilter = activate.QueryBinaryPrefilterAsNumpy()
        self.temporalFromNs = activate.TemporalFromNs()
        self.temporalToNs = activate.TemporalToNs()
        if not activate.TokenWeightsIsNone():
            if np is None:
                self.tokenWeights = []
                for i in range(activate.TokenWeightsLength()):
                    self.tokenWeights.append(activate.TokenWeights(i))
            else:
                self.tokenWeights = activate.TokenWeightsAsNumpy()
        self.tokenItemOverhead = activate.TokenItemOverhead()

    # ActivateT
    def Pack(self, builder):
        if self.conversation is not None:
            if np is not None and type(self.conversation) is np.ndarray:
                conversation = builder.CreateNumpyVector(self.conversation)
            else:
                ActivateStartConversationVector(builder, len(self.conversation))
                for i in reversed(range(len(self.conversation))):
                    builder.PrependUint8(self.conversation[i])
                conversation = builder.EndVector()
        if self.query is not None:
            if np is not None and type(self.query) is np.ndarray:
                query = builder.CreateNumpyVector(self.query)
            else:
                ActivateStartQueryVector(builder, len(self.query))
                for i in reversed(range(len(self.query))):
                    builder.PrependUint8(self.query[i])
                query = builder.EndVector()
        if self.turnText is not None:
            if np is not None and type(self.turnText) is np.ndarray:
                turnText = builder.CreateNumpyVector(self.turnText)
            else:
                ActivateStartTurnTextVector(builder, len(self.turnText))
                for i in reversed(range(len(self.turnText))):
                    builder.PrependUint8(self.turnText[i])
                turnText = builder.EndVector()
        if self.queryEmbedding is not None:
            if np is not None and type(self.queryEmbedding) is np.ndarray:
                queryEmbedding = builder.CreateNumpyVector(self.queryEmbedding)
            else:
                ActivateStartQueryEmbeddingVector(builder, len(self.queryEmbedding))
                for i in reversed(range(len(self.queryEmbedding))):
                    builder.PrependByte(self.queryEmbedding[i])
                queryEmbedding = builder.EndVector()
        if self.queryBinaryPrefilter is not None:
            if np is not None and type(self.queryBinaryPrefilter) is np.ndarray:
                queryBinaryPrefilter = builder.CreateNumpyVector(self.queryBinaryPrefilter)
            else:
                ActivateStartQueryBinaryPrefilterVector(builder, len(self.queryBinaryPrefilter))
                for i in reversed(range(len(self.queryBinaryPrefilter))):
                    builder.PrependUint8(self.queryBinaryPrefilter[i])
                queryBinaryPrefilter = builder.EndVector()
        if self.tokenWeights is not None:
            if np is not None and type(self.tokenWeights) is np.ndarray:
                tokenWeights = builder.CreateNumpyVector(self.tokenWeights)
            else:
                ActivateStartTokenWeightsVector(builder, len(self.tokenWeights))
                for i in reversed(range(len(self.tokenWeights))):
                    builder.PrependUint16(self.tokenWeights[i])
                tokenWeights = builder.EndVector()
        ActivateStart(builder)
        if self.conversation is not None:
            ActivateAddConversation(builder, conversation)
        if self.query is not None:
            ActivateAddQuery(builder, query)
        if self.turnText is not None:
            ActivateAddTurnText(builder, turnText)
        ActivateAddBudgetTokens(builder, self.budgetTokens)
        if self.queryEmbedding is not None:
            ActivateAddQueryEmbedding(builder, queryEmbedding)
        if self.queryBinaryPrefilter is not None:
            ActivateAddQueryBinaryPrefilter(builder, queryBinaryPrefilter)
        ActivateAddTemporalFromNs(builder, self.temporalFromNs)
        ActivateAddTemporalToNs(builder, self.temporalToNs)
        if self.tokenWeights is not None:
            ActivateAddTokenWeights(builder, tokenWeights)
        ActivateAddTokenItemOverhead(builder, self.tokenItemOverhead)
        activate = ActivateEnd(builder)
        return activate
