# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AsOf(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AsOf()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAsOf(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AsOfBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # AsOf
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AsOf
    def BeliefType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # AsOf
    def CanonicalIdentity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AsOf
    def ValidTimeNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # AsOf
    def TransactionLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AsOf
    def KnownLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AsOfStart(builder): builder.StartObject(5)
def Start(builder):
    return AsOfStart(builder)
def AsOfAddBeliefType(builder, beliefType): builder.PrependUint8Slot(0, beliefType, 0)
def AddBeliefType(builder, beliefType):
    return AsOfAddBeliefType(builder, beliefType)
def AsOfAddCanonicalIdentity(builder, canonicalIdentity): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(canonicalIdentity), 0)
def AddCanonicalIdentity(builder, canonicalIdentity):
    return AsOfAddCanonicalIdentity(builder, canonicalIdentity)
def AsOfAddValidTimeNs(builder, validTimeNs): builder.PrependInt64Slot(2, validTimeNs, 0)
def AddValidTimeNs(builder, validTimeNs):
    return AsOfAddValidTimeNs(builder, validTimeNs)
def AsOfAddTransactionLsn(builder, transactionLsn): builder.PrependUint64Slot(3, transactionLsn, 0)
def AddTransactionLsn(builder, transactionLsn):
    return AsOfAddTransactionLsn(builder, transactionLsn)
def AsOfAddKnownLsn(builder, knownLsn): builder.PrependUint64Slot(4, knownLsn, 0)
def AddKnownLsn(builder, knownLsn):
    return AsOfAddKnownLsn(builder, knownLsn)
def AsOfEnd(builder): return builder.EndObject()
def End(builder):
    return AsOfEnd(builder)

class AsOfT(object):

    # AsOfT
    def __init__(self):
        self.beliefType = 0  # type: int
        self.canonicalIdentity = None  # type: str
        self.validTimeNs = 0  # type: int
        self.transactionLsn = 0  # type: int
        self.knownLsn = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        asOf = AsOf()
        asOf.Init(buf, pos)
        return cls.InitFromObj(asOf)

    @classmethod
    def InitFromObj(cls, asOf):
        x = AsOfT()
        x._UnPack(asOf)
        return x

    # AsOfT
    def _UnPack(self, asOf):
        if asOf is None:
            return
        self.beliefType = asOf.BeliefType()
        self.canonicalIdentity = asOf.CanonicalIdentity()
        self.validTimeNs = asOf.ValidTimeNs()
        self.transactionLsn = asOf.TransactionLsn()
        self.knownLsn = asOf.KnownLsn()

    # AsOfT
    def Pack(self, builder):
        if self.canonicalIdentity is not None:
            canonicalIdentity = builder.CreateString(self.canonicalIdentity)
        AsOfStart(builder)
        AsOfAddBeliefType(builder, self.beliefType)
        if self.canonicalIdentity is not None:
            AsOfAddCanonicalIdentity(builder, canonicalIdentity)
        AsOfAddValidTimeNs(builder, self.validTimeNs)
        AsOfAddTransactionLsn(builder, self.transactionLsn)
        AsOfAddKnownLsn(builder, self.knownLsn)
        asOf = AsOfEnd(builder)
        return asOf
