# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BeliefProvenanceRecord(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BeliefProvenanceRecord()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBeliefProvenanceRecord(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BeliefProvenanceRecordBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # BeliefProvenanceRecord
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BeliefProvenanceRecord
    def FirstLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BeliefProvenanceRecord
    def LastLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BeliefProvenanceRecord
    def ByteStart(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BeliefProvenanceRecord
    def ByteEnd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def BeliefProvenanceRecordStart(builder): builder.StartObject(4)
def Start(builder):
    return BeliefProvenanceRecordStart(builder)
def BeliefProvenanceRecordAddFirstLsn(builder, firstLsn): builder.PrependUint64Slot(0, firstLsn, 0)
def AddFirstLsn(builder, firstLsn):
    return BeliefProvenanceRecordAddFirstLsn(builder, firstLsn)
def BeliefProvenanceRecordAddLastLsn(builder, lastLsn): builder.PrependUint64Slot(1, lastLsn, 0)
def AddLastLsn(builder, lastLsn):
    return BeliefProvenanceRecordAddLastLsn(builder, lastLsn)
def BeliefProvenanceRecordAddByteStart(builder, byteStart): builder.PrependUint32Slot(2, byteStart, 0)
def AddByteStart(builder, byteStart):
    return BeliefProvenanceRecordAddByteStart(builder, byteStart)
def BeliefProvenanceRecordAddByteEnd(builder, byteEnd): builder.PrependUint32Slot(3, byteEnd, 0)
def AddByteEnd(builder, byteEnd):
    return BeliefProvenanceRecordAddByteEnd(builder, byteEnd)
def BeliefProvenanceRecordEnd(builder): return builder.EndObject()
def End(builder):
    return BeliefProvenanceRecordEnd(builder)

class BeliefProvenanceRecordT(object):

    # BeliefProvenanceRecordT
    def __init__(self):
        self.firstLsn = 0  # type: int
        self.lastLsn = 0  # type: int
        self.byteStart = 0  # type: int
        self.byteEnd = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        beliefProvenanceRecord = BeliefProvenanceRecord()
        beliefProvenanceRecord.Init(buf, pos)
        return cls.InitFromObj(beliefProvenanceRecord)

    @classmethod
    def InitFromObj(cls, beliefProvenanceRecord):
        x = BeliefProvenanceRecordT()
        x._UnPack(beliefProvenanceRecord)
        return x

    # BeliefProvenanceRecordT
    def _UnPack(self, beliefProvenanceRecord):
        if beliefProvenanceRecord is None:
            return
        self.firstLsn = beliefProvenanceRecord.FirstLsn()
        self.lastLsn = beliefProvenanceRecord.LastLsn()
        self.byteStart = beliefProvenanceRecord.ByteStart()
        self.byteEnd = beliefProvenanceRecord.ByteEnd()

    # BeliefProvenanceRecordT
    def Pack(self, builder):
        BeliefProvenanceRecordStart(builder)
        BeliefProvenanceRecordAddFirstLsn(builder, self.firstLsn)
        BeliefProvenanceRecordAddLastLsn(builder, self.lastLsn)
        BeliefProvenanceRecordAddByteStart(builder, self.byteStart)
        BeliefProvenanceRecordAddByteEnd(builder, self.byteEnd)
        beliefProvenanceRecord = BeliefProvenanceRecordEnd(builder)
        return beliefProvenanceRecord
