# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BeliefResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BeliefResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBeliefResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BeliefResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # BeliefResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BeliefResult
    def Present(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # BeliefResult
    def BeliefType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # BeliefResult
    def BeliefId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BeliefResult
    def BeliefIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BeliefResult
    def BeliefIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BeliefResult
    def BeliefIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # BeliefResult
    def CanonicalIdentity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BeliefResult
    def ConflictDomain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BeliefResult
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BeliefResult
    def ValueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BeliefResult
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BeliefResult
    def ValueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # BeliefResult
    def Claim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # BeliefResult
    def ValidFromNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # BeliefResult
    def ValidToNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # BeliefResult
    def TransactionLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BeliefResult
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BeliefResult
    def SupersedesVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BeliefResult
    def Provenance(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from hypermind.protocol.BeliefProvenanceRecord import BeliefProvenanceRecord
            obj = BeliefProvenanceRecord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BeliefResult
    def ProvenanceLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BeliefResult
    def ProvenanceIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # BeliefResult
    def ConflictEdges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from hypermind.protocol.BeliefConflictRecord import BeliefConflictRecord
            obj = BeliefConflictRecord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BeliefResult
    def ConflictEdgesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BeliefResult
    def ConflictEdgesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # BeliefResult
    def Tombstoned(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BeliefResultStart(builder): builder.StartObject(15)
def Start(builder):
    return BeliefResultStart(builder)
def BeliefResultAddPresent(builder, present): builder.PrependBoolSlot(0, present, 0)
def AddPresent(builder, present):
    return BeliefResultAddPresent(builder, present)
def BeliefResultAddBeliefType(builder, beliefType): builder.PrependUint8Slot(1, beliefType, 0)
def AddBeliefType(builder, beliefType):
    return BeliefResultAddBeliefType(builder, beliefType)
def BeliefResultAddBeliefId(builder, beliefId): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(beliefId), 0)
def AddBeliefId(builder, beliefId):
    return BeliefResultAddBeliefId(builder, beliefId)
def BeliefResultStartBeliefIdVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartBeliefIdVector(builder, numElems):
    return BeliefResultStartBeliefIdVector(builder, numElems)
def BeliefResultAddCanonicalIdentity(builder, canonicalIdentity): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(canonicalIdentity), 0)
def AddCanonicalIdentity(builder, canonicalIdentity):
    return BeliefResultAddCanonicalIdentity(builder, canonicalIdentity)
def BeliefResultAddConflictDomain(builder, conflictDomain): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(conflictDomain), 0)
def AddConflictDomain(builder, conflictDomain):
    return BeliefResultAddConflictDomain(builder, conflictDomain)
def BeliefResultAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def AddValue(builder, value):
    return BeliefResultAddValue(builder, value)
def BeliefResultStartValueVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartValueVector(builder, numElems):
    return BeliefResultStartValueVector(builder, numElems)
def BeliefResultAddClaim(builder, claim): builder.PrependUint8Slot(6, claim, 0)
def AddClaim(builder, claim):
    return BeliefResultAddClaim(builder, claim)
def BeliefResultAddValidFromNs(builder, validFromNs): builder.PrependInt64Slot(7, validFromNs, 0)
def AddValidFromNs(builder, validFromNs):
    return BeliefResultAddValidFromNs(builder, validFromNs)
def BeliefResultAddValidToNs(builder, validToNs): builder.PrependInt64Slot(8, validToNs, 0)
def AddValidToNs(builder, validToNs):
    return BeliefResultAddValidToNs(builder, validToNs)
def BeliefResultAddTransactionLsn(builder, transactionLsn): builder.PrependUint64Slot(9, transactionLsn, 0)
def AddTransactionLsn(builder, transactionLsn):
    return BeliefResultAddTransactionLsn(builder, transactionLsn)
def BeliefResultAddVersion(builder, version): builder.PrependUint64Slot(10, version, 0)
def AddVersion(builder, version):
    return BeliefResultAddVersion(builder, version)
def BeliefResultAddSupersedesVersion(builder, supersedesVersion): builder.PrependUint64Slot(11, supersedesVersion, 0)
def AddSupersedesVersion(builder, supersedesVersion):
    return BeliefResultAddSupersedesVersion(builder, supersedesVersion)
def BeliefResultAddProvenance(builder, provenance): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)
def AddProvenance(builder, provenance):
    return BeliefResultAddProvenance(builder, provenance)
def BeliefResultStartProvenanceVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartProvenanceVector(builder, numElems):
    return BeliefResultStartProvenanceVector(builder, numElems)
def BeliefResultAddConflictEdges(builder, conflictEdges): builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(conflictEdges), 0)
def AddConflictEdges(builder, conflictEdges):
    return BeliefResultAddConflictEdges(builder, conflictEdges)
def BeliefResultStartConflictEdgesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartConflictEdgesVector(builder, numElems):
    return BeliefResultStartConflictEdgesVector(builder, numElems)
def BeliefResultAddTombstoned(builder, tombstoned): builder.PrependBoolSlot(14, tombstoned, 0)
def AddTombstoned(builder, tombstoned):
    return BeliefResultAddTombstoned(builder, tombstoned)
def BeliefResultEnd(builder): return builder.EndObject()
def End(builder):
    return BeliefResultEnd(builder)
import hypermind.protocol.BeliefConflictRecord
import hypermind.protocol.BeliefProvenanceRecord
try:
    from typing import List
except:
    pass

class BeliefResultT(object):

    # BeliefResultT
    def __init__(self):
        self.present = False  # type: bool
        self.beliefType = 0  # type: int
        self.beliefId = None  # type: List[int]
        self.canonicalIdentity = None  # type: str
        self.conflictDomain = None  # type: str
        self.value = None  # type: List[int]
        self.claim = 0  # type: int
        self.validFromNs = 0  # type: int
        self.validToNs = 0  # type: int
        self.transactionLsn = 0  # type: int
        self.version = 0  # type: int
        self.supersedesVersion = 0  # type: int
        self.provenance = None  # type: List[hypermind.protocol.BeliefProvenanceRecord.BeliefProvenanceRecordT]
        self.conflictEdges = None  # type: List[hypermind.protocol.BeliefConflictRecord.BeliefConflictRecordT]
        self.tombstoned = False  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        beliefResult = BeliefResult()
        beliefResult.Init(buf, pos)
        return cls.InitFromObj(beliefResult)

    @classmethod
    def InitFromObj(cls, beliefResult):
        x = BeliefResultT()
        x._UnPack(beliefResult)
        return x

    # BeliefResultT
    def _UnPack(self, beliefResult):
        if beliefResult is None:
            return
        self.present = beliefResult.Present()
        self.beliefType = beliefResult.BeliefType()
        if not beliefResult.BeliefIdIsNone():
            if np is None:
                self.beliefId = []
                for i in range(beliefResult.BeliefIdLength()):
                    self.beliefId.append(beliefResult.BeliefId(i))
            else:
                self.beliefId = beliefResult.BeliefIdAsNumpy()
        self.canonicalIdentity = beliefResult.CanonicalIdentity()
        self.conflictDomain = beliefResult.ConflictDomain()
        if not beliefResult.ValueIsNone():
            if np is None:
                self.value = []
                for i in range(beliefResult.ValueLength()):
                    self.value.append(beliefResult.Value(i))
            else:
                self.value = beliefResult.ValueAsNumpy()
        self.claim = beliefResult.Claim()
        self.validFromNs = beliefResult.ValidFromNs()
        self.validToNs = beliefResult.ValidToNs()
        self.transactionLsn = beliefResult.TransactionLsn()
        self.version = beliefResult.Version()
        self.supersedesVersion = beliefResult.SupersedesVersion()
        if not beliefResult.ProvenanceIsNone():
            self.provenance = []
            for i in range(beliefResult.ProvenanceLength()):
                if beliefResult.Provenance(i) is None:
                    self.provenance.append(None)
                else:
                    beliefProvenanceRecord_ = hypermind.protocol.BeliefProvenanceRecord.BeliefProvenanceRecordT.InitFromObj(beliefResult.Provenance(i))
                    self.provenance.append(beliefProvenanceRecord_)
        if not beliefResult.ConflictEdgesIsNone():
            self.conflictEdges = []
            for i in range(beliefResult.ConflictEdgesLength()):
                if beliefResult.ConflictEdges(i) is None:
                    self.conflictEdges.append(None)
                else:
                    beliefConflictRecord_ = hypermind.protocol.BeliefConflictRecord.BeliefConflictRecordT.InitFromObj(beliefResult.ConflictEdges(i))
                    self.conflictEdges.append(beliefConflictRecord_)
        self.tombstoned = beliefResult.Tombstoned()

    # BeliefResultT
    def Pack(self, builder):
        if self.beliefId is not None:
            if np is not None and type(self.beliefId) is np.ndarray:
                beliefId = builder.CreateNumpyVector(self.beliefId)
            else:
                BeliefResultStartBeliefIdVector(builder, len(self.beliefId))
                for i in reversed(range(len(self.beliefId))):
                    builder.PrependUint8(self.beliefId[i])
                beliefId = builder.EndVector()
        if self.canonicalIdentity is not None:
            canonicalIdentity = builder.CreateString(self.canonicalIdentity)
        if self.conflictDomain is not None:
            conflictDomain = builder.CreateString(self.conflictDomain)
        if self.value is not None:
            if np is not None and type(self.value) is np.ndarray:
                value = builder.CreateNumpyVector(self.value)
            else:
                BeliefResultStartValueVector(builder, len(self.value))
                for i in reversed(range(len(self.value))):
                    builder.PrependUint8(self.value[i])
                value = builder.EndVector()
        if self.provenance is not None:
            provenancelist = []
            for i in range(len(self.provenance)):
                provenancelist.append(self.provenance[i].Pack(builder))
            BeliefResultStartProvenanceVector(builder, len(self.provenance))
            for i in reversed(range(len(self.provenance))):
                builder.PrependUOffsetTRelative(provenancelist[i])
            provenance = builder.EndVector()
        if self.conflictEdges is not None:
            conflictEdgeslist = []
            for i in range(len(self.conflictEdges)):
                conflictEdgeslist.append(self.conflictEdges[i].Pack(builder))
            BeliefResultStartConflictEdgesVector(builder, len(self.conflictEdges))
            for i in reversed(range(len(self.conflictEdges))):
                builder.PrependUOffsetTRelative(conflictEdgeslist[i])
            conflictEdges = builder.EndVector()
        BeliefResultStart(builder)
        BeliefResultAddPresent(builder, self.present)
        BeliefResultAddBeliefType(builder, self.beliefType)
        if self.beliefId is not None:
            BeliefResultAddBeliefId(builder, beliefId)
        if self.canonicalIdentity is not None:
            BeliefResultAddCanonicalIdentity(builder, canonicalIdentity)
        if self.conflictDomain is not None:
            BeliefResultAddConflictDomain(builder, conflictDomain)
        if self.value is not None:
            BeliefResultAddValue(builder, value)
        BeliefResultAddClaim(builder, self.claim)
        BeliefResultAddValidFromNs(builder, self.validFromNs)
        BeliefResultAddValidToNs(builder, self.validToNs)
        BeliefResultAddTransactionLsn(builder, self.transactionLsn)
        BeliefResultAddVersion(builder, self.version)
        BeliefResultAddSupersedesVersion(builder, self.supersedesVersion)
        if self.provenance is not None:
            BeliefResultAddProvenance(builder, provenance)
        if self.conflictEdges is not None:
            BeliefResultAddConflictEdges(builder, conflictEdges)
        BeliefResultAddTombstoned(builder, self.tombstoned)
        beliefResult = BeliefResultEnd(builder)
        return beliefResult
