# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BytesResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BytesResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBytesResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BytesResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # BytesResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BytesResult
    def Bytes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BytesResult
    def BytesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BytesResult
    def BytesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BytesResult
    def BytesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BytesResultStart(builder): builder.StartObject(1)
def Start(builder):
    return BytesResultStart(builder)
def BytesResultAddBytes(builder, bytes): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bytes), 0)
def AddBytes(builder, bytes):
    return BytesResultAddBytes(builder, bytes)
def BytesResultStartBytesVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartBytesVector(builder, numElems):
    return BytesResultStartBytesVector(builder, numElems)
def BytesResultEnd(builder): return builder.EndObject()
def End(builder):
    return BytesResultEnd(builder)
try:
    from typing import List
except:
    pass

class BytesResultT(object):

    # BytesResultT
    def __init__(self):
        self.bytes = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bytesResult = BytesResult()
        bytesResult.Init(buf, pos)
        return cls.InitFromObj(bytesResult)

    @classmethod
    def InitFromObj(cls, bytesResult):
        x = BytesResultT()
        x._UnPack(bytesResult)
        return x

    # BytesResultT
    def _UnPack(self, bytesResult):
        if bytesResult is None:
            return
        if not bytesResult.BytesIsNone():
            if np is None:
                self.bytes = []
                for i in range(bytesResult.BytesLength()):
                    self.bytes.append(bytesResult.Bytes(i))
            else:
                self.bytes = bytesResult.BytesAsNumpy()

    # BytesResultT
    def Pack(self, builder):
        if self.bytes is not None:
            if np is not None and type(self.bytes) is np.ndarray:
                bytes = builder.CreateNumpyVector(self.bytes)
            else:
                BytesResultStartBytesVector(builder, len(self.bytes))
                for i in reversed(range(len(self.bytes))):
                    builder.PrependUint8(self.bytes[i])
                bytes = builder.EndVector()
        BytesResultStart(builder)
        if self.bytes is not None:
            BytesResultAddBytes(builder, bytes)
        bytesResult = BytesResultEnd(builder)
        return bytesResult
