# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Identifies the ledger record containing the accepted checkpoint.
class CheckpointAck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CheckpointAck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCheckpointAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CheckpointAckBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # CheckpointAck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CheckpointAck
    def Lsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CheckpointAckStart(builder): builder.StartObject(1)
def Start(builder):
    return CheckpointAckStart(builder)
def CheckpointAckAddLsn(builder, lsn): builder.PrependUint64Slot(0, lsn, 0)
def AddLsn(builder, lsn):
    return CheckpointAckAddLsn(builder, lsn)
def CheckpointAckEnd(builder): return builder.EndObject()
def End(builder):
    return CheckpointAckEnd(builder)

class CheckpointAckT(object):

    # CheckpointAckT
    def __init__(self):
        self.lsn = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        checkpointAck = CheckpointAck()
        checkpointAck.Init(buf, pos)
        return cls.InitFromObj(checkpointAck)

    @classmethod
    def InitFromObj(cls, checkpointAck):
        x = CheckpointAckT()
        x._UnPack(checkpointAck)
        return x

    # CheckpointAckT
    def _UnPack(self, checkpointAck):
        if checkpointAck is None:
            return
        self.lsn = checkpointAck.Lsn()

    # CheckpointAckT
    def Pack(self, builder):
        CheckpointAckStart(builder)
        CheckpointAckAddLsn(builder, self.lsn)
        checkpointAck = CheckpointAckEnd(builder)
        return checkpointAck
