# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Persists an opaque turn state with client-sequence idempotency.
class Checkpoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Checkpoint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCheckpoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CheckpointBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # Checkpoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Checkpoint
    def TurnId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Checkpoint
    def TurnIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Checkpoint
    def TurnIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Checkpoint
    def TurnIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Checkpoint
    def Blob(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Checkpoint
    def BlobAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Checkpoint
    def BlobLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Checkpoint
    def BlobIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Checkpoint
    def ClientSeq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CheckpointStart(builder): builder.StartObject(3)
def Start(builder):
    return CheckpointStart(builder)
def CheckpointAddTurnId(builder, turnId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(turnId), 0)
def AddTurnId(builder, turnId):
    return CheckpointAddTurnId(builder, turnId)
def CheckpointStartTurnIdVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartTurnIdVector(builder, numElems):
    return CheckpointStartTurnIdVector(builder, numElems)
def CheckpointAddBlob(builder, blob): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(blob), 0)
def AddBlob(builder, blob):
    return CheckpointAddBlob(builder, blob)
def CheckpointStartBlobVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartBlobVector(builder, numElems):
    return CheckpointStartBlobVector(builder, numElems)
def CheckpointAddClientSeq(builder, clientSeq): builder.PrependUint64Slot(2, clientSeq, 0)
def AddClientSeq(builder, clientSeq):
    return CheckpointAddClientSeq(builder, clientSeq)
def CheckpointEnd(builder): return builder.EndObject()
def End(builder):
    return CheckpointEnd(builder)
try:
    from typing import List
except:
    pass

class CheckpointT(object):

    # CheckpointT
    def __init__(self):
        self.turnId = None  # type: List[int]
        self.blob = None  # type: List[int]
        self.clientSeq = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        checkpoint = Checkpoint()
        checkpoint.Init(buf, pos)
        return cls.InitFromObj(checkpoint)

    @classmethod
    def InitFromObj(cls, checkpoint):
        x = CheckpointT()
        x._UnPack(checkpoint)
        return x

    # CheckpointT
    def _UnPack(self, checkpoint):
        if checkpoint is None:
            return
        if not checkpoint.TurnIdIsNone():
            if np is None:
                self.turnId = []
                for i in range(checkpoint.TurnIdLength()):
                    self.turnId.append(checkpoint.TurnId(i))
            else:
                self.turnId = checkpoint.TurnIdAsNumpy()
        if not checkpoint.BlobIsNone():
            if np is None:
                self.blob = []
                for i in range(checkpoint.BlobLength()):
                    self.blob.append(checkpoint.Blob(i))
            else:
                self.blob = checkpoint.BlobAsNumpy()
        self.clientSeq = checkpoint.ClientSeq()

    # CheckpointT
    def Pack(self, builder):
        if self.turnId is not None:
            if np is not None and type(self.turnId) is np.ndarray:
                turnId = builder.CreateNumpyVector(self.turnId)
            else:
                CheckpointStartTurnIdVector(builder, len(self.turnId))
                for i in reversed(range(len(self.turnId))):
                    builder.PrependUint8(self.turnId[i])
                turnId = builder.EndVector()
        if self.blob is not None:
            if np is not None and type(self.blob) is np.ndarray:
                blob = builder.CreateNumpyVector(self.blob)
            else:
                CheckpointStartBlobVector(builder, len(self.blob))
                for i in reversed(range(len(self.blob))):
                    builder.PrependUint8(self.blob[i])
                blob = builder.EndVector()
        CheckpointStart(builder)
        if self.turnId is not None:
            CheckpointAddTurnId(builder, turnId)
        if self.blob is not None:
            CheckpointAddBlob(builder, blob)
        CheckpointAddClientSeq(builder, self.clientSeq)
        checkpoint = CheckpointEnd(builder)
        return checkpoint
