# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CryptoDelete(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CryptoDelete()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCryptoDelete(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CryptoDeleteBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # CryptoDelete
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CryptoDelete
    def Actor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def CryptoDeleteStart(builder): builder.StartObject(1)
def Start(builder):
    return CryptoDeleteStart(builder)
def CryptoDeleteAddActor(builder, actor): builder.PrependUint16Slot(0, actor, 0)
def AddActor(builder, actor):
    return CryptoDeleteAddActor(builder, actor)
def CryptoDeleteEnd(builder): return builder.EndObject()
def End(builder):
    return CryptoDeleteEnd(builder)

class CryptoDeleteT(object):

    # CryptoDeleteT
    def __init__(self):
        self.actor = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cryptoDelete = CryptoDelete()
        cryptoDelete.Init(buf, pos)
        return cls.InitFromObj(cryptoDelete)

    @classmethod
    def InitFromObj(cls, cryptoDelete):
        x = CryptoDeleteT()
        x._UnPack(cryptoDelete)
        return x

    # CryptoDeleteT
    def _UnPack(self, cryptoDelete):
        if cryptoDelete is None:
            return
        self.actor = cryptoDelete.Actor()

    # CryptoDeleteT
    def Pack(self, builder):
        CryptoDeleteStart(builder)
        CryptoDeleteAddActor(builder, self.actor)
        cryptoDelete = CryptoDeleteEnd(builder)
        return cryptoDelete
