# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Pushes one committed ledger event to a subscriber.
class Event(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Event()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EventBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # Event
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Event
    def SubscriptionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Event
    def Lsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Event
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Event
    def WallTimestampNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Event
    def Actor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Event
    def Conversation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Event
    def ConversationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Event
    def ConversationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Event
    def ConversationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Event
    def Payload(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Event
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Event
    def PayloadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Event
    def PayloadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def EventStart(builder): builder.StartObject(7)
def Start(builder):
    return EventStart(builder)
def EventAddSubscriptionId(builder, subscriptionId): builder.PrependUint64Slot(0, subscriptionId, 0)
def AddSubscriptionId(builder, subscriptionId):
    return EventAddSubscriptionId(builder, subscriptionId)
def EventAddLsn(builder, lsn): builder.PrependUint64Slot(1, lsn, 0)
def AddLsn(builder, lsn):
    return EventAddLsn(builder, lsn)
def EventAddKind(builder, kind): builder.PrependUint8Slot(2, kind, 0)
def AddKind(builder, kind):
    return EventAddKind(builder, kind)
def EventAddWallTimestampNs(builder, wallTimestampNs): builder.PrependInt64Slot(3, wallTimestampNs, 0)
def AddWallTimestampNs(builder, wallTimestampNs):
    return EventAddWallTimestampNs(builder, wallTimestampNs)
def EventAddActor(builder, actor): builder.PrependUint16Slot(4, actor, 0)
def AddActor(builder, actor):
    return EventAddActor(builder, actor)
def EventAddConversation(builder, conversation): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(conversation), 0)
def AddConversation(builder, conversation):
    return EventAddConversation(builder, conversation)
def EventStartConversationVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartConversationVector(builder, numElems):
    return EventStartConversationVector(builder, numElems)
def EventAddPayload(builder, payload): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)
def AddPayload(builder, payload):
    return EventAddPayload(builder, payload)
def EventStartPayloadVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartPayloadVector(builder, numElems):
    return EventStartPayloadVector(builder, numElems)
def EventEnd(builder): return builder.EndObject()
def End(builder):
    return EventEnd(builder)
try:
    from typing import List
except:
    pass

class EventT(object):

    # EventT
    def __init__(self):
        self.subscriptionId = 0  # type: int
        self.lsn = 0  # type: int
        self.kind = 0  # type: int
        self.wallTimestampNs = 0  # type: int
        self.actor = 0  # type: int
        self.conversation = None  # type: List[int]
        self.payload = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        event = Event()
        event.Init(buf, pos)
        return cls.InitFromObj(event)

    @classmethod
    def InitFromObj(cls, event):
        x = EventT()
        x._UnPack(event)
        return x

    # EventT
    def _UnPack(self, event):
        if event is None:
            return
        self.subscriptionId = event.SubscriptionId()
        self.lsn = event.Lsn()
        self.kind = event.Kind()
        self.wallTimestampNs = event.WallTimestampNs()
        self.actor = event.Actor()
        if not event.ConversationIsNone():
            if np is None:
                self.conversation = []
                for i in range(event.ConversationLength()):
                    self.conversation.append(event.Conversation(i))
            else:
                self.conversation = event.ConversationAsNumpy()
        if not event.PayloadIsNone():
            if np is None:
                self.payload = []
                for i in range(event.PayloadLength()):
                    self.payload.append(event.Payload(i))
            else:
                self.payload = event.PayloadAsNumpy()

    # EventT
    def Pack(self, builder):
        if self.conversation is not None:
            if np is not None and type(self.conversation) is np.ndarray:
                conversation = builder.CreateNumpyVector(self.conversation)
            else:
                EventStartConversationVector(builder, len(self.conversation))
                for i in reversed(range(len(self.conversation))):
                    builder.PrependUint8(self.conversation[i])
                conversation = builder.EndVector()
        if self.payload is not None:
            if np is not None and type(self.payload) is np.ndarray:
                payload = builder.CreateNumpyVector(self.payload)
            else:
                EventStartPayloadVector(builder, len(self.payload))
                for i in reversed(range(len(self.payload))):
                    builder.PrependUint8(self.payload[i])
                payload = builder.EndVector()
        EventStart(builder)
        EventAddSubscriptionId(builder, self.subscriptionId)
        EventAddLsn(builder, self.lsn)
        EventAddKind(builder, self.kind)
        EventAddWallTimestampNs(builder, self.wallTimestampNs)
        EventAddActor(builder, self.actor)
        if self.conversation is not None:
            EventAddConversation(builder, conversation)
        if self.payload is not None:
            EventAddPayload(builder, payload)
        event = EventEnd(builder)
        return event
