# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FrameRecord(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FrameRecord()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFrameRecord(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FrameRecordBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # FrameRecord
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FrameRecord
    def Lsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FrameRecord
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FrameRecord
    def WallTimestampNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FrameRecord
    def Actor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FrameRecord
    def Conversation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FrameRecord
    def ConversationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FrameRecord
    def ConversationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FrameRecord
    def ConversationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # FrameRecord
    def Payload(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FrameRecord
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FrameRecord
    def PayloadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FrameRecord
    def PayloadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def FrameRecordStart(builder): builder.StartObject(6)
def Start(builder):
    return FrameRecordStart(builder)
def FrameRecordAddLsn(builder, lsn): builder.PrependUint64Slot(0, lsn, 0)
def AddLsn(builder, lsn):
    return FrameRecordAddLsn(builder, lsn)
def FrameRecordAddKind(builder, kind): builder.PrependUint8Slot(1, kind, 0)
def AddKind(builder, kind):
    return FrameRecordAddKind(builder, kind)
def FrameRecordAddWallTimestampNs(builder, wallTimestampNs): builder.PrependInt64Slot(2, wallTimestampNs, 0)
def AddWallTimestampNs(builder, wallTimestampNs):
    return FrameRecordAddWallTimestampNs(builder, wallTimestampNs)
def FrameRecordAddActor(builder, actor): builder.PrependUint16Slot(3, actor, 0)
def AddActor(builder, actor):
    return FrameRecordAddActor(builder, actor)
def FrameRecordAddConversation(builder, conversation): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(conversation), 0)
def AddConversation(builder, conversation):
    return FrameRecordAddConversation(builder, conversation)
def FrameRecordStartConversationVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartConversationVector(builder, numElems):
    return FrameRecordStartConversationVector(builder, numElems)
def FrameRecordAddPayload(builder, payload): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)
def AddPayload(builder, payload):
    return FrameRecordAddPayload(builder, payload)
def FrameRecordStartPayloadVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartPayloadVector(builder, numElems):
    return FrameRecordStartPayloadVector(builder, numElems)
def FrameRecordEnd(builder): return builder.EndObject()
def End(builder):
    return FrameRecordEnd(builder)
try:
    from typing import List
except:
    pass

class FrameRecordT(object):

    # FrameRecordT
    def __init__(self):
        self.lsn = 0  # type: int
        self.kind = 0  # type: int
        self.wallTimestampNs = 0  # type: int
        self.actor = 0  # type: int
        self.conversation = None  # type: List[int]
        self.payload = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        frameRecord = FrameRecord()
        frameRecord.Init(buf, pos)
        return cls.InitFromObj(frameRecord)

    @classmethod
    def InitFromObj(cls, frameRecord):
        x = FrameRecordT()
        x._UnPack(frameRecord)
        return x

    # FrameRecordT
    def _UnPack(self, frameRecord):
        if frameRecord is None:
            return
        self.lsn = frameRecord.Lsn()
        self.kind = frameRecord.Kind()
        self.wallTimestampNs = frameRecord.WallTimestampNs()
        self.actor = frameRecord.Actor()
        if not frameRecord.ConversationIsNone():
            if np is None:
                self.conversation = []
                for i in range(frameRecord.ConversationLength()):
                    self.conversation.append(frameRecord.Conversation(i))
            else:
                self.conversation = frameRecord.ConversationAsNumpy()
        if not frameRecord.PayloadIsNone():
            if np is None:
                self.payload = []
                for i in range(frameRecord.PayloadLength()):
                    self.payload.append(frameRecord.Payload(i))
            else:
                self.payload = frameRecord.PayloadAsNumpy()

    # FrameRecordT
    def Pack(self, builder):
        if self.conversation is not None:
            if np is not None and type(self.conversation) is np.ndarray:
                conversation = builder.CreateNumpyVector(self.conversation)
            else:
                FrameRecordStartConversationVector(builder, len(self.conversation))
                for i in reversed(range(len(self.conversation))):
                    builder.PrependUint8(self.conversation[i])
                conversation = builder.EndVector()
        if self.payload is not None:
            if np is not None and type(self.payload) is np.ndarray:
                payload = builder.CreateNumpyVector(self.payload)
            else:
                FrameRecordStartPayloadVector(builder, len(self.payload))
                for i in reversed(range(len(self.payload))):
                    builder.PrependUint8(self.payload[i])
                payload = builder.EndVector()
        FrameRecordStart(builder)
        FrameRecordAddLsn(builder, self.lsn)
        FrameRecordAddKind(builder, self.kind)
        FrameRecordAddWallTimestampNs(builder, self.wallTimestampNs)
        FrameRecordAddActor(builder, self.actor)
        if self.conversation is not None:
            FrameRecordAddConversation(builder, conversation)
        if self.payload is not None:
            FrameRecordAddPayload(builder, payload)
        frameRecord = FrameRecordEnd(builder)
        return frameRecord
