# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Hello(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Hello()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHello(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HelloBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # Hello
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Hello
    def ProtoVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Hello
    def ConnectionId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Hello
    def ConnectionIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Hello
    def ConnectionIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Hello
    def ConnectionIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Hello
    def CapabilityToken(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Hello
    def CapabilityTokenAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Hello
    def CapabilityTokenLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Hello
    def CapabilityTokenIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def HelloStart(builder): builder.StartObject(3)
def Start(builder):
    return HelloStart(builder)
def HelloAddProtoVersion(builder, protoVersion): builder.PrependUint16Slot(0, protoVersion, 0)
def AddProtoVersion(builder, protoVersion):
    return HelloAddProtoVersion(builder, protoVersion)
def HelloAddConnectionId(builder, connectionId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(connectionId), 0)
def AddConnectionId(builder, connectionId):
    return HelloAddConnectionId(builder, connectionId)
def HelloStartConnectionIdVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartConnectionIdVector(builder, numElems):
    return HelloStartConnectionIdVector(builder, numElems)
def HelloAddCapabilityToken(builder, capabilityToken): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(capabilityToken), 0)
def AddCapabilityToken(builder, capabilityToken):
    return HelloAddCapabilityToken(builder, capabilityToken)
def HelloStartCapabilityTokenVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartCapabilityTokenVector(builder, numElems):
    return HelloStartCapabilityTokenVector(builder, numElems)
def HelloEnd(builder): return builder.EndObject()
def End(builder):
    return HelloEnd(builder)
try:
    from typing import List
except:
    pass

class HelloT(object):

    # HelloT
    def __init__(self):
        self.protoVersion = 0  # type: int
        self.connectionId = None  # type: List[int]
        self.capabilityToken = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        hello = Hello()
        hello.Init(buf, pos)
        return cls.InitFromObj(hello)

    @classmethod
    def InitFromObj(cls, hello):
        x = HelloT()
        x._UnPack(hello)
        return x

    # HelloT
    def _UnPack(self, hello):
        if hello is None:
            return
        self.protoVersion = hello.ProtoVersion()
        if not hello.ConnectionIdIsNone():
            if np is None:
                self.connectionId = []
                for i in range(hello.ConnectionIdLength()):
                    self.connectionId.append(hello.ConnectionId(i))
            else:
                self.connectionId = hello.ConnectionIdAsNumpy()
        if not hello.CapabilityTokenIsNone():
            if np is None:
                self.capabilityToken = []
                for i in range(hello.CapabilityTokenLength()):
                    self.capabilityToken.append(hello.CapabilityToken(i))
            else:
                self.capabilityToken = hello.CapabilityTokenAsNumpy()

    # HelloT
    def Pack(self, builder):
        if self.connectionId is not None:
            if np is not None and type(self.connectionId) is np.ndarray:
                connectionId = builder.CreateNumpyVector(self.connectionId)
            else:
                HelloStartConnectionIdVector(builder, len(self.connectionId))
                for i in reversed(range(len(self.connectionId))):
                    builder.PrependUint8(self.connectionId[i])
                connectionId = builder.EndVector()
        if self.capabilityToken is not None:
            if np is not None and type(self.capabilityToken) is np.ndarray:
                capabilityToken = builder.CreateNumpyVector(self.capabilityToken)
            else:
                HelloStartCapabilityTokenVector(builder, len(self.capabilityToken))
                for i in reversed(range(len(self.capabilityToken))):
                    builder.PrependUint8(self.capabilityToken[i])
                capabilityToken = builder.EndVector()
        HelloStart(builder)
        HelloAddProtoVersion(builder, self.protoVersion)
        if self.connectionId is not None:
            HelloAddConnectionId(builder, connectionId)
        if self.capabilityToken is not None:
            HelloAddCapabilityToken(builder, capabilityToken)
        hello = HelloEnd(builder)
        return hello
