# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Reads the latest persisted state for one turn identity.
class LatestCheckpoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LatestCheckpoint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLatestCheckpoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LatestCheckpointBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # LatestCheckpoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LatestCheckpoint
    def TurnId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # LatestCheckpoint
    def TurnIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # LatestCheckpoint
    def TurnIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LatestCheckpoint
    def TurnIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def LatestCheckpointStart(builder): builder.StartObject(1)
def Start(builder):
    return LatestCheckpointStart(builder)
def LatestCheckpointAddTurnId(builder, turnId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(turnId), 0)
def AddTurnId(builder, turnId):
    return LatestCheckpointAddTurnId(builder, turnId)
def LatestCheckpointStartTurnIdVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartTurnIdVector(builder, numElems):
    return LatestCheckpointStartTurnIdVector(builder, numElems)
def LatestCheckpointEnd(builder): return builder.EndObject()
def End(builder):
    return LatestCheckpointEnd(builder)
try:
    from typing import List
except:
    pass

class LatestCheckpointT(object):

    # LatestCheckpointT
    def __init__(self):
        self.turnId = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        latestCheckpoint = LatestCheckpoint()
        latestCheckpoint.Init(buf, pos)
        return cls.InitFromObj(latestCheckpoint)

    @classmethod
    def InitFromObj(cls, latestCheckpoint):
        x = LatestCheckpointT()
        x._UnPack(latestCheckpoint)
        return x

    # LatestCheckpointT
    def _UnPack(self, latestCheckpoint):
        if latestCheckpoint is None:
            return
        if not latestCheckpoint.TurnIdIsNone():
            if np is None:
                self.turnId = []
                for i in range(latestCheckpoint.TurnIdLength()):
                    self.turnId.append(latestCheckpoint.TurnId(i))
            else:
                self.turnId = latestCheckpoint.TurnIdAsNumpy()

    # LatestCheckpointT
    def Pack(self, builder):
        if self.turnId is not None:
            if np is not None and type(self.turnId) is np.ndarray:
                turnId = builder.CreateNumpyVector(self.turnId)
            else:
                LatestCheckpointStartTurnIdVector(builder, len(self.turnId))
                for i in reversed(range(len(self.turnId))):
                    builder.PrependUint8(self.turnId[i])
                turnId = builder.EndVector()
        LatestCheckpointStart(builder)
        if self.turnId is not None:
            LatestCheckpointAddTurnId(builder, turnId)
        latestCheckpoint = LatestCheckpointEnd(builder)
        return latestCheckpoint
