# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LatencyBucket(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LatencyBucket()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLatencyBucket(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LatencyBucketBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # LatencyBucket
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LatencyBucket
    def Operation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LatencyBucket
    def UpperBoundNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # LatencyBucket
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def LatencyBucketStart(builder): builder.StartObject(3)
def Start(builder):
    return LatencyBucketStart(builder)
def LatencyBucketAddOperation(builder, operation): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(operation), 0)
def AddOperation(builder, operation):
    return LatencyBucketAddOperation(builder, operation)
def LatencyBucketAddUpperBoundNs(builder, upperBoundNs): builder.PrependUint64Slot(1, upperBoundNs, 0)
def AddUpperBoundNs(builder, upperBoundNs):
    return LatencyBucketAddUpperBoundNs(builder, upperBoundNs)
def LatencyBucketAddCount(builder, count): builder.PrependUint64Slot(2, count, 0)
def AddCount(builder, count):
    return LatencyBucketAddCount(builder, count)
def LatencyBucketEnd(builder): return builder.EndObject()
def End(builder):
    return LatencyBucketEnd(builder)

class LatencyBucketT(object):

    # LatencyBucketT
    def __init__(self):
        self.operation = None  # type: str
        self.upperBoundNs = 0  # type: int
        self.count = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        latencyBucket = LatencyBucket()
        latencyBucket.Init(buf, pos)
        return cls.InitFromObj(latencyBucket)

    @classmethod
    def InitFromObj(cls, latencyBucket):
        x = LatencyBucketT()
        x._UnPack(latencyBucket)
        return x

    # LatencyBucketT
    def _UnPack(self, latencyBucket):
        if latencyBucket is None:
            return
        self.operation = latencyBucket.Operation()
        self.upperBoundNs = latencyBucket.UpperBoundNs()
        self.count = latencyBucket.Count()

    # LatencyBucketT
    def Pack(self, builder):
        if self.operation is not None:
            operation = builder.CreateString(self.operation)
        LatencyBucketStart(builder)
        if self.operation is not None:
            LatencyBucketAddOperation(builder, operation)
        LatencyBucketAddUpperBoundNs(builder, self.upperBoundNs)
        LatencyBucketAddCount(builder, self.count)
        latencyBucket = LatencyBucketEnd(builder)
        return latencyBucket
