# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LatencyHistograms(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LatencyHistograms()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLatencyHistograms(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LatencyHistogramsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # LatencyHistograms
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def LatencyHistogramsStart(builder): builder.StartObject(0)
def Start(builder):
    return LatencyHistogramsStart(builder)
def LatencyHistogramsEnd(builder): return builder.EndObject()
def End(builder):
    return LatencyHistogramsEnd(builder)

class LatencyHistogramsT(object):

    # LatencyHistogramsT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        latencyHistograms = LatencyHistograms()
        latencyHistograms.Init(buf, pos)
        return cls.InitFromObj(latencyHistograms)

    @classmethod
    def InitFromObj(cls, latencyHistograms):
        x = LatencyHistogramsT()
        x._UnPack(latencyHistograms)
        return x

    # LatencyHistogramsT
    def _UnPack(self, latencyHistograms):
        if latencyHistograms is None:
            return

    # LatencyHistogramsT
    def Pack(self, builder):
        LatencyHistogramsStart(builder)
        latencyHistograms = LatencyHistogramsEnd(builder)
        return latencyHistograms
