# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LatencyResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LatencyResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLatencyResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LatencyResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # LatencyResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LatencyResult
    def Buckets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from hypermind.protocol.LatencyBucket import LatencyBucket
            obj = LatencyBucket()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LatencyResult
    def BucketsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LatencyResult
    def BucketsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def LatencyResultStart(builder): builder.StartObject(1)
def Start(builder):
    return LatencyResultStart(builder)
def LatencyResultAddBuckets(builder, buckets): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(buckets), 0)
def AddBuckets(builder, buckets):
    return LatencyResultAddBuckets(builder, buckets)
def LatencyResultStartBucketsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBucketsVector(builder, numElems):
    return LatencyResultStartBucketsVector(builder, numElems)
def LatencyResultEnd(builder): return builder.EndObject()
def End(builder):
    return LatencyResultEnd(builder)
import hypermind.protocol.LatencyBucket
try:
    from typing import List
except:
    pass

class LatencyResultT(object):

    # LatencyResultT
    def __init__(self):
        self.buckets = None  # type: List[hypermind.protocol.LatencyBucket.LatencyBucketT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        latencyResult = LatencyResult()
        latencyResult.Init(buf, pos)
        return cls.InitFromObj(latencyResult)

    @classmethod
    def InitFromObj(cls, latencyResult):
        x = LatencyResultT()
        x._UnPack(latencyResult)
        return x

    # LatencyResultT
    def _UnPack(self, latencyResult):
        if latencyResult is None:
            return
        if not latencyResult.BucketsIsNone():
            self.buckets = []
            for i in range(latencyResult.BucketsLength()):
                if latencyResult.Buckets(i) is None:
                    self.buckets.append(None)
                else:
                    latencyBucket_ = hypermind.protocol.LatencyBucket.LatencyBucketT.InitFromObj(latencyResult.Buckets(i))
                    self.buckets.append(latencyBucket_)

    # LatencyResultT
    def Pack(self, builder):
        if self.buckets is not None:
            bucketslist = []
            for i in range(len(self.buckets)):
                bucketslist.append(self.buckets[i].Pack(builder))
            LatencyResultStartBucketsVector(builder, len(self.buckets))
            for i in reversed(range(len(self.buckets))):
                builder.PrependUOffsetTRelative(bucketslist[i])
            buckets = builder.EndVector()
        LatencyResultStart(builder)
        if self.buckets is not None:
            LatencyResultAddBuckets(builder, buckets)
        latencyResult = LatencyResultEnd(builder)
        return latencyResult
