# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProjectionStat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProjectionStat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProjectionStat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ProjectionStatBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # ProjectionStat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProjectionStat
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProjectionStat
    def AppliedLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ProjectionStatStart(builder): builder.StartObject(2)
def Start(builder):
    return ProjectionStatStart(builder)
def ProjectionStatAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def AddName(builder, name):
    return ProjectionStatAddName(builder, name)
def ProjectionStatAddAppliedLsn(builder, appliedLsn): builder.PrependUint64Slot(1, appliedLsn, 0)
def AddAppliedLsn(builder, appliedLsn):
    return ProjectionStatAddAppliedLsn(builder, appliedLsn)
def ProjectionStatEnd(builder): return builder.EndObject()
def End(builder):
    return ProjectionStatEnd(builder)

class ProjectionStatT(object):

    # ProjectionStatT
    def __init__(self):
        self.name = None  # type: str
        self.appliedLsn = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        projectionStat = ProjectionStat()
        projectionStat.Init(buf, pos)
        return cls.InitFromObj(projectionStat)

    @classmethod
    def InitFromObj(cls, projectionStat):
        x = ProjectionStatT()
        x._UnPack(projectionStat)
        return x

    # ProjectionStatT
    def _UnPack(self, projectionStat):
        if projectionStat is None:
            return
        self.name = projectionStat.Name()
        self.appliedLsn = projectionStat.AppliedLsn()

    # ProjectionStatT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        ProjectionStatStart(builder)
        if self.name is not None:
            ProjectionStatAddName(builder, name)
        ProjectionStatAddAppliedLsn(builder, self.appliedLsn)
        projectionStat = ProjectionStatEnd(builder)
        return projectionStat
