# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RebuildResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RebuildResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRebuildResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RebuildResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # RebuildResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RebuildResult
    def Actor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # RebuildResult
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RebuildResult
    def AppliedLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def RebuildResultStart(builder): builder.StartObject(3)
def Start(builder):
    return RebuildResultStart(builder)
def RebuildResultAddActor(builder, actor): builder.PrependUint16Slot(0, actor, 0)
def AddActor(builder, actor):
    return RebuildResultAddActor(builder, actor)
def RebuildResultAddName(builder, name): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def AddName(builder, name):
    return RebuildResultAddName(builder, name)
def RebuildResultAddAppliedLsn(builder, appliedLsn): builder.PrependUint64Slot(2, appliedLsn, 0)
def AddAppliedLsn(builder, appliedLsn):
    return RebuildResultAddAppliedLsn(builder, appliedLsn)
def RebuildResultEnd(builder): return builder.EndObject()
def End(builder):
    return RebuildResultEnd(builder)

class RebuildResultT(object):

    # RebuildResultT
    def __init__(self):
        self.actor = 0  # type: int
        self.name = None  # type: str
        self.appliedLsn = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        rebuildResult = RebuildResult()
        rebuildResult.Init(buf, pos)
        return cls.InitFromObj(rebuildResult)

    @classmethod
    def InitFromObj(cls, rebuildResult):
        x = RebuildResultT()
        x._UnPack(rebuildResult)
        return x

    # RebuildResultT
    def _UnPack(self, rebuildResult):
        if rebuildResult is None:
            return
        self.actor = rebuildResult.Actor()
        self.name = rebuildResult.Name()
        self.appliedLsn = rebuildResult.AppliedLsn()

    # RebuildResultT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        RebuildResultStart(builder)
        RebuildResultAddActor(builder, self.actor)
        if self.name is not None:
            RebuildResultAddName(builder, name)
        RebuildResultAddAppliedLsn(builder, self.appliedLsn)
        rebuildResult = RebuildResultEnd(builder)
        return rebuildResult
