# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RebuildProjection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RebuildProjection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRebuildProjection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RebuildProjectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # RebuildProjection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RebuildProjection
    def Actor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # RebuildProjection
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RebuildProjectionStart(builder): builder.StartObject(2)
def Start(builder):
    return RebuildProjectionStart(builder)
def RebuildProjectionAddActor(builder, actor): builder.PrependUint16Slot(0, actor, 0)
def AddActor(builder, actor):
    return RebuildProjectionAddActor(builder, actor)
def RebuildProjectionAddName(builder, name): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def AddName(builder, name):
    return RebuildProjectionAddName(builder, name)
def RebuildProjectionEnd(builder): return builder.EndObject()
def End(builder):
    return RebuildProjectionEnd(builder)

class RebuildProjectionT(object):

    # RebuildProjectionT
    def __init__(self):
        self.actor = 0  # type: int
        self.name = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        rebuildProjection = RebuildProjection()
        rebuildProjection.Init(buf, pos)
        return cls.InitFromObj(rebuildProjection)

    @classmethod
    def InitFromObj(cls, rebuildProjection):
        x = RebuildProjectionT()
        x._UnPack(rebuildProjection)
        return x

    # RebuildProjectionT
    def _UnPack(self, rebuildProjection):
        if rebuildProjection is None:
            return
        self.actor = rebuildProjection.Actor()
        self.name = rebuildProjection.Name()

    # RebuildProjectionT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        RebuildProjectionStart(builder)
        RebuildProjectionAddActor(builder, self.actor)
        if self.name is not None:
            RebuildProjectionAddName(builder, name)
        rebuildProjection = RebuildProjectionEnd(builder)
        return rebuildProjection
