# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RecallResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RecallResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRecallResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RecallResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # RecallResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RecallResult
    def Windows(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from hypermind.protocol.TemporalWindowRecord import TemporalWindowRecord
            obj = TemporalWindowRecord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RecallResult
    def WindowsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RecallResult
    def WindowsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # RecallResult
    def Members(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # RecallResult
    def MembersAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # RecallResult
    def MembersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RecallResult
    def MembersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def RecallResultStart(builder): builder.StartObject(2)
def Start(builder):
    return RecallResultStart(builder)
def RecallResultAddWindows(builder, windows): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(windows), 0)
def AddWindows(builder, windows):
    return RecallResultAddWindows(builder, windows)
def RecallResultStartWindowsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartWindowsVector(builder, numElems):
    return RecallResultStartWindowsVector(builder, numElems)
def RecallResultAddMembers(builder, members): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(members), 0)
def AddMembers(builder, members):
    return RecallResultAddMembers(builder, members)
def RecallResultStartMembersVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def StartMembersVector(builder, numElems):
    return RecallResultStartMembersVector(builder, numElems)
def RecallResultEnd(builder): return builder.EndObject()
def End(builder):
    return RecallResultEnd(builder)
import hypermind.protocol.TemporalWindowRecord
try:
    from typing import List
except:
    pass

class RecallResultT(object):

    # RecallResultT
    def __init__(self):
        self.windows = None  # type: List[hypermind.protocol.TemporalWindowRecord.TemporalWindowRecordT]
        self.members = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        recallResult = RecallResult()
        recallResult.Init(buf, pos)
        return cls.InitFromObj(recallResult)

    @classmethod
    def InitFromObj(cls, recallResult):
        x = RecallResultT()
        x._UnPack(recallResult)
        return x

    # RecallResultT
    def _UnPack(self, recallResult):
        if recallResult is None:
            return
        if not recallResult.WindowsIsNone():
            self.windows = []
            for i in range(recallResult.WindowsLength()):
                if recallResult.Windows(i) is None:
                    self.windows.append(None)
                else:
                    temporalWindowRecord_ = hypermind.protocol.TemporalWindowRecord.TemporalWindowRecordT.InitFromObj(recallResult.Windows(i))
                    self.windows.append(temporalWindowRecord_)
        if not recallResult.MembersIsNone():
            if np is None:
                self.members = []
                for i in range(recallResult.MembersLength()):
                    self.members.append(recallResult.Members(i))
            else:
                self.members = recallResult.MembersAsNumpy()

    # RecallResultT
    def Pack(self, builder):
        if self.windows is not None:
            windowslist = []
            for i in range(len(self.windows)):
                windowslist.append(self.windows[i].Pack(builder))
            RecallResultStartWindowsVector(builder, len(self.windows))
            for i in reversed(range(len(self.windows))):
                builder.PrependUOffsetTRelative(windowslist[i])
            windows = builder.EndVector()
        if self.members is not None:
            if np is not None and type(self.members) is np.ndarray:
                members = builder.CreateNumpyVector(self.members)
            else:
                RecallResultStartMembersVector(builder, len(self.members))
                for i in reversed(range(len(self.members))):
                    builder.PrependUint64(self.members[i])
                members = builder.EndVector()
        RecallResultStart(builder)
        if self.windows is not None:
            RecallResultAddWindows(builder, windows)
        if self.members is not None:
            RecallResultAddMembers(builder, members)
        recallResult = RecallResultEnd(builder)
        return recallResult
