# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Recall(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Recall()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRecall(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RecallBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # Recall
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Recall
    def Query(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Recall
    def QueryAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Recall
    def QueryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Recall
    def QueryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Recall
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Recall
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Recall
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Recall
    def StartNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Recall
    def EndNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def RecallStart(builder): builder.StartObject(6)
def Start(builder):
    return RecallStart(builder)
def RecallAddQuery(builder, query): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)
def AddQuery(builder, query):
    return RecallAddQuery(builder, query)
def RecallStartQueryVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartQueryVector(builder, numElems):
    return RecallStartQueryVector(builder, numElems)
def RecallAddLimit(builder, limit): builder.PrependUint32Slot(1, limit, 0)
def AddLimit(builder, limit):
    return RecallAddLimit(builder, limit)
def RecallAddMode(builder, mode): builder.PrependUint8Slot(2, mode, 0)
def AddMode(builder, mode):
    return RecallAddMode(builder, mode)
def RecallAddLevel(builder, level): builder.PrependUint8Slot(3, level, 0)
def AddLevel(builder, level):
    return RecallAddLevel(builder, level)
def RecallAddStartNs(builder, startNs): builder.PrependInt64Slot(4, startNs, 0)
def AddStartNs(builder, startNs):
    return RecallAddStartNs(builder, startNs)
def RecallAddEndNs(builder, endNs): builder.PrependInt64Slot(5, endNs, 0)
def AddEndNs(builder, endNs):
    return RecallAddEndNs(builder, endNs)
def RecallEnd(builder): return builder.EndObject()
def End(builder):
    return RecallEnd(builder)
try:
    from typing import List
except:
    pass

class RecallT(object):

    # RecallT
    def __init__(self):
        self.query = None  # type: List[int]
        self.limit = 0  # type: int
        self.mode = 0  # type: int
        self.level = 0  # type: int
        self.startNs = 0  # type: int
        self.endNs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        recall = Recall()
        recall.Init(buf, pos)
        return cls.InitFromObj(recall)

    @classmethod
    def InitFromObj(cls, recall):
        x = RecallT()
        x._UnPack(recall)
        return x

    # RecallT
    def _UnPack(self, recall):
        if recall is None:
            return
        if not recall.QueryIsNone():
            if np is None:
                self.query = []
                for i in range(recall.QueryLength()):
                    self.query.append(recall.Query(i))
            else:
                self.query = recall.QueryAsNumpy()
        self.limit = recall.Limit()
        self.mode = recall.Mode()
        self.level = recall.Level()
        self.startNs = recall.StartNs()
        self.endNs = recall.EndNs()

    # RecallT
    def Pack(self, builder):
        if self.query is not None:
            if np is not None and type(self.query) is np.ndarray:
                query = builder.CreateNumpyVector(self.query)
            else:
                RecallStartQueryVector(builder, len(self.query))
                for i in reversed(range(len(self.query))):
                    builder.PrependUint8(self.query[i])
                query = builder.EndVector()
        RecallStart(builder)
        if self.query is not None:
            RecallAddQuery(builder, query)
        RecallAddLimit(builder, self.limit)
        RecallAddMode(builder, self.mode)
        RecallAddLevel(builder, self.level)
        RecallAddStartNs(builder, self.startNs)
        RecallAddEndNs(builder, self.endNs)
        recall = RecallEnd(builder)
        return recall
