# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Request(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RequestBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # Request
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Request
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Request
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def RequestStart(builder): builder.StartObject(3)
def Start(builder):
    return RequestStart(builder)
def RequestAddRequestId(builder, requestId): builder.PrependUint64Slot(0, requestId, 0)
def AddRequestId(builder, requestId):
    return RequestAddRequestId(builder, requestId)
def RequestAddPayloadType(builder, payloadType): builder.PrependUint8Slot(1, payloadType, 0)
def AddPayloadType(builder, payloadType):
    return RequestAddPayloadType(builder, payloadType)
def RequestAddPayload(builder, payload): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)
def AddPayload(builder, payload):
    return RequestAddPayload(builder, payload)
def RequestEnd(builder): return builder.EndObject()
def End(builder):
    return RequestEnd(builder)
import hypermind.protocol.Activate
import hypermind.protocol.Append
import hypermind.protocol.AsOf
import hypermind.protocol.Attest
import hypermind.protocol.Checkpoint
import hypermind.protocol.CryptoDelete
import hypermind.protocol.Health
import hypermind.protocol.LatencyHistograms
import hypermind.protocol.LatestCheckpoint
import hypermind.protocol.RebuildProjection
import hypermind.protocol.Recall
import hypermind.protocol.RequestPayload
import hypermind.protocol.Stats
import hypermind.protocol.Subscribe
import hypermind.protocol.ToolRequest
import hypermind.protocol.Transcript
import hypermind.protocol.VerifyStatus
try:
    from typing import Union
except:
    pass

class RequestT(object):

    # RequestT
    def __init__(self):
        self.requestId = 0  # type: int
        self.payloadType = 0  # type: int
        self.payload = None  # type: Union[None, hypermind.protocol.Append.AppendT, hypermind.protocol.Activate.ActivateT, hypermind.protocol.Transcript.TranscriptT, hypermind.protocol.Recall.RecallT, hypermind.protocol.AsOf.AsOfT, hypermind.protocol.Checkpoint.CheckpointT, hypermind.protocol.LatestCheckpoint.LatestCheckpointT, hypermind.protocol.Attest.AttestT, hypermind.protocol.Subscribe.SubscribeT, hypermind.protocol.Health.HealthT, hypermind.protocol.Stats.StatsT, hypermind.protocol.LatencyHistograms.LatencyHistogramsT, hypermind.protocol.VerifyStatus.VerifyStatusT, hypermind.protocol.RebuildProjection.RebuildProjectionT, hypermind.protocol.CryptoDelete.CryptoDeleteT, hypermind.protocol.ToolRequest.ToolRequestT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        request = Request()
        request.Init(buf, pos)
        return cls.InitFromObj(request)

    @classmethod
    def InitFromObj(cls, request):
        x = RequestT()
        x._UnPack(request)
        return x

    # RequestT
    def _UnPack(self, request):
        if request is None:
            return
        self.requestId = request.RequestId()
        self.payloadType = request.PayloadType()
        self.payload = hypermind.protocol.RequestPayload.RequestPayloadCreator(self.payloadType, request.Payload())

    # RequestT
    def Pack(self, builder):
        if self.payload is not None:
            payload = self.payload.Pack(builder)
        RequestStart(builder)
        RequestAddRequestId(builder, self.requestId)
        RequestAddPayloadType(builder, self.payloadType)
        if self.payload is not None:
            RequestAddPayload(builder, payload)
        request = RequestEnd(builder)
        return request
