# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

class ResponsePayload(object):
    NONE = 0
    ErrorDetail = 1
    AppendAck = 2
    BytesResult = 3
    SubscriptionAck = 4
    HealthResult = 5
    StatsResult = 6
    LatencyResult = 7
    VerifyResult = 8
    RebuildResult = 9
    DeleteResult = 10
    TranscriptResult = 11
    RecallResult = 12
    BeliefResult = 13
    CheckpointAck = 14
    CheckpointResult = 15
    AttestAck = 16

def ResponsePayloadCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == ResponsePayload().ErrorDetail:
        import hypermind.protocol.ErrorDetail
        return hypermind.protocol.ErrorDetail.ErrorDetailT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().AppendAck:
        import hypermind.protocol.AppendAck
        return hypermind.protocol.AppendAck.AppendAckT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().BytesResult:
        import hypermind.protocol.BytesResult
        return hypermind.protocol.BytesResult.BytesResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().SubscriptionAck:
        import hypermind.protocol.SubscriptionAck
        return hypermind.protocol.SubscriptionAck.SubscriptionAckT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().HealthResult:
        import hypermind.protocol.HealthResult
        return hypermind.protocol.HealthResult.HealthResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().StatsResult:
        import hypermind.protocol.StatsResult
        return hypermind.protocol.StatsResult.StatsResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().LatencyResult:
        import hypermind.protocol.LatencyResult
        return hypermind.protocol.LatencyResult.LatencyResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().VerifyResult:
        import hypermind.protocol.VerifyResult
        return hypermind.protocol.VerifyResult.VerifyResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().RebuildResult:
        import hypermind.protocol.RebuildResult
        return hypermind.protocol.RebuildResult.RebuildResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().DeleteResult:
        import hypermind.protocol.DeleteResult
        return hypermind.protocol.DeleteResult.DeleteResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().TranscriptResult:
        import hypermind.protocol.TranscriptResult
        return hypermind.protocol.TranscriptResult.TranscriptResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().RecallResult:
        import hypermind.protocol.RecallResult
        return hypermind.protocol.RecallResult.RecallResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().BeliefResult:
        import hypermind.protocol.BeliefResult
        return hypermind.protocol.BeliefResult.BeliefResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().CheckpointAck:
        import hypermind.protocol.CheckpointAck
        return hypermind.protocol.CheckpointAck.CheckpointAckT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().CheckpointResult:
        import hypermind.protocol.CheckpointResult
        return hypermind.protocol.CheckpointResult.CheckpointResultT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ResponsePayload().AttestAck:
        import hypermind.protocol.AttestAck
        return hypermind.protocol.AttestAck.AttestAckT.InitFromBuf(table.Bytes, table.Pos)
    return None
