# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StatsResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatsResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatsResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StatsResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # StatsResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StatsResult
    def Actor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # StatsResult
    def LogEvents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StatsResult
    def LogBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StatsResult
    def ProjectionStats(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from hypermind.protocol.ProjectionStat import ProjectionStat
            obj = ProjectionStat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StatsResult
    def ProjectionStatsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StatsResult
    def ProjectionStatsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def StatsResultStart(builder): builder.StartObject(4)
def Start(builder):
    return StatsResultStart(builder)
def StatsResultAddActor(builder, actor): builder.PrependUint16Slot(0, actor, 0)
def AddActor(builder, actor):
    return StatsResultAddActor(builder, actor)
def StatsResultAddLogEvents(builder, logEvents): builder.PrependUint64Slot(1, logEvents, 0)
def AddLogEvents(builder, logEvents):
    return StatsResultAddLogEvents(builder, logEvents)
def StatsResultAddLogBytes(builder, logBytes): builder.PrependUint64Slot(2, logBytes, 0)
def AddLogBytes(builder, logBytes):
    return StatsResultAddLogBytes(builder, logBytes)
def StatsResultAddProjectionStats(builder, projectionStats): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(projectionStats), 0)
def AddProjectionStats(builder, projectionStats):
    return StatsResultAddProjectionStats(builder, projectionStats)
def StatsResultStartProjectionStatsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartProjectionStatsVector(builder, numElems):
    return StatsResultStartProjectionStatsVector(builder, numElems)
def StatsResultEnd(builder): return builder.EndObject()
def End(builder):
    return StatsResultEnd(builder)
import hypermind.protocol.ProjectionStat
try:
    from typing import List
except:
    pass

class StatsResultT(object):

    # StatsResultT
    def __init__(self):
        self.actor = 0  # type: int
        self.logEvents = 0  # type: int
        self.logBytes = 0  # type: int
        self.projectionStats = None  # type: List[hypermind.protocol.ProjectionStat.ProjectionStatT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        statsResult = StatsResult()
        statsResult.Init(buf, pos)
        return cls.InitFromObj(statsResult)

    @classmethod
    def InitFromObj(cls, statsResult):
        x = StatsResultT()
        x._UnPack(statsResult)
        return x

    # StatsResultT
    def _UnPack(self, statsResult):
        if statsResult is None:
            return
        self.actor = statsResult.Actor()
        self.logEvents = statsResult.LogEvents()
        self.logBytes = statsResult.LogBytes()
        if not statsResult.ProjectionStatsIsNone():
            self.projectionStats = []
            for i in range(statsResult.ProjectionStatsLength()):
                if statsResult.ProjectionStats(i) is None:
                    self.projectionStats.append(None)
                else:
                    projectionStat_ = hypermind.protocol.ProjectionStat.ProjectionStatT.InitFromObj(statsResult.ProjectionStats(i))
                    self.projectionStats.append(projectionStat_)

    # StatsResultT
    def Pack(self, builder):
        if self.projectionStats is not None:
            projectionStatslist = []
            for i in range(len(self.projectionStats)):
                projectionStatslist.append(self.projectionStats[i].Pack(builder))
            StatsResultStartProjectionStatsVector(builder, len(self.projectionStats))
            for i in reversed(range(len(self.projectionStats))):
                builder.PrependUOffsetTRelative(projectionStatslist[i])
            projectionStats = builder.EndVector()
        StatsResultStart(builder)
        StatsResultAddActor(builder, self.actor)
        StatsResultAddLogEvents(builder, self.logEvents)
        StatsResultAddLogBytes(builder, self.logBytes)
        if self.projectionStats is not None:
            StatsResultAddProjectionStats(builder, projectionStats)
        statsResult = StatsResultEnd(builder)
        return statsResult
