# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Streams committed events after an optional conversation and LSN cursor.
class Subscribe(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Subscribe()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubscribe(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SubscribeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # Subscribe
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Subscribe
    def Conversation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Subscribe
    def ConversationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Subscribe
    def ConversationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Subscribe
    def ConversationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Subscribe
    def SinceLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def SubscribeStart(builder): builder.StartObject(2)
def Start(builder):
    return SubscribeStart(builder)
def SubscribeAddConversation(builder, conversation): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(conversation), 0)
def AddConversation(builder, conversation):
    return SubscribeAddConversation(builder, conversation)
def SubscribeStartConversationVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartConversationVector(builder, numElems):
    return SubscribeStartConversationVector(builder, numElems)
def SubscribeAddSinceLsn(builder, sinceLsn): builder.PrependUint64Slot(1, sinceLsn, 0)
def AddSinceLsn(builder, sinceLsn):
    return SubscribeAddSinceLsn(builder, sinceLsn)
def SubscribeEnd(builder): return builder.EndObject()
def End(builder):
    return SubscribeEnd(builder)
try:
    from typing import List
except:
    pass

class SubscribeT(object):

    # SubscribeT
    def __init__(self):
        self.conversation = None  # type: List[int]
        self.sinceLsn = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        subscribe = Subscribe()
        subscribe.Init(buf, pos)
        return cls.InitFromObj(subscribe)

    @classmethod
    def InitFromObj(cls, subscribe):
        x = SubscribeT()
        x._UnPack(subscribe)
        return x

    # SubscribeT
    def _UnPack(self, subscribe):
        if subscribe is None:
            return
        if not subscribe.ConversationIsNone():
            if np is None:
                self.conversation = []
                for i in range(subscribe.ConversationLength()):
                    self.conversation.append(subscribe.Conversation(i))
            else:
                self.conversation = subscribe.ConversationAsNumpy()
        self.sinceLsn = subscribe.SinceLsn()

    # SubscribeT
    def Pack(self, builder):
        if self.conversation is not None:
            if np is not None and type(self.conversation) is np.ndarray:
                conversation = builder.CreateNumpyVector(self.conversation)
            else:
                SubscribeStartConversationVector(builder, len(self.conversation))
                for i in reversed(range(len(self.conversation))):
                    builder.PrependUint8(self.conversation[i])
                conversation = builder.EndVector()
        SubscribeStart(builder)
        if self.conversation is not None:
            SubscribeAddConversation(builder, conversation)
        SubscribeAddSinceLsn(builder, self.sinceLsn)
        subscribe = SubscribeEnd(builder)
        return subscribe
