# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TemporalWindowRecord(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TemporalWindowRecord()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTemporalWindowRecord(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TemporalWindowRecordBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # TemporalWindowRecord
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TemporalWindowRecord
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TemporalWindowRecord
    def StartNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TemporalWindowRecord
    def EndNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TemporalWindowRecord
    def MemberCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def TemporalWindowRecordStart(builder): builder.StartObject(4)
def Start(builder):
    return TemporalWindowRecordStart(builder)
def TemporalWindowRecordAddLevel(builder, level): builder.PrependUint8Slot(0, level, 0)
def AddLevel(builder, level):
    return TemporalWindowRecordAddLevel(builder, level)
def TemporalWindowRecordAddStartNs(builder, startNs): builder.PrependInt64Slot(1, startNs, 0)
def AddStartNs(builder, startNs):
    return TemporalWindowRecordAddStartNs(builder, startNs)
def TemporalWindowRecordAddEndNs(builder, endNs): builder.PrependInt64Slot(2, endNs, 0)
def AddEndNs(builder, endNs):
    return TemporalWindowRecordAddEndNs(builder, endNs)
def TemporalWindowRecordAddMemberCount(builder, memberCount): builder.PrependUint64Slot(3, memberCount, 0)
def AddMemberCount(builder, memberCount):
    return TemporalWindowRecordAddMemberCount(builder, memberCount)
def TemporalWindowRecordEnd(builder): return builder.EndObject()
def End(builder):
    return TemporalWindowRecordEnd(builder)

class TemporalWindowRecordT(object):

    # TemporalWindowRecordT
    def __init__(self):
        self.level = 0  # type: int
        self.startNs = 0  # type: int
        self.endNs = 0  # type: int
        self.memberCount = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        temporalWindowRecord = TemporalWindowRecord()
        temporalWindowRecord.Init(buf, pos)
        return cls.InitFromObj(temporalWindowRecord)

    @classmethod
    def InitFromObj(cls, temporalWindowRecord):
        x = TemporalWindowRecordT()
        x._UnPack(temporalWindowRecord)
        return x

    # TemporalWindowRecordT
    def _UnPack(self, temporalWindowRecord):
        if temporalWindowRecord is None:
            return
        self.level = temporalWindowRecord.Level()
        self.startNs = temporalWindowRecord.StartNs()
        self.endNs = temporalWindowRecord.EndNs()
        self.memberCount = temporalWindowRecord.MemberCount()

    # TemporalWindowRecordT
    def Pack(self, builder):
        TemporalWindowRecordStart(builder)
        TemporalWindowRecordAddLevel(builder, self.level)
        TemporalWindowRecordAddStartNs(builder, self.startNs)
        TemporalWindowRecordAddEndNs(builder, self.endNs)
        TemporalWindowRecordAddMemberCount(builder, self.memberCount)
        temporalWindowRecord = TemporalWindowRecordEnd(builder)
        return temporalWindowRecord
