# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ToolRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ToolRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsToolRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ToolRequestBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # ToolRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ToolRequest
    def Verb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolRequest
    def ArgumentsJson(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ToolRequest
    def ArgumentsJsonAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ToolRequest
    def ArgumentsJsonLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ToolRequest
    def ArgumentsJsonIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ToolRequestStart(builder): builder.StartObject(2)
def Start(builder):
    return ToolRequestStart(builder)
def ToolRequestAddVerb(builder, verb): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(verb), 0)
def AddVerb(builder, verb):
    return ToolRequestAddVerb(builder, verb)
def ToolRequestAddArgumentsJson(builder, argumentsJson): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(argumentsJson), 0)
def AddArgumentsJson(builder, argumentsJson):
    return ToolRequestAddArgumentsJson(builder, argumentsJson)
def ToolRequestStartArgumentsJsonVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartArgumentsJsonVector(builder, numElems):
    return ToolRequestStartArgumentsJsonVector(builder, numElems)
def ToolRequestEnd(builder): return builder.EndObject()
def End(builder):
    return ToolRequestEnd(builder)
try:
    from typing import List
except:
    pass

class ToolRequestT(object):

    # ToolRequestT
    def __init__(self):
        self.verb = None  # type: str
        self.argumentsJson = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        toolRequest = ToolRequest()
        toolRequest.Init(buf, pos)
        return cls.InitFromObj(toolRequest)

    @classmethod
    def InitFromObj(cls, toolRequest):
        x = ToolRequestT()
        x._UnPack(toolRequest)
        return x

    # ToolRequestT
    def _UnPack(self, toolRequest):
        if toolRequest is None:
            return
        self.verb = toolRequest.Verb()
        if not toolRequest.ArgumentsJsonIsNone():
            if np is None:
                self.argumentsJson = []
                for i in range(toolRequest.ArgumentsJsonLength()):
                    self.argumentsJson.append(toolRequest.ArgumentsJson(i))
            else:
                self.argumentsJson = toolRequest.ArgumentsJsonAsNumpy()

    # ToolRequestT
    def Pack(self, builder):
        if self.verb is not None:
            verb = builder.CreateString(self.verb)
        if self.argumentsJson is not None:
            if np is not None and type(self.argumentsJson) is np.ndarray:
                argumentsJson = builder.CreateNumpyVector(self.argumentsJson)
            else:
                ToolRequestStartArgumentsJsonVector(builder, len(self.argumentsJson))
                for i in reversed(range(len(self.argumentsJson))):
                    builder.PrependUint8(self.argumentsJson[i])
                argumentsJson = builder.EndVector()
        ToolRequestStart(builder)
        if self.verb is not None:
            ToolRequestAddVerb(builder, verb)
        if self.argumentsJson is not None:
            ToolRequestAddArgumentsJson(builder, argumentsJson)
        toolRequest = ToolRequestEnd(builder)
        return toolRequest
