# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Transcript(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Transcript()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTranscript(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TranscriptBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # Transcript
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Transcript
    def Conversation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Transcript
    def ConversationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Transcript
    def ConversationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Transcript
    def ConversationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Transcript
    def SinceLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Transcript
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def TranscriptStart(builder): builder.StartObject(3)
def Start(builder):
    return TranscriptStart(builder)
def TranscriptAddConversation(builder, conversation): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(conversation), 0)
def AddConversation(builder, conversation):
    return TranscriptAddConversation(builder, conversation)
def TranscriptStartConversationVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartConversationVector(builder, numElems):
    return TranscriptStartConversationVector(builder, numElems)
def TranscriptAddSinceLsn(builder, sinceLsn): builder.PrependUint64Slot(1, sinceLsn, 0)
def AddSinceLsn(builder, sinceLsn):
    return TranscriptAddSinceLsn(builder, sinceLsn)
def TranscriptAddLimit(builder, limit): builder.PrependUint32Slot(2, limit, 0)
def AddLimit(builder, limit):
    return TranscriptAddLimit(builder, limit)
def TranscriptEnd(builder): return builder.EndObject()
def End(builder):
    return TranscriptEnd(builder)
try:
    from typing import List
except:
    pass

class TranscriptT(object):

    # TranscriptT
    def __init__(self):
        self.conversation = None  # type: List[int]
        self.sinceLsn = 0  # type: int
        self.limit = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        transcript = Transcript()
        transcript.Init(buf, pos)
        return cls.InitFromObj(transcript)

    @classmethod
    def InitFromObj(cls, transcript):
        x = TranscriptT()
        x._UnPack(transcript)
        return x

    # TranscriptT
    def _UnPack(self, transcript):
        if transcript is None:
            return
        if not transcript.ConversationIsNone():
            if np is None:
                self.conversation = []
                for i in range(transcript.ConversationLength()):
                    self.conversation.append(transcript.Conversation(i))
            else:
                self.conversation = transcript.ConversationAsNumpy()
        self.sinceLsn = transcript.SinceLsn()
        self.limit = transcript.Limit()

    # TranscriptT
    def Pack(self, builder):
        if self.conversation is not None:
            if np is not None and type(self.conversation) is np.ndarray:
                conversation = builder.CreateNumpyVector(self.conversation)
            else:
                TranscriptStartConversationVector(builder, len(self.conversation))
                for i in reversed(range(len(self.conversation))):
                    builder.PrependUint8(self.conversation[i])
                conversation = builder.EndVector()
        TranscriptStart(builder)
        if self.conversation is not None:
            TranscriptAddConversation(builder, conversation)
        TranscriptAddSinceLsn(builder, self.sinceLsn)
        TranscriptAddLimit(builder, self.limit)
        transcript = TranscriptEnd(builder)
        return transcript
