# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VerifyResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VerifyResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVerifyResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def VerifyResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x43\x50\x52", size_prefixed=size_prefixed)

    # VerifyResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VerifyResult
    def Actor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # VerifyResult
    def Root(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # VerifyResult
    def RootAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # VerifyResult
    def RootLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VerifyResult
    def RootIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # VerifyResult
    def LeafCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # VerifyResult
    def LastCheckpointLsn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # VerifyResult
    def Verified(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VerifyResultStart(builder): builder.StartObject(5)
def Start(builder):
    return VerifyResultStart(builder)
def VerifyResultAddActor(builder, actor): builder.PrependUint16Slot(0, actor, 0)
def AddActor(builder, actor):
    return VerifyResultAddActor(builder, actor)
def VerifyResultAddRoot(builder, root): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(root), 0)
def AddRoot(builder, root):
    return VerifyResultAddRoot(builder, root)
def VerifyResultStartRootVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartRootVector(builder, numElems):
    return VerifyResultStartRootVector(builder, numElems)
def VerifyResultAddLeafCount(builder, leafCount): builder.PrependUint64Slot(2, leafCount, 0)
def AddLeafCount(builder, leafCount):
    return VerifyResultAddLeafCount(builder, leafCount)
def VerifyResultAddLastCheckpointLsn(builder, lastCheckpointLsn): builder.PrependUint64Slot(3, lastCheckpointLsn, 0)
def AddLastCheckpointLsn(builder, lastCheckpointLsn):
    return VerifyResultAddLastCheckpointLsn(builder, lastCheckpointLsn)
def VerifyResultAddVerified(builder, verified): builder.PrependBoolSlot(4, verified, 0)
def AddVerified(builder, verified):
    return VerifyResultAddVerified(builder, verified)
def VerifyResultEnd(builder): return builder.EndObject()
def End(builder):
    return VerifyResultEnd(builder)
try:
    from typing import List
except:
    pass

class VerifyResultT(object):

    # VerifyResultT
    def __init__(self):
        self.actor = 0  # type: int
        self.root = None  # type: List[int]
        self.leafCount = 0  # type: int
        self.lastCheckpointLsn = 0  # type: int
        self.verified = False  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        verifyResult = VerifyResult()
        verifyResult.Init(buf, pos)
        return cls.InitFromObj(verifyResult)

    @classmethod
    def InitFromObj(cls, verifyResult):
        x = VerifyResultT()
        x._UnPack(verifyResult)
        return x

    # VerifyResultT
    def _UnPack(self, verifyResult):
        if verifyResult is None:
            return
        self.actor = verifyResult.Actor()
        if not verifyResult.RootIsNone():
            if np is None:
                self.root = []
                for i in range(verifyResult.RootLength()):
                    self.root.append(verifyResult.Root(i))
            else:
                self.root = verifyResult.RootAsNumpy()
        self.leafCount = verifyResult.LeafCount()
        self.lastCheckpointLsn = verifyResult.LastCheckpointLsn()
        self.verified = verifyResult.Verified()

    # VerifyResultT
    def Pack(self, builder):
        if self.root is not None:
            if np is not None and type(self.root) is np.ndarray:
                root = builder.CreateNumpyVector(self.root)
            else:
                VerifyResultStartRootVector(builder, len(self.root))
                for i in reversed(range(len(self.root))):
                    builder.PrependUint8(self.root[i])
                root = builder.EndVector()
        VerifyResultStart(builder)
        VerifyResultAddActor(builder, self.actor)
        if self.root is not None:
            VerifyResultAddRoot(builder, root)
        VerifyResultAddLeafCount(builder, self.leafCount)
        VerifyResultAddLastCheckpointLsn(builder, self.lastCheckpointLsn)
        VerifyResultAddVerified(builder, self.verified)
        verifyResult = VerifyResultEnd(builder)
        return verifyResult
