[package]
name = "hm-docs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake3 = "1.8.2"
hm-core = { path = "../hm-core" }
lopdf = { version = "0.45.0", default-features = false }
mail-parser = { version = "0.11.9", default-features = false }

[lints]
workspace = true
