// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ApprovalDecision } from '../../hypermind/schema/approval-decision';


export class Approval {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Approval {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsApproval(bb:flatbuffers.ByteBuffer, obj?:Approval):Approval {
  return (obj || new Approval()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsApproval(bb:flatbuffers.ByteBuffer, obj?:Approval):Approval {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Approval()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

effectId(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

effectIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

effectIdArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

decision():ApprovalDecision {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ApprovalDecision.approved;
}

static startApproval(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEffectId(builder:flatbuffers.Builder, effectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, effectIdOffset, 0);
}

static createEffectIdVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startEffectIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addDecision(builder:flatbuffers.Builder, decision:ApprovalDecision) {
  builder.addFieldInt8(1, decision, ApprovalDecision.approved);
}

static endApproval(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // effect_id
  return offset;
}

static createApproval(builder:flatbuffers.Builder, effectIdOffset:flatbuffers.Offset, decision:ApprovalDecision):flatbuffers.Offset {
  Approval.startApproval(builder);
  Approval.addEffectId(builder, effectIdOffset);
  Approval.addDecision(builder, decision);
  return Approval.endApproval(builder);
}

unpack(): ApprovalT {
  return new ApprovalT(
    this.bb!.createScalarList(this.effectId.bind(this), this.effectIdLength()),
    this.decision()
  );
}


unpackTo(_o: ApprovalT): void {
  _o.effectId = this.bb!.createScalarList(this.effectId.bind(this), this.effectIdLength());
  _o.decision = this.decision();
}
}

export class ApprovalT {
constructor(
  public effectId: (number)[] = [],
  public decision: ApprovalDecision = ApprovalDecision.approved
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const effectId = Approval.createEffectIdVector(builder, this.effectId);

  return Approval.createApproval(builder,
    effectId,
    this.decision
  );
}
}
