// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { AttestationDisposition } from '../../hypermind/schema/attestation-disposition';


export class Attestation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Attestation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAttestation(bb:flatbuffers.ByteBuffer, obj?:Attestation):Attestation {
  return (obj || new Attestation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAttestation(bb:flatbuffers.ByteBuffer, obj?:Attestation):Attestation {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Attestation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

targetLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

disposition():AttestationDisposition {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AttestationDisposition.used;
}

static startAttestation(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTargetLsn(builder:flatbuffers.Builder, targetLsn:bigint) {
  builder.addFieldInt64(0, targetLsn, BigInt('0'));
}

static addDisposition(builder:flatbuffers.Builder, disposition:AttestationDisposition) {
  builder.addFieldInt8(1, disposition, AttestationDisposition.used);
}

static endAttestation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAttestation(builder:flatbuffers.Builder, targetLsn:bigint, disposition:AttestationDisposition):flatbuffers.Offset {
  Attestation.startAttestation(builder);
  Attestation.addTargetLsn(builder, targetLsn);
  Attestation.addDisposition(builder, disposition);
  return Attestation.endAttestation(builder);
}

unpack(): AttestationT {
  return new AttestationT(
    this.targetLsn(),
    this.disposition()
  );
}


unpackTo(_o: AttestationT): void {
  _o.targetLsn = this.targetLsn();
  _o.disposition = this.disposition();
}
}

export class AttestationT {
constructor(
  public targetLsn: bigint = BigInt('0'),
  public disposition: AttestationDisposition = AttestationDisposition.used
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Attestation.createAttestation(builder,
    this.targetLsn,
    this.disposition
  );
}
}
