// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Binding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Binding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBinding(bb:flatbuffers.ByteBuffer, obj?:Binding):Binding {
  return (obj || new Binding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBinding(bb:flatbuffers.ByteBuffer, obj?:Binding):Binding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Binding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

task(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

taskLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

taskArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

scope(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

scopeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

scopeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

canonicalEntity():string|null
canonicalEntity(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
canonicalEntity(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

property():string|null
property(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
property(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

evidenceLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

revision(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

revisionLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

revisionArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

freshnessRequirementNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startBinding(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addTask(builder:flatbuffers.Builder, taskOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, taskOffset, 0);
}

static createTaskVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startTaskVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addScope(builder:flatbuffers.Builder, scopeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, scopeOffset, 0);
}

static createScopeVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startScopeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addCanonicalEntity(builder:flatbuffers.Builder, canonicalEntityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, canonicalEntityOffset, 0);
}

static addProperty(builder:flatbuffers.Builder, propertyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, propertyOffset, 0);
}

static addEvidenceLsn(builder:flatbuffers.Builder, evidenceLsn:bigint) {
  builder.addFieldInt64(4, evidenceLsn, BigInt('0'));
}

static addRevision(builder:flatbuffers.Builder, revisionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, revisionOffset, 0);
}

static createRevisionVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startRevisionVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addFreshnessRequirementNs(builder:flatbuffers.Builder, freshnessRequirementNs:bigint) {
  builder.addFieldInt64(6, freshnessRequirementNs, BigInt('0'));
}

static endBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 8) // canonical_entity
  builder.requiredField(offset, 10) // property
  builder.requiredField(offset, 14) // revision
  return offset;
}

static createBinding(builder:flatbuffers.Builder, taskOffset:flatbuffers.Offset, scopeOffset:flatbuffers.Offset, canonicalEntityOffset:flatbuffers.Offset, propertyOffset:flatbuffers.Offset, evidenceLsn:bigint, revisionOffset:flatbuffers.Offset, freshnessRequirementNs:bigint):flatbuffers.Offset {
  Binding.startBinding(builder);
  Binding.addTask(builder, taskOffset);
  Binding.addScope(builder, scopeOffset);
  Binding.addCanonicalEntity(builder, canonicalEntityOffset);
  Binding.addProperty(builder, propertyOffset);
  Binding.addEvidenceLsn(builder, evidenceLsn);
  Binding.addRevision(builder, revisionOffset);
  Binding.addFreshnessRequirementNs(builder, freshnessRequirementNs);
  return Binding.endBinding(builder);
}

unpack(): BindingT {
  return new BindingT(
    this.bb!.createScalarList(this.task.bind(this), this.taskLength()),
    this.bb!.createScalarList(this.scope.bind(this), this.scopeLength()),
    this.canonicalEntity(),
    this.property(),
    this.evidenceLsn(),
    this.bb!.createScalarList(this.revision.bind(this), this.revisionLength()),
    this.freshnessRequirementNs()
  );
}


unpackTo(_o: BindingT): void {
  _o.task = this.bb!.createScalarList(this.task.bind(this), this.taskLength());
  _o.scope = this.bb!.createScalarList(this.scope.bind(this), this.scopeLength());
  _o.canonicalEntity = this.canonicalEntity();
  _o.property = this.property();
  _o.evidenceLsn = this.evidenceLsn();
  _o.revision = this.bb!.createScalarList(this.revision.bind(this), this.revisionLength());
  _o.freshnessRequirementNs = this.freshnessRequirementNs();
}
}

export class BindingT {
constructor(
  public task: (number)[] = [],
  public scope: (number)[] = [],
  public canonicalEntity: string|Uint8Array|null = null,
  public property: string|Uint8Array|null = null,
  public evidenceLsn: bigint = BigInt('0'),
  public revision: (number)[] = [],
  public freshnessRequirementNs: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const task = Binding.createTaskVector(builder, this.task);
  const scope = Binding.createScopeVector(builder, this.scope);
  const canonicalEntity = (this.canonicalEntity !== null ? builder.createString(this.canonicalEntity!) : 0);
  const property = (this.property !== null ? builder.createString(this.property!) : 0);
  const revision = Binding.createRevisionVector(builder, this.revision);

  return Binding.createBinding(builder,
    task,
    scope,
    canonicalEntity,
    property,
    this.evidenceLsn,
    revision,
    this.freshnessRequirementNs
  );
}
}
