// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Checkpoint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Checkpoint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCheckpoint(bb:flatbuffers.ByteBuffer, obj?:Checkpoint):Checkpoint {
  return (obj || new Checkpoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCheckpoint(bb:flatbuffers.ByteBuffer, obj?:Checkpoint):Checkpoint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Checkpoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cursor(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

cursorLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

cursorArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startCheckpoint(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCursor(builder:flatbuffers.Builder, cursorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cursorOffset, 0);
}

static createCursorVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startCursorVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endCheckpoint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // cursor
  return offset;
}

static createCheckpoint(builder:flatbuffers.Builder, cursorOffset:flatbuffers.Offset):flatbuffers.Offset {
  Checkpoint.startCheckpoint(builder);
  Checkpoint.addCursor(builder, cursorOffset);
  return Checkpoint.endCheckpoint(builder);
}

unpack(): CheckpointT {
  return new CheckpointT(
    this.bb!.createScalarList(this.cursor.bind(this), this.cursorLength())
  );
}


unpackTo(_o: CheckpointT): void {
  _o.cursor = this.bb!.createScalarList(this.cursor.bind(this), this.cursorLength());
}
}

export class CheckpointT {
constructor(
  public cursor: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const cursor = Checkpoint.createCursorVector(builder, this.cursor);

  return Checkpoint.createCheckpoint(builder,
    cursor
  );
}
}
