// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { EffectState } from '../../hypermind/schema/effect-state';


export class Effect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Effect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEffect(bb:flatbuffers.ByteBuffer, obj?:Effect):Effect {
  return (obj || new Effect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEffect(bb:flatbuffers.ByteBuffer, obj?:Effect):Effect {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Effect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

effectId(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

effectIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

effectIdArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

toolCallLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

state():EffectState {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : EffectState.dispatched;
}

static startEffect(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addEffectId(builder:flatbuffers.Builder, effectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, effectIdOffset, 0);
}

static createEffectIdVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startEffectIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addToolCallLsn(builder:flatbuffers.Builder, toolCallLsn:bigint) {
  builder.addFieldInt64(1, toolCallLsn, BigInt('0'));
}

static addState(builder:flatbuffers.Builder, state:EffectState) {
  builder.addFieldInt8(2, state, EffectState.dispatched);
}

static endEffect(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // effect_id
  return offset;
}

static createEffect(builder:flatbuffers.Builder, effectIdOffset:flatbuffers.Offset, toolCallLsn:bigint, state:EffectState):flatbuffers.Offset {
  Effect.startEffect(builder);
  Effect.addEffectId(builder, effectIdOffset);
  Effect.addToolCallLsn(builder, toolCallLsn);
  Effect.addState(builder, state);
  return Effect.endEffect(builder);
}

unpack(): EffectT {
  return new EffectT(
    this.bb!.createScalarList(this.effectId.bind(this), this.effectIdLength()),
    this.toolCallLsn(),
    this.state()
  );
}


unpackTo(_o: EffectT): void {
  _o.effectId = this.bb!.createScalarList(this.effectId.bind(this), this.effectIdLength());
  _o.toolCallLsn = this.toolCallLsn();
  _o.state = this.state();
}
}

export class EffectT {
constructor(
  public effectId: (number)[] = [],
  public toolCallLsn: bigint = BigInt('0'),
  public state: EffectState = EffectState.dispatched
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const effectId = Effect.createEffectIdVector(builder, this.effectId);

  return Effect.createEffect(builder,
    effectId,
    this.toolCallLsn,
    this.state
  );
}
}
