// automatically generated by the FlatBuffers compiler, do not modify

import { Approval, ApprovalT } from '../../hypermind/schema/approval';
import { Assertion, AssertionT } from '../../hypermind/schema/assertion';
import { Attestation, AttestationT } from '../../hypermind/schema/attestation';
import { Binding, BindingT } from '../../hypermind/schema/binding';
import { Checkpoint, CheckpointT } from '../../hypermind/schema/checkpoint';
import { Consolidation, ConsolidationT } from '../../hypermind/schema/consolidation';
import { DeliveredMsg, DeliveredMsgT } from '../../hypermind/schema/delivered-msg';
import { Effect, EffectT } from '../../hypermind/schema/effect';
import { Embedding, EmbeddingT } from '../../hypermind/schema/embedding';
import { IntentSet, IntentSetT } from '../../hypermind/schema/intent-set';
import { LoopClosed, LoopClosedT } from '../../hypermind/schema/loop-closed';
import { LoopOpened, LoopOpenedT } from '../../hypermind/schema/loop-opened';
import { MediaRef, MediaRefT } from '../../hypermind/schema/media-ref';
import { Outcome, OutcomeT } from '../../hypermind/schema/outcome';
import { ProviderFrame, ProviderFrameT } from '../../hypermind/schema/provider-frame';
import { Reasoning, ReasoningT } from '../../hypermind/schema/reasoning';
import { Recovery, RecoveryT } from '../../hypermind/schema/recovery';
import { Retract, RetractT } from '../../hypermind/schema/retract';
import { Supervisor, SupervisorT } from '../../hypermind/schema/supervisor';
import { ToolCall, ToolCallT } from '../../hypermind/schema/tool-call';
import { ToolResult, ToolResultT } from '../../hypermind/schema/tool-result';
import { UserMsg, UserMsgT } from '../../hypermind/schema/user-msg';


export enum EventPayload {
  NONE = 0,
  UserMsg = 1,
  DeliveredMsg = 2,
  ToolCall = 3,
  ToolResult = 4,
  Reasoning = 5,
  ProviderFrame = 6,
  MediaRef = 7,
  Effect = 8,
  Approval = 9,
  Outcome = 10,
  Checkpoint = 11,
  Supervisor = 12,
  Recovery = 13,
  IntentSet = 14,
  LoopOpened = 15,
  LoopClosed = 16,
  Assertion = 17,
  Consolidation = 18,
  Embedding = 19,
  Retract = 20,
  Attestation = 21,
  Binding = 22
}

export function unionToEventPayload(
  type: EventPayload,
  accessor: (obj:Approval|Assertion|Attestation|Binding|Checkpoint|Consolidation|DeliveredMsg|Effect|Embedding|IntentSet|LoopClosed|LoopOpened|MediaRef|Outcome|ProviderFrame|Reasoning|Recovery|Retract|Supervisor|ToolCall|ToolResult|UserMsg) => Approval|Assertion|Attestation|Binding|Checkpoint|Consolidation|DeliveredMsg|Effect|Embedding|IntentSet|LoopClosed|LoopOpened|MediaRef|Outcome|ProviderFrame|Reasoning|Recovery|Retract|Supervisor|ToolCall|ToolResult|UserMsg|null
): Approval|Assertion|Attestation|Binding|Checkpoint|Consolidation|DeliveredMsg|Effect|Embedding|IntentSet|LoopClosed|LoopOpened|MediaRef|Outcome|ProviderFrame|Reasoning|Recovery|Retract|Supervisor|ToolCall|ToolResult|UserMsg|null {
  switch(EventPayload[type]) {
    case 'NONE': return null; 
    case 'UserMsg': return accessor(new UserMsg())! as UserMsg;
    case 'DeliveredMsg': return accessor(new DeliveredMsg())! as DeliveredMsg;
    case 'ToolCall': return accessor(new ToolCall())! as ToolCall;
    case 'ToolResult': return accessor(new ToolResult())! as ToolResult;
    case 'Reasoning': return accessor(new Reasoning())! as Reasoning;
    case 'ProviderFrame': return accessor(new ProviderFrame())! as ProviderFrame;
    case 'MediaRef': return accessor(new MediaRef())! as MediaRef;
    case 'Effect': return accessor(new Effect())! as Effect;
    case 'Approval': return accessor(new Approval())! as Approval;
    case 'Outcome': return accessor(new Outcome())! as Outcome;
    case 'Checkpoint': return accessor(new Checkpoint())! as Checkpoint;
    case 'Supervisor': return accessor(new Supervisor())! as Supervisor;
    case 'Recovery': return accessor(new Recovery())! as Recovery;
    case 'IntentSet': return accessor(new IntentSet())! as IntentSet;
    case 'LoopOpened': return accessor(new LoopOpened())! as LoopOpened;
    case 'LoopClosed': return accessor(new LoopClosed())! as LoopClosed;
    case 'Assertion': return accessor(new Assertion())! as Assertion;
    case 'Consolidation': return accessor(new Consolidation())! as Consolidation;
    case 'Embedding': return accessor(new Embedding())! as Embedding;
    case 'Retract': return accessor(new Retract())! as Retract;
    case 'Attestation': return accessor(new Attestation())! as Attestation;
    case 'Binding': return accessor(new Binding())! as Binding;
    default: return null;
  }
}

export function unionListToEventPayload(
  type: EventPayload, 
  accessor: (index: number, obj:Approval|Assertion|Attestation|Binding|Checkpoint|Consolidation|DeliveredMsg|Effect|Embedding|IntentSet|LoopClosed|LoopOpened|MediaRef|Outcome|ProviderFrame|Reasoning|Recovery|Retract|Supervisor|ToolCall|ToolResult|UserMsg) => Approval|Assertion|Attestation|Binding|Checkpoint|Consolidation|DeliveredMsg|Effect|Embedding|IntentSet|LoopClosed|LoopOpened|MediaRef|Outcome|ProviderFrame|Reasoning|Recovery|Retract|Supervisor|ToolCall|ToolResult|UserMsg|null, 
  index: number
): Approval|Assertion|Attestation|Binding|Checkpoint|Consolidation|DeliveredMsg|Effect|Embedding|IntentSet|LoopClosed|LoopOpened|MediaRef|Outcome|ProviderFrame|Reasoning|Recovery|Retract|Supervisor|ToolCall|ToolResult|UserMsg|null {
  switch(EventPayload[type]) {
    case 'NONE': return null; 
    case 'UserMsg': return accessor(index, new UserMsg())! as UserMsg;
    case 'DeliveredMsg': return accessor(index, new DeliveredMsg())! as DeliveredMsg;
    case 'ToolCall': return accessor(index, new ToolCall())! as ToolCall;
    case 'ToolResult': return accessor(index, new ToolResult())! as ToolResult;
    case 'Reasoning': return accessor(index, new Reasoning())! as Reasoning;
    case 'ProviderFrame': return accessor(index, new ProviderFrame())! as ProviderFrame;
    case 'MediaRef': return accessor(index, new MediaRef())! as MediaRef;
    case 'Effect': return accessor(index, new Effect())! as Effect;
    case 'Approval': return accessor(index, new Approval())! as Approval;
    case 'Outcome': return accessor(index, new Outcome())! as Outcome;
    case 'Checkpoint': return accessor(index, new Checkpoint())! as Checkpoint;
    case 'Supervisor': return accessor(index, new Supervisor())! as Supervisor;
    case 'Recovery': return accessor(index, new Recovery())! as Recovery;
    case 'IntentSet': return accessor(index, new IntentSet())! as IntentSet;
    case 'LoopOpened': return accessor(index, new LoopOpened())! as LoopOpened;
    case 'LoopClosed': return accessor(index, new LoopClosed())! as LoopClosed;
    case 'Assertion': return accessor(index, new Assertion())! as Assertion;
    case 'Consolidation': return accessor(index, new Consolidation())! as Consolidation;
    case 'Embedding': return accessor(index, new Embedding())! as Embedding;
    case 'Retract': return accessor(index, new Retract())! as Retract;
    case 'Attestation': return accessor(index, new Attestation())! as Attestation;
    case 'Binding': return accessor(index, new Binding())! as Binding;
    default: return null;
  }
}
