// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class MediaRef {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MediaRef {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMediaRef(bb:flatbuffers.ByteBuffer, obj?:MediaRef):MediaRef {
  return (obj || new MediaRef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMediaRef(bb:flatbuffers.ByteBuffer, obj?:MediaRef):MediaRef {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MediaRef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

uri():string|null
uri(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uri(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mediaType():string|null
mediaType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mediaType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

digest(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

digestLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

digestArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startMediaRef(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addUri(builder:flatbuffers.Builder, uriOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, uriOffset, 0);
}

static addMediaType(builder:flatbuffers.Builder, mediaTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, mediaTypeOffset, 0);
}

static addDigest(builder:flatbuffers.Builder, digestOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, digestOffset, 0);
}

static createDigestVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDigestVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endMediaRef(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // uri
  builder.requiredField(offset, 6) // media_type
  builder.requiredField(offset, 8) // digest
  return offset;
}

static createMediaRef(builder:flatbuffers.Builder, uriOffset:flatbuffers.Offset, mediaTypeOffset:flatbuffers.Offset, digestOffset:flatbuffers.Offset):flatbuffers.Offset {
  MediaRef.startMediaRef(builder);
  MediaRef.addUri(builder, uriOffset);
  MediaRef.addMediaType(builder, mediaTypeOffset);
  MediaRef.addDigest(builder, digestOffset);
  return MediaRef.endMediaRef(builder);
}

unpack(): MediaRefT {
  return new MediaRefT(
    this.uri(),
    this.mediaType(),
    this.bb!.createScalarList(this.digest.bind(this), this.digestLength())
  );
}


unpackTo(_o: MediaRefT): void {
  _o.uri = this.uri();
  _o.mediaType = this.mediaType();
  _o.digest = this.bb!.createScalarList(this.digest.bind(this), this.digestLength());
}
}

export class MediaRefT {
constructor(
  public uri: string|Uint8Array|null = null,
  public mediaType: string|Uint8Array|null = null,
  public digest: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const uri = (this.uri !== null ? builder.createString(this.uri!) : 0);
  const mediaType = (this.mediaType !== null ? builder.createString(this.mediaType!) : 0);
  const digest = MediaRef.createDigestVector(builder, this.digest);

  return MediaRef.createMediaRef(builder,
    uri,
    mediaType,
    digest
  );
}
}
