// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ResultStatus } from '../../hypermind/schema/result-status';


export class Outcome {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Outcome {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOutcome(bb:flatbuffers.ByteBuffer, obj?:Outcome):Outcome {
  return (obj || new Outcome()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOutcome(bb:flatbuffers.ByteBuffer, obj?:Outcome):Outcome {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Outcome()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

effectId(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

effectIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

effectIdArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

status():ResultStatus {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ResultStatus.ok;
}

detail(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

detailLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

detailArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

evidenceLsns(index: number):bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
}

evidenceLsnsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startOutcome(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addEffectId(builder:flatbuffers.Builder, effectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, effectIdOffset, 0);
}

static createEffectIdVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startEffectIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addStatus(builder:flatbuffers.Builder, status:ResultStatus) {
  builder.addFieldInt8(1, status, ResultStatus.ok);
}

static addDetail(builder:flatbuffers.Builder, detailOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, detailOffset, 0);
}

static createDetailVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDetailVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addEvidenceLsns(builder:flatbuffers.Builder, evidenceLsnsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, evidenceLsnsOffset, 0);
}

static createEvidenceLsnsVector(builder:flatbuffers.Builder, data:bigint[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startEvidenceLsnsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static endOutcome(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // effect_id
  builder.requiredField(offset, 8) // detail
  return offset;
}

static createOutcome(builder:flatbuffers.Builder, effectIdOffset:flatbuffers.Offset, status:ResultStatus, detailOffset:flatbuffers.Offset, evidenceLsnsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Outcome.startOutcome(builder);
  Outcome.addEffectId(builder, effectIdOffset);
  Outcome.addStatus(builder, status);
  Outcome.addDetail(builder, detailOffset);
  Outcome.addEvidenceLsns(builder, evidenceLsnsOffset);
  return Outcome.endOutcome(builder);
}

unpack(): OutcomeT {
  return new OutcomeT(
    this.bb!.createScalarList(this.effectId.bind(this), this.effectIdLength()),
    this.status(),
    this.bb!.createScalarList(this.detail.bind(this), this.detailLength()),
    this.bb!.createScalarList(this.evidenceLsns.bind(this), this.evidenceLsnsLength())
  );
}


unpackTo(_o: OutcomeT): void {
  _o.effectId = this.bb!.createScalarList(this.effectId.bind(this), this.effectIdLength());
  _o.status = this.status();
  _o.detail = this.bb!.createScalarList(this.detail.bind(this), this.detailLength());
  _o.evidenceLsns = this.bb!.createScalarList(this.evidenceLsns.bind(this), this.evidenceLsnsLength());
}
}

export class OutcomeT {
constructor(
  public effectId: (number)[] = [],
  public status: ResultStatus = ResultStatus.ok,
  public detail: (number)[] = [],
  public evidenceLsns: (bigint)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const effectId = Outcome.createEffectIdVector(builder, this.effectId);
  const detail = Outcome.createDetailVector(builder, this.detail);
  const evidenceLsns = Outcome.createEvidenceLsnsVector(builder, this.evidenceLsns);

  return Outcome.createOutcome(builder,
    effectId,
    this.status,
    detail,
    evidenceLsns
  );
}
}
