// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { AssertionClaim } from '../../hypermind/schema/assertion-claim';
import { BeliefType } from '../../hypermind/schema/belief-type';
import { ProvenanceRange, ProvenanceRangeT } from '../../hypermind/schema/provenance-range';


export class ProposedAssertion {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProposedAssertion {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProposedAssertion(bb:flatbuffers.ByteBuffer, obj?:ProposedAssertion):ProposedAssertion {
  return (obj || new ProposedAssertion()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProposedAssertion(bb:flatbuffers.ByteBuffer, obj?:ProposedAssertion):ProposedAssertion {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProposedAssertion()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

beliefId(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

beliefIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

beliefIdArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

beliefType():BeliefType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BeliefType.fact;
}

canonicalIdentity():string|null
canonicalIdentity(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
canonicalIdentity(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

value(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

valueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

valueArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

validFromNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

validToNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

provenance(index: number, obj?:ProvenanceRange):ProvenanceRange|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new ProvenanceRange()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 24, this.bb!) : null;
}

provenanceLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

conflictDomain():string|null
conflictDomain(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
conflictDomain(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

claim():AssertionClaim {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssertionClaim.affirmative;
}

static startProposedAssertion(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addBeliefId(builder:flatbuffers.Builder, beliefIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, beliefIdOffset, 0);
}

static createBeliefIdVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startBeliefIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addBeliefType(builder:flatbuffers.Builder, beliefType:BeliefType) {
  builder.addFieldInt8(1, beliefType, BeliefType.fact);
}

static addCanonicalIdentity(builder:flatbuffers.Builder, canonicalIdentityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, canonicalIdentityOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, valueOffset, 0);
}

static createValueVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addValidFromNs(builder:flatbuffers.Builder, validFromNs:bigint) {
  builder.addFieldInt64(4, validFromNs, BigInt('0'));
}

static addValidToNs(builder:flatbuffers.Builder, validToNs:bigint) {
  builder.addFieldInt64(5, validToNs, BigInt('0'));
}

static addProvenance(builder:flatbuffers.Builder, provenanceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, provenanceOffset, 0);
}

static startProvenanceVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(24, numElems, 8);
}

static addConflictDomain(builder:flatbuffers.Builder, conflictDomainOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, conflictDomainOffset, 0);
}

static addClaim(builder:flatbuffers.Builder, claim:AssertionClaim) {
  builder.addFieldInt8(8, claim, AssertionClaim.affirmative);
}

static endProposedAssertion(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // belief_id
  builder.requiredField(offset, 8) // canonical_identity
  builder.requiredField(offset, 10) // value
  builder.requiredField(offset, 16) // provenance
  return offset;
}

static createProposedAssertion(builder:flatbuffers.Builder, beliefIdOffset:flatbuffers.Offset, beliefType:BeliefType, canonicalIdentityOffset:flatbuffers.Offset, valueOffset:flatbuffers.Offset, validFromNs:bigint, validToNs:bigint, provenanceOffset:flatbuffers.Offset, conflictDomainOffset:flatbuffers.Offset, claim:AssertionClaim):flatbuffers.Offset {
  ProposedAssertion.startProposedAssertion(builder);
  ProposedAssertion.addBeliefId(builder, beliefIdOffset);
  ProposedAssertion.addBeliefType(builder, beliefType);
  ProposedAssertion.addCanonicalIdentity(builder, canonicalIdentityOffset);
  ProposedAssertion.addValue(builder, valueOffset);
  ProposedAssertion.addValidFromNs(builder, validFromNs);
  ProposedAssertion.addValidToNs(builder, validToNs);
  ProposedAssertion.addProvenance(builder, provenanceOffset);
  ProposedAssertion.addConflictDomain(builder, conflictDomainOffset);
  ProposedAssertion.addClaim(builder, claim);
  return ProposedAssertion.endProposedAssertion(builder);
}

unpack(): ProposedAssertionT {
  return new ProposedAssertionT(
    this.bb!.createScalarList(this.beliefId.bind(this), this.beliefIdLength()),
    this.beliefType(),
    this.canonicalIdentity(),
    this.bb!.createScalarList(this.value.bind(this), this.valueLength()),
    this.validFromNs(),
    this.validToNs(),
    this.bb!.createObjList(this.provenance.bind(this), this.provenanceLength()),
    this.conflictDomain(),
    this.claim()
  );
}


unpackTo(_o: ProposedAssertionT): void {
  _o.beliefId = this.bb!.createScalarList(this.beliefId.bind(this), this.beliefIdLength());
  _o.beliefType = this.beliefType();
  _o.canonicalIdentity = this.canonicalIdentity();
  _o.value = this.bb!.createScalarList(this.value.bind(this), this.valueLength());
  _o.validFromNs = this.validFromNs();
  _o.validToNs = this.validToNs();
  _o.provenance = this.bb!.createObjList(this.provenance.bind(this), this.provenanceLength());
  _o.conflictDomain = this.conflictDomain();
  _o.claim = this.claim();
}
}

export class ProposedAssertionT {
constructor(
  public beliefId: (number)[] = [],
  public beliefType: BeliefType = BeliefType.fact,
  public canonicalIdentity: string|Uint8Array|null = null,
  public value: (number)[] = [],
  public validFromNs: bigint = BigInt('0'),
  public validToNs: bigint = BigInt('0'),
  public provenance: (ProvenanceRangeT)[] = [],
  public conflictDomain: string|Uint8Array|null = null,
  public claim: AssertionClaim = AssertionClaim.affirmative
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const beliefId = ProposedAssertion.createBeliefIdVector(builder, this.beliefId);
  const canonicalIdentity = (this.canonicalIdentity !== null ? builder.createString(this.canonicalIdentity!) : 0);
  const value = ProposedAssertion.createValueVector(builder, this.value);
  const provenance = builder.createStructOffsetList(this.provenance, ProposedAssertion.startProvenanceVector);
  const conflictDomain = (this.conflictDomain !== null ? builder.createString(this.conflictDomain!) : 0);

  return ProposedAssertion.createProposedAssertion(builder,
    beliefId,
    this.beliefType,
    canonicalIdentity,
    value,
    this.validFromNs,
    this.validToNs,
    provenance,
    conflictDomain,
    this.claim
  );
}
}
