// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ProvenanceRange {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProvenanceRange {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

firstLsn():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

lastLsn():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createProvenanceRange(builder:flatbuffers.Builder, first_lsn: bigint, last_lsn: bigint):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeInt64(last_lsn);
  builder.writeInt64(first_lsn);
  return builder.offset();
}


unpack(): ProvenanceRangeT {
  return new ProvenanceRangeT(
    this.firstLsn(),
    this.lastLsn()
  );
}


unpackTo(_o: ProvenanceRangeT): void {
  _o.firstLsn = this.firstLsn();
  _o.lastLsn = this.lastLsn();
}
}

export class ProvenanceRangeT {
constructor(
  public firstLsn: bigint = BigInt('0'),
  public lastLsn: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ProvenanceRange.createProvenanceRange(builder,
    this.firstLsn,
    this.lastLsn
  );
}
}
