// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ProviderFrame {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProviderFrame {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProviderFrame(bb:flatbuffers.ByteBuffer, obj?:ProviderFrame):ProviderFrame {
  return (obj || new ProviderFrame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProviderFrame(bb:flatbuffers.ByteBuffer, obj?:ProviderFrame):ProviderFrame {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProviderFrame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

provider():string|null
provider(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
provider(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

apiContent(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

apiContentLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

apiContentArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startProviderFrame(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addProvider(builder:flatbuffers.Builder, providerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, providerOffset, 0);
}

static addApiContent(builder:flatbuffers.Builder, apiContentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, apiContentOffset, 0);
}

static createApiContentVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startApiContentVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endProviderFrame(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // provider
  builder.requiredField(offset, 6) // api_content
  return offset;
}

static createProviderFrame(builder:flatbuffers.Builder, providerOffset:flatbuffers.Offset, apiContentOffset:flatbuffers.Offset):flatbuffers.Offset {
  ProviderFrame.startProviderFrame(builder);
  ProviderFrame.addProvider(builder, providerOffset);
  ProviderFrame.addApiContent(builder, apiContentOffset);
  return ProviderFrame.endProviderFrame(builder);
}

unpack(): ProviderFrameT {
  return new ProviderFrameT(
    this.provider(),
    this.bb!.createScalarList(this.apiContent.bind(this), this.apiContentLength())
  );
}


unpackTo(_o: ProviderFrameT): void {
  _o.provider = this.provider();
  _o.apiContent = this.bb!.createScalarList(this.apiContent.bind(this), this.apiContentLength());
}
}

export class ProviderFrameT {
constructor(
  public provider: string|Uint8Array|null = null,
  public apiContent: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const provider = (this.provider !== null ? builder.createString(this.provider!) : 0);
  const apiContent = ProviderFrame.createApiContentVector(builder, this.apiContent);

  return ProviderFrame.createProviderFrame(builder,
    provider,
    apiContent
  );
}
}
