// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Reasoning {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Reasoning {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReasoning(bb:flatbuffers.ByteBuffer, obj?:Reasoning):Reasoning {
  return (obj || new Reasoning()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReasoning(bb:flatbuffers.ByteBuffer, obj?:Reasoning):Reasoning {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Reasoning()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

content(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

contentLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

contentArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startReasoning(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, contentOffset, 0);
}

static createContentVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startContentVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endReasoning(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // content
  return offset;
}

static createReasoning(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset):flatbuffers.Offset {
  Reasoning.startReasoning(builder);
  Reasoning.addContent(builder, contentOffset);
  return Reasoning.endReasoning(builder);
}

unpack(): ReasoningT {
  return new ReasoningT(
    this.bb!.createScalarList(this.content.bind(this), this.contentLength())
  );
}


unpackTo(_o: ReasoningT): void {
  _o.content = this.bb!.createScalarList(this.content.bind(this), this.contentLength());
}
}

export class ReasoningT {
constructor(
  public content: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const content = Reasoning.createContentVector(builder, this.content);

  return Reasoning.createReasoning(builder,
    content
  );
}
}
