// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Recovery {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Recovery {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRecovery(bb:flatbuffers.ByteBuffer, obj?:Recovery):Recovery {
  return (obj || new Recovery()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRecovery(bb:flatbuffers.ByteBuffer, obj?:Recovery):Recovery {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Recovery()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():string|null
code(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
code(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

targetLsn():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startRecovery(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCode(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, codeOffset, 0);
}

static addTargetLsn(builder:flatbuffers.Builder, targetLsn:bigint) {
  builder.addFieldInt64(1, targetLsn, BigInt('0'));
}

static endRecovery(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // code
  return offset;
}

static createRecovery(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset, targetLsn:bigint):flatbuffers.Offset {
  Recovery.startRecovery(builder);
  Recovery.addCode(builder, codeOffset);
  Recovery.addTargetLsn(builder, targetLsn);
  return Recovery.endRecovery(builder);
}

unpack(): RecoveryT {
  return new RecoveryT(
    this.code(),
    this.targetLsn()
  );
}


unpackTo(_o: RecoveryT): void {
  _o.code = this.code();
  _o.targetLsn = this.targetLsn();
}
}

export class RecoveryT {
constructor(
  public code: string|Uint8Array|null = null,
  public targetLsn: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const code = (this.code !== null ? builder.createString(this.code!) : 0);

  return Recovery.createRecovery(builder,
    code,
    this.targetLsn
  );
}
}
