use super::*;
use fs2::FileExt;
use std::{fs::{File,OpenOptions},io::{Read,Write},process::{Command,Stdio},thread,time::Instant};
#[derive(Serialize,Deserialize)]
struct OwnedUnit {receipt:ServiceReceipt,unit:String}
pub struct LinuxServiceManager {records:PathBuf,units:PathBuf,scope:Scope,trusted:VerifyingKey}
struct NativeOutput {success:bool,text:String}
fn native(args:&[&str],timeout:Duration)->Result<NativeOutput,ServiceError> {
 let mut child=Command::new("/usr/bin/systemctl").arg("--user").args(args).stdin(Stdio::null()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().map_err(|e|ServiceError::Unavailable(e.to_string()))?;
 let deadline=Instant::now()+timeout;let status=loop {if let Some(status)=child.try_wait()?{break status;}if Instant::now()>=deadline{let _=child.kill();let _=child.wait();return Err(ServiceError::Timeout(format!("systemctl --user {}",args.join(" "))));}thread::sleep(Duration::from_millis(10));};
 let mut stdout=Vec::new();let mut stderr=Vec::new();if let Some(pipe)=child.stdout.take(){pipe.take(16385).read_to_end(&mut stdout)?;}if let Some(pipe)=child.stderr.take(){pipe.take(16385).read_to_end(&mut stderr)?;}if stdout.len()>16384 || stderr.len()>16384{return Err(ServiceError::Native("native response exceeded bounds".into()));}
 let text=format!("{}{}",String::from_utf8_lossy(&stdout),String::from_utf8_lossy(&stderr));Ok(NativeOutput{success:status.success(),text})
}
fn checked(args:&[&str])->Result<String,ServiceError>{let result=native(args,Duration::from_secs(15))?;if !result.success{return Err(ServiceError::Native(result.text));}Ok(result.text)}
fn quote(value:&str,exec:bool)->Result<String,ServiceError>{if value.contains('\0'){return Err(ServiceError::Invalid("NUL in unit argument".into()));}let mut out=String::from("\"");for c in value.chars(){match c{'"'=>out.push_str("\\\""),'\\'=>out.push_str("\\\\"),'\n'=>out.push_str("\\n"),'\r'=>out.push_str("\\r"),'\t'=>out.push_str("\\t"),'%'=>out.push_str("%%"),'$' if exec=>out.push_str("$$"),c if c.is_control()=>return Err(ServiceError::Invalid("control character in unit argument".into())),c=>out.push(c)}}out.push('"');Ok(out)}
impl LinuxServiceManager {
 pub fn availability()->Result<String,ServiceError>{let output=native(&["show","--property=Version"],Duration::from_secs(5))?;if !output.success{return Err(ServiceError::Unavailable(output.text));}if !output.text.starts_with("Version="){return Err(ServiceError::Unavailable("native user manager did not report a version".into()));}Ok(output.text.trim().into())}
 pub fn open(records:PathBuf,scope:Scope,trusted:VerifyingKey)->Result<Self,ServiceError>{Self::availability()?;scope.validate().map_err(|e|ServiceError::Invalid(e.to_string()))?;let home=std::env::var_os("HOME").ok_or_else(||ServiceError::Unavailable("HOME is not configured".into()))?;let home=fs::canonicalize(home)?;let units=home.join(".config/systemd/user");fs::create_dir_all(&units)?;let units=fs::canonicalize(units)?;
  if records.exists()&&fs::symlink_metadata(&records)?.file_type().is_symlink(){return Err(ServiceError::Ownership("receipt directory is a symlink".into()));}fs::create_dir_all(&records)?;let records=fs::canonicalize(records)?;Ok(Self{records,units,scope,trusted})}
 fn lock(&self)->Result<File,ServiceError>{let path=self.records.join("writer.lock");if path.exists()&&fs::symlink_metadata(&path)?.file_type().is_symlink(){return Err(ServiceError::Ownership("writer lock is a symlink".into()));}let file=OpenOptions::new().create(true).truncate(false).read(true).write(true).open(path)?;file.lock_exclusive()?;Ok(file)}
 fn properties(&self,name:&str)->Result<BTreeMap<String,String>,ServiceError>{let output=native(&["show",name,"--property=LoadState,FragmentPath,ActiveState,SubState,MainPID,NRestarts,ControlGroup,Result"],Duration::from_secs(5))?;let props=output.text.lines().filter_map(|s|s.split_once('=')).map(|(k,v)|(k.into(),v.into())).collect::<BTreeMap<String,String>>();if !output.success&&props.get("LoadState").is_none_or(|s|s!="not-found"){return Err(ServiceError::Native(output.text));}Ok(props)}
 fn record_path(&self,name:&str)->PathBuf{self.records.join(format!("{name}.json"))}
 fn verify_receipt(&self,receipt:&ServiceReceipt)->Result<OwnedUnit,ServiceError>{
  if receipt.scope!=self.scope||!receipt.service_name.starts_with("hypermind-")||!receipt.service_name.ends_with(".service")||receipt.service_name.len()!=58||!receipt.service_name.as_bytes()[10..50].iter().all(|b|b.is_ascii_hexdigit())||receipt.unit_path!=self.units.join(&receipt.service_name)||receipt.backend!="systemd-user"{return Err(ServiceError::Ownership("receipt identity mismatch".into()));}
  let path=self.record_path(&receipt.service_name);if fs::symlink_metadata(&path)?.file_type().is_symlink()||fs::metadata(&path)?.len()>1024*1024{return Err(ServiceError::Ownership("receipt file invalid".into()));}let record:OwnedUnit=serde_json::from_slice(&fs::read(path)?)?;if &record.receipt!=receipt{return Err(ServiceError::Ownership("receipt differs from owned registration".into()));}
  if fs::symlink_metadata(&receipt.unit_path)?.file_type().is_symlink()||digest_bytes(&fs::read(&receipt.unit_path)?)!=receipt.unit_digest||digest_bytes(record.unit.as_bytes())!=receipt.unit_digest{return Err(ServiceError::Ownership("native unit content changed".into()));}
  let properties=self.properties(&receipt.service_name)?;if properties.get("FragmentPath").is_none_or(|p|PathBuf::from(p)!=receipt.unit_path){return Err(ServiceError::Ownership("native fragment path changed".into()));}Ok(record)
 }
 pub fn preview_service(&self,spec:&ServiceSpec,owner:&str)->Result<ServicePlan,ServiceError>{
  let _lock=self.lock()?;spec.artifact.verify(&self.scope,&self.trusted)?;if spec.artifact.ownership.owner!=owner||spec.reviewed_capabilities!=spec.artifact.manifest().capabilities{return Err(ServiceError::Ownership("owner or capability review mismatch".into()));}
  if spec.restart_limit==0||spec.restart_limit>16||spec.restart_delay<Duration::from_millis(50)||spec.restart_delay>Duration::from_secs(60)||spec.restart_window.is_zero()||spec.restart_window>Duration::from_secs(3600)||spec.stop_timeout.is_zero()||spec.stop_timeout>Duration::from_secs(30){return Err(ServiceError::Invalid("restart or drain bounds invalid".into()));}
  let name=service_name(&self.scope,owner,&spec.service_key)?;let path=self.units.join(&name);if path.exists()||self.record_path(&name).exists(){return Err(ServiceError::Ownership("isolated service name already registered".into()));}let props=self.properties(&name)?;if props.get("LoadState").is_some_and(|s|s!="not-found"){return Err(ServiceError::Ownership("native service name already owned elsewhere".into()));}
  let manifest=spec.artifact.manifest();if manifest.env.keys().any(|k|k.starts_with("LD_")||k.starts_with("MALLOC_")||["GLIBC_TUNABLES","GCONV_PATH","LOCPATH","ENV","BASH_ENV","SHELLOPTS","IFS","INVOCATION_ID","SYSTEMD_EXEC_PID","NOTIFY_SOCKET","LISTEN_FDS","LISTEN_PID"].contains(&k.as_str())){return Err(ServiceError::Invalid("privileged launcher environment refused".into()));}
  let command=crate::containment::prepare_command(&spec.containment,&spec.artifact.payload_root.join(&manifest.command),&manifest.args,&spec.artifact.payload_root).map_err(|e|ServiceError::Unavailable(e.to_string()))?;
  let mut args=vec![quote(command.get_program().to_str().ok_or_else(||ServiceError::Invalid("non UTF-8 executable".into()))?,true)?];for arg in command.get_args(){args.push(quote(arg.to_str().ok_or_else(||ServiceError::Invalid("non UTF-8 argument".into()))?,true)?);}
  let mut unit=format!("[Unit]\nDescription=HyperMind owned module service\nStartLimitIntervalSec={}ms\nStartLimitBurst={}\n\n[Service]\nType=exec\nExecStart={}\nRestart=on-failure\nRestartSec={}ms\nTimeoutStopSec={}ms\nKillMode=control-group\nSendSIGKILL=yes\n\n",spec.restart_window.as_millis(),spec.restart_limit,args.join(" "),spec.restart_delay.as_millis(),spec.stop_timeout.as_millis());
  for (key,value) in &manifest.env{unit.push_str(&format!("Environment={}\n",quote(&format!("{key}={value}"),false)?));}
  unit.push_str("\n[Install]\nWantedBy=default.target\n");
  let receipt=ServiceReceipt{scope:self.scope.clone(),owner:owner.into(),service_name:name,unit_path:path,unit_digest:digest_bytes(unit.as_bytes()),artifact:spec.artifact.ownership.clone(),backend:"systemd-user".into()};let digest=digest_bytes(&serde_json::to_vec(&(&receipt,&unit))?);Ok(ServicePlan{receipt,unit,digest,artifact:spec.artifact.clone()})
 }
 pub fn install(&self,plan:&ServicePlan,expected_digest:&str,owner:&str)->Result<ServiceReceipt,ServiceError>{let _lock=self.lock()?;
  if plan.digest!=expected_digest||digest_bytes(&serde_json::to_vec(&(&plan.receipt,&plan.unit))?)!=expected_digest||plan.receipt.owner!=owner||plan.receipt.scope!=self.scope||plan.receipt.unit_path!=self.units.join(&plan.receipt.service_name){return Err(ServiceError::Ownership("reviewed service plan changed".into()));}plan.artifact.verify(&self.scope,&self.trusted)?;
  if plan.receipt.unit_path.exists()||self.record_path(&plan.receipt.service_name).exists()||self.properties(&plan.receipt.service_name)?.get("LoadState").is_some_and(|s|s!="not-found"){return Err(ServiceError::Ownership("service registration changed since preview".into()));}
  let mut file=OpenOptions::new().write(true).create_new(true).open(&plan.receipt.unit_path)?;file.write_all(plan.unit.as_bytes())?;file.sync_all()?;File::open(&self.units)?.sync_all()?;
  let record=OwnedUnit{receipt:plan.receipt.clone(),unit:plan.unit.clone()};let record_path=self.record_path(&plan.receipt.service_name);let mut file=OpenOptions::new().write(true).create_new(true).open(record_path)?;file.write_all(&serde_json::to_vec(&record)?)?;file.sync_all()?;File::open(&self.records)?.sync_all()?;
  checked(&["daemon-reload"])?;checked(&["enable",&plan.receipt.service_name])?;checked(&["start",&plan.receipt.service_name])?;self.verify_receipt(&plan.receipt)?;Ok(plan.receipt.clone())
 }
 pub fn status(&self,receipt:&ServiceReceipt)->Result<ServiceStatus,ServiceError>{let _lock=self.lock()?;self.verify_receipt(receipt)?;let p=self.properties(&receipt.service_name)?;Ok(ServiceStatus{active_state:p.get("ActiveState").cloned().unwrap_or_default(),sub_state:p.get("SubState").cloned().unwrap_or_default(),main_pid:p.get("MainPID").and_then(|s|s.parse().ok()).unwrap_or(0),restarts:p.get("NRestarts").and_then(|s|s.parse().ok()).unwrap_or(0),control_group:p.get("ControlGroup").cloned().unwrap_or_default(),native_result:p.get("Result").cloned().unwrap_or_default()})}
 pub fn stop(&self,receipt:&ServiceReceipt)->Result<(),ServiceError>{let _lock=self.lock()?;self.stop_owned(receipt)}
 fn stop_owned(&self,receipt:&ServiceReceipt)->Result<(),ServiceError>{self.verify_receipt(receipt)?;let before=self.properties(&receipt.service_name)?;let group=before.get("ControlGroup").cloned().unwrap_or_default();checked(&["stop",&receipt.service_name])?;let props=self.properties(&receipt.service_name)?;
  if props.get("MainPID").is_some_and(|v|v!="0")||props.get("ActiveState").is_none_or(|v|v!="inactive"&&v!="failed"){return Err(ServiceError::Native("native service did not stop".into()));}
  if !group.is_empty(){if !group.starts_with('/')||group.split('/').any(|p|p==".."){return Err(ServiceError::Ownership("invalid owned control group".into()));}let events=PathBuf::from("/sys/fs/cgroup").join(group.trim_start_matches('/')).join("cgroup.events");if events.exists()&&fs::read_to_string(events)?.lines().any(|line|line=="populated 1"){return Err(ServiceError::Native("owned service still has child processes".into()));}}
  Ok(())
 }
 pub fn uninstall(&self,receipt:&ServiceReceipt,owner:&str)->Result<(),ServiceError>{let _lock=self.lock()?;if receipt.owner!=owner{return Err(ServiceError::Ownership("uninstall owner mismatch".into()));}self.stop_owned(receipt)?;self.verify_receipt(receipt)?;checked(&["disable",&receipt.service_name])?;fs::remove_file(&receipt.unit_path)?;File::open(&self.units)?.sync_all()?;checked(&["daemon-reload"])?;fs::remove_file(self.record_path(&receipt.service_name))?;File::open(&self.records)?.sync_all()?;Ok(())}
}
