# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hypermind_pb2 as hypermind__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hypermind_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HyperMindStub(object):
    """Frozen v3 transport: each byte field is a complete NCPR WireEnvelope, without
    the Unix socket length/CRC prefix. Existing v2 envelopes remain compatible.
    TLS client certificates and the Hello capability token are both mandatory.
    Actor and admin listeners are separate; a listener never accepts both roles.
    Transport errors carry effect-state metadata (not_dispatched or unknown).
    Application errors retain their NCPR ErrorDetail, including effect_state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/hypermind.v3.HyperMind/Connect',
                request_serializer=hypermind__pb2.Envelope.SerializeToString,
                response_deserializer=hypermind__pb2.Envelope.FromString,
                _registered_method=True)
        self.Exchange = channel.unary_unary(
                '/hypermind.v3.HyperMind/Exchange',
                request_serializer=hypermind__pb2.ExchangeRequest.SerializeToString,
                response_deserializer=hypermind__pb2.Envelope.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/hypermind.v3.HyperMind/Subscribe',
                request_serializer=hypermind__pb2.ExchangeRequest.SerializeToString,
                response_deserializer=hypermind__pb2.Envelope.FromString,
                _registered_method=True)


class HyperMindServicer(object):
    """Frozen v3 transport: each byte field is a complete NCPR WireEnvelope, without
    the Unix socket length/CRC prefix. Existing v2 envelopes remain compatible.
    TLS client certificates and the Hello capability token are both mandatory.
    Actor and admin listeners are separate; a listener never accepts both roles.
    Transport errors carry effect-state metadata (not_dispatched or unknown).
    Application errors retain their NCPR ErrorDetail, including effect_state.
    """

    def Connect(self, request, context):
        """Validates Hello and returns Welcome, including the durable next_client_seq.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exchange(self, request, context):
        """Reuses the Hello connection_id for durable idempotency across RPCs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """The request must contain Subscribe. First response is SubscriptionAck,
        followed by unchanged NCPR Event envelopes. Resume using the last LSN.
        A saturated bounded queue terminates with RESOURCE_EXHAUSTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HyperMindServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=hypermind__pb2.Envelope.FromString,
                    response_serializer=hypermind__pb2.Envelope.SerializeToString,
            ),
            'Exchange': grpc.unary_unary_rpc_method_handler(
                    servicer.Exchange,
                    request_deserializer=hypermind__pb2.ExchangeRequest.FromString,
                    response_serializer=hypermind__pb2.Envelope.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=hypermind__pb2.ExchangeRequest.FromString,
                    response_serializer=hypermind__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hypermind.v3.HyperMind', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hypermind.v3.HyperMind', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HyperMind(object):
    """Frozen v3 transport: each byte field is a complete NCPR WireEnvelope, without
    the Unix socket length/CRC prefix. Existing v2 envelopes remain compatible.
    TLS client certificates and the Hello capability token are both mandatory.
    Actor and admin listeners are separate; a listener never accepts both roles.
    Transport errors carry effect-state metadata (not_dispatched or unknown).
    Application errors retain their NCPR ErrorDetail, including effect_state.
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypermind.v3.HyperMind/Connect',
            hypermind__pb2.Envelope.SerializeToString,
            hypermind__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypermind.v3.HyperMind/Exchange',
            hypermind__pb2.ExchangeRequest.SerializeToString,
            hypermind__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hypermind.v3.HyperMind/Subscribe',
            hypermind__pb2.ExchangeRequest.SerializeToString,
            hypermind__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
