[package]
name = "hm-index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hm-core = { path = "../hm-core" }
tantivy = { version = "0.25.0", default-features = false }
wide = "0.8.1"

[lints]
workspace = true
